### ISSUE TITLE
建议不要UI版不要输入验证码，难道害怕别人给我挖矿不成？

### ISSUE THREAD

**Issue by rootdgy** [hpool-dev/chia-miner#10]
参考各种挖矿软件，建议不需输入验证码

**Comment by h9-dev** [comment]
> 参考各种挖矿软件，建议不需输入验证码

多谢反馈。不输入验证码容易照成您的帐号密码通过此接口被机器人暴力破解，我们通常建议使用命令行版本的 miner 软件。
