### ISSUE TITLE
1.1.1 多文件夹，修改yaml config后会重复添加

### ISSUE THREAD

**Issue by phyerbarte** [hpool-dev/chia-miner#102]
容量也会被重复计算，我有15T，显示30T，池子反而显示我只有800G，这是被判定重复挖？能否修复这个bug，有时候改文件路径不方便啊。

**Comment by trying2016** [comment]
v.1.2.0 版本修复了该问题 
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
