### ISSUE TITLE
IN ENGLISH, please

### ISSUE THREAD

**Issue by MikhailZelenkov** [hpool-dev/chia-miner#103]
Friends! We, of course, understand that the developers are from China, but the world community using your pool and your developments would like you to write IN ENGLISH.

**Comment by zc2174** [comment]
if u want to use it, learn CHINESE; otherwise, FXXK off

**Comment by Daewju** [comment]
Programming and therefore also the issues should be written in English. This is an unwritten law worldwide.
But the only open source file here is the README.md anyway ...

**Comment by MikhailZelenkov** [comment]
> if u want to use it, learn CHINESE; otherwise, FXXK off

Нахуй иди сам! С русскими не стоит так разговарить!

**Comment by zc2174** [comment]
> > if u want to use it, learn CHINESE; otherwise, FXXK off
> 
> Нахуй иди сам! С русскими не стоит так разговарить!

傻逼 俄狗

**Comment by trying2016** [comment]
1. Increase arm, aarch64 version
2. Increase the English version, switch in the settings
3. Increase display capacity, scan time and scan consumption information in the log
4. Improve Miner stability
Note: Miner will automatically go offline if the scan time exceeds 10s. If your scan time exceeds 10s, please check whether the hardware is normal
If you have any questions or need technical support, please contact the official customer service WeChat: 17717291449
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1

**Comment by ghost** [comment]
не злись, Может он не знает что брат ты русский. 友谊长存 :)

**Comment by SNGDude** [comment]
> if u want to use it, learn CHINESE; otherwise, FXXK off

be kind
