### ISSUE TITLE
1.1.1 问题

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#109]
panic: reflect: call of reflect.Value.IsNil on zero Value [recovered]
        panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 291 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000cbab20)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:326 +0x85
panic(0x9c4780, 0xc0007262a0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/panic.go:969 +0x1b9
reflect.Value.IsNil(...)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/reflect/value.go:1086
encoding/json.interfaceEncoder(0xc000ab0080, 0x0, 0x0, 0x0, 0xc000b00100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:710 +0x17f
encoding/json.mapEncoder.encode(0xa6dea8, 0xc000ab0080, 0xa19340, 0xc000e84420, 0x15, 0xa10100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:801 +0x35c
encoding/json.(*encodeState).reflectValue(0xc000ab0080, 0xa19340, 0xc000e84420, 0x15, 0xc000cb0100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc000ab0080, 0xa19340, 0xc000e84420, 0xfc970100, 0x0, 0x0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:330 +0xf4
encoding/json.Marshal(0xa19340, 0xc000e84420, 0xa48b24, 0x6, 0xc00073d058, 0x0, 0x0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:161 +0x52
github.com/trying2016/common-tools/utils.Map.ToJson(...)
        vendor/github.com/trying2016/common-tools/utils/map.go:51
hpool.com/dev/miner-client/miner/server/websocket.(*Server).Send(0xc00012a180, 0xa4a811, 0x8, 0xc000cbacc0, 0xc000cbac90)
        miner/server/websocket/server.go:144 +0x270
hpool.com/dev/miner-client/miner/server/websocket.(*Server).keepLive(...)
        miner/server/websocket/server.go:58
hpool.com/dev/miner-client/miner/server/websocket.(*Server).check(0xc00012a180)
        miner/server/websocket/server.go:53 +0x1d0
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc00049a560, 0xc00040e080)
        vendor/github.com/trying2016/common-tools/utils/timer.go:26 +0x3e
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.1.1
**** BuildTime:2021-05-02-15:57:33 GMT
**** MinerName:xxxxxxxxxx
***************************************************
INFO[2021-05-06T02:48:39-07:00] pool public key: [hide] 
file=loggers.go func=logging.CPrint line=168 tid=52
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb6 pc=0x423fc8]

runtime stack:
runtime.throw(0xa5ef17, 0x2a)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/signal_unix.go:726 +0x4ac
runtime.gcResetMarkState()
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/mgc.go:2214 +0x48
runtime.systemstack(0x0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/proc.go:1116

goroutine 157 [running]:
runtime.systemstack_switch()
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/asm_amd64.s:330 fp=0xc000283a70 sp=0xc000283a68 pc=0x473cc0
runtime.gcStart(0x0, 0x0, 0xc000000000)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/mgc.go:1298 +0x1da fp=0xc000283ae8 sp=0xc000283a70 pc=0x421dfa
runtime.mallocgc(0x20, 0x9ab700, 0x13c6701, 0x13c5b40)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/malloc.go:1153 +0x470 fp=0xc000283b88 sp=0xc000283ae8 pc=0x413bf0
runtime.makeslice(0x9ab700, 0x20, 0x20, 0x40)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/slice.go:98 +0x6c fp=0xc000283bb8 sp=0xc000283b88 pc=0x454dac
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetQualitiesForChallenge(0xc000708000, 0xc00070c000, 0x20, 0x40, 0x0, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:227 +0x193 fp=0xc000283c58 sp=0xc000283bb8 pc=0x7b91d3
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc0007061c0, 0x68, 0xc000283e00, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:89 +0x1da fp=0xc000283cf0 sp=0xc000283c58 pc=0x7b863a
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc0005720f0, 0xc00028c290, 0x8, 0x1)
        miner/chain/chia/plotterSpace.go:131 +0x198 fp=0xc000283fc0 sp=0xc000283cf0 pc=0x7d9578
runtime.goexit()
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000283fc8 sp=0xc000283fc0 pc=0x475aa1
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:62 +0x253

**Comment by herotm** [comment]
panic: reflect: call of reflect.Value.IsNil on zero Value [recovered]
        panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 292 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000d1eb20)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:326 +0x85
panic(0x9c4780, 0xc000b964e0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/runtime/panic.go:969 +0x1b9
reflect.Value.IsNil(...)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/reflect/value.go:1086
encoding/json.interfaceEncoder(0xc0007e0900, 0x0, 0x0, 0x0, 0xc0004a0100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:710 +0x17f
encoding/json.mapEncoder.encode(0xa6dea8, 0xc0007e0900, 0xa19340, 0xc000618600, 0x15, 0xa10100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:801 +0x35c
encoding/json.(*encodeState).reflectValue(0xc0007e0900, 0xa19340, 0xc000618600, 0x15, 0xc000d10100)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc0007e0900, 0xa19340, 0xc000618600, 0x59830100, 0x0, 0x0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:330 +0xf4
encoding/json.Marshal(0xa19340, 0xc000618600, 0xa48b24, 0x6, 0xc000c44cf8, 0x0, 0x0)
        /Users/trying/go1.15.11/go1.5.9/go1.15.10/src/encoding/json/encode.go:161 +0x52
github.com/trying2016/common-tools/utils.Map.ToJson(...)
        vendor/github.com/trying2016/common-tools/utils/map.go:51
hpool.com/dev/miner-client/miner/server/websocket.(*Server).Send(0xc000216280, 0xa4a811, 0x8, 0xc000d1ecc0, 0xc000d1ec90)
        miner/server/websocket/server.go:144 +0x270
hpool.com/dev/miner-client/miner/server/websocket.(*Server).keepLive(...)
        miner/server/websocket/server.go:58
hpool.com/dev/miner-client/miner/server/websocket.(*Server).check(0xc000216280)
        miner/server/websocket/server.go:53 +0x1d0
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc000a94ac0, 0xc00048e710)
        vendor/github.com/trying2016/common-tools/utils/timer.go:26 +0x3e
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

**Comment by trying2016** [comment]
请更新https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1 版本
