### ISSUE TITLE
如何配置mac,的config.yaml

### ISSUE THREAD

**Issue by Woner1** [hpool-dev/chia-miner#11]
什么时候能加上注释和完善文档
![image](https://user-images.githubusercontent.com/24207130/115260462-597c0180-a165-11eb-94ca-4381715db80b.png)

**Comment by NirHeaven** [comment]
直接运行按照提示填写就写，会自动填充的

**Comment by PresidentCake** [comment]
Linux和Mac的文件相似，按官方的教程（在Windows设置的最下面，一开始我也没有看到）就是只填path，key，和把false改为true……但是，我填了之后运行还是检测不出矿机在运行……

**Comment by MBTimY** [comment]
> Linux和Mac的文件相似，按官方的教程（在Windows设置的最下面，一开始我也没有看到）就是只填path，key，和把false改为true……但是，我填了之后运行还是检测不出矿机在运行……

我也是MAC, 请问你现在可以正常使用了吗

**Comment by weiok550** [comment]
无法正常挖矿，请问有大佬解决吗

**Comment by only145** [comment]
求大佬解决MAC端挖矿问题

**Comment by sec-plus** [comment]
> 求大佬解决MAC端挖矿问题

更新最新版本的minner 已经可以正常识别, 和挖矿了.

**Comment by only145** [comment]
> > 求大佬解决MAC端挖矿问题
> 
> 更新最新版本的minner 已经可以正常识别, 和挖矿了.

我用1.1版本的也不行呀，能看一下你的设置文件吗？

**Comment by only145** [comment]
<img width="1427" alt="截屏2021-04-30 下午7 34 05" src="https://user-images.githubusercontent.com/69851394/116689859-2d754180-a9eb-11eb-8f39-8c5ab5f19eaf.png">
运行界面是这样算正常吗？我看pool public key也是和我矿池是对应的，但是在线矿机就是没有。

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
