### ISSUE TITLE
ARM Version, Please!

### ISSUE THREAD

**Issue by cooshare** [hpool-dev/chia-miner#110]
we need arm version!

**Comment by ghost** [comment]
一人血书，求快出ARM版本！

**Comment by trying2016** [comment]
Increase arm, aarch64 version
Increase the English version, switch in the settings
Increase display capacity, scan time and scan consumption information in the log
Improve Miner stability
Note: Miner will automatically go offline if the scan time exceeds 10s. If your scan time exceeds 10s, please check whether the hardware is normal

https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
