### ISSUE TITLE
1.2.0 FreeBSD 问题

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#117]
panic : hpool.com/dev/miner-client/miner/chain/chia.(*Prove).write.func1(0x8c8c20, 0xc0004f10e8, 0xc0005afda0, 0x52, 0x1)
        miner/chain/chia/prove.go:111 +0xa8
sync.(*Map).Range(0xc0001011a0, 0xc000b97ce8)
        /usr/local/go/src/sync/map.go:345 +0x1dc
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).write(0xc0001011a0)
        miner/chain/chia/prove.go:110 +0x9b
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).submitProve(0xc0001011a0, 0xc000748b00)
        miner/chain/chia/prove.go:187 +0x566
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0xc0001011a0)
        miner/chain/chia/prove.go:166 +0x125
github.com/trying2016/common-tools/utils.SafeGo.func1(0x969118, 0xc000013f00)
        vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49ERRO[2021-05-07T08:32:19-07:00] prove run error                               error="hpool.com/dev/miner-client/miner/chain/chia.(*Prove).write.func1(0x8c8c20, 0xc0004f10e8, 0xc0005afda0, 0x52, 0x1)\n\tminer/chain/chia/prove.go:111 +0xa8\nsync.(*Map).Range(0xc0001011a0, 0xc000b97ce8)\n\t/usr/local/go/src/sync/map.go:345 +0x1dc\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).write(0xc0001011a0)\n\tminer/chain/chia/prove.go:110 +0x9b\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).submitProve(0xc0001011a0, 0xc000748b00)\n\tminer/chain/chia/prove.go:187 +0x566\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0xc0001011a0)\n\tminer/chain/chia/prove.go:166 +0x125\ngithub.com/trying2016/common-tools/utils.SafeGo.func1(0x969118, 0xc000013f00)\n\tvendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f\ncreated by github.com/trying2016/common-tools/utils.SafeGo\n\tvendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49" f7="{loggers.go,logging.CPrint,156}" f8="{prove.go,chia.(*Prove).Start.func1,72}" f9="{utils.go,utils.SafeGo.func1.1,172}" tid=12

**Comment by herotm** [comment]
程序没有奔溃 还是正常在挖， 只是中间偶尔会出现这个错误

**Comment by trying2016** [comment]
会有影响，更新了1.2.0-2，请下载新的再试下
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-2

**Comment by herotm** [comment]
不对 还是奔溃了  是最新版本的

这里的时候奔溃的

goroutine 197 [select, 7 minutes]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0xc0000ac290, 0xc00019c070)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 199 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc0002be3c0)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 200 [select, 7 minutes]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0xc0000ac2b0, 0xc00019c078)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 174 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc00039db50, 0xc0009165d0)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 263 [syscall, 27 minutes]:
os/signal.signal_recv(0x2f66477748525547)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.2.0
**** BuildTime:2021-05-07-10:10:39 GMT
**** MinerName:xxxxxx
***************************************************
INFO[2021-05-07T08:44:35-07:00] switch line                                   chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=1 type=ws
INFO[2021-05-07T08:44:36-07:00] init server                                   file=loggers.go func=logging.CPrint line=168 tid=199 type=ws url="ws://chia-hb2.hpool.com:9030/ws"
panic: runtime error: index out of range [0] with length 0

goroutine 66 [running]:
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetQualitiesForChallenge.func1(0x14319e0, 0xc0000f2700, 0x0, 0x40, 0xc000996500, 0x7201ea)
        miner/chain/chia/common/chiapos/chia_static.go:43 +0x94
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetQualitiesForChallenge(0x14319e0, 0xc0000f2700, 0x0, 0x40, 0xc0000f2700, 0x96087b, 0x40, 0x40)
        miner/chain/chia/common/chiapos/chia_static.go:44 +0x9f
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetQualitiesForChallenge(0xc0007be9b0, 0xc0000f2700, 0x0, 0x40, 0x0, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:176 +0xad
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc0008a3570, 0x68, 0xc000790e00, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:66 +0x17a
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc000412960, 0xc0000db1d8, 0x8, 0x1)
        miner/chain/chia/plotterSpace.go:131 +0x198
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:62 +0x253

**Comment by herotm** [comment]
这问题能解决么， 3小时掉了2次算力

**Comment by trying2016** [comment]
崩溃的进行了处理，请下载1.2.0-3版本。
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-3

**Comment by herotm** [comment]
解决的问题是什么， 能不能列出来， 每次小更新我们也不知道 更新了什么最起码 让用户知道

**Comment by trying2016** [comment]
(3)版本更新：
5、修复linux加载文件失败导致程序异常退出
6、增加扫盘时间超过最大时间时错误提示（GUI版本增加扫盘状态显示）

**Comment by herotm** [comment]
我换了 现在扫描一对的文件都出来了  这个正常么

DiskProver : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

开跑了 有情况我这边发出来

**Comment by herotm** [comment]
兄弟还是一样


INFO[2021-05-07T23:31:04-07:00] new mining info                               capacity="156.36 TB" file=loggers.go func=logging.CPrint height=248964 jobId=1376755546 line=168 scan consume=550 scan time="2021-05-07 23:30:56" tid=265
INFO[2021-05-07T23:31:12-07:00] new mining info                               capacity="156.36 TB" file=loggers.go func=logging.CPrint height=248965 jobId=609479461 line=168 scan consume=550 scan time="2021-05-07 23:31:04" tid=265
INFO[2021-05-07T23:31:20-07:00] new mining info                               capacity="156.36 TB" file=loggers.go func=logging.CPrint height=248965 jobId=2059730149 line=168 scan consume=550 scan time="2021-05-07 23:31:12" tid=265
INFO[2021-05-07T23:31:32-07:00] new mining info                               capacity="156.36 TB" file=loggers.go func=logging.CPrint height=248966 jobId=3300226201 line=168 scan consume=550 scan time="2021-05-07 23:31:20" tid=265
panic : encoding/json.(*encodeState).marshal.func1(0xc000c19bc0)
        /usr/local/go/src/encoding/json/encode.go:328 +0x8d
panic(0x8da680, 0xc00000e048)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.Value.Int(...)
        /usr/local/go/src/reflect/value.go:999
encoding/json.intEncoder(0xc000522080, 0x0, 0x0, 0x0, 0xc0004f0100)
        /usr/local/go/src/encoding/json/encode.go:552 +0x1ca
encoding/json.mapEncoder.encode(0x96a1a8, 0xc000522080, 0x8de820, 0xc0005aa270, 0x15, 0x8d0100)
        /usr/local/go/src/encoding/json/encode.go:813 +0x366
encoding/json.(*encodeState).reflectValue(0xc000522080, 0x8de820, 0xc0005aa270, 0x15, 0xc000c10100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.(*encodeState).marshal(0xc000522080, 0x8de820, 0xc0005aa270, 0x8d0100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:332 +0xf9
encoding/json.Marshal(0x8de820, 0xc0005aa270, 0xc000c19c58, 0x40c265, 0xc000499080, 0x4, 0xc000c19d90)
        /usr/local/go/src/encoding/json/encode.go:161 +0x52
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).write(0xc0000ab1a0)
        miner/chain/chia/prove.go:115 +0xb8
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).submitProve(0xc0000ab1a0, 0xc000e3e080)
        miner/chain/chia/prove.go:187 +0x566
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0xc0000ab1a0)
        miner/chain/chia/prove.go:166 +0x125
github.com/trying2016/common-tools/utils.SafeGo.func1(0x96a518, 0xc0000b9ed0)
        vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49ERRO[2021-05-07T23:31:33-07:00] prove run error                               error="encoding/json.(*encodeState).marshal.func1(0xc000c19bc0)\n\t/usr/local/go/src/encoding/json/encode.go:328 +0x8d\npanic(0x8da680, 0xc00000e048)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\nreflect.Value.Int(...)\n\t/usr/local/go/src/reflect/value.go:999\nencoding/json.intEncoder(0xc000522080, 0x0, 0x0, 0x0, 0xc0004f0100)\n\t/usr/local/go/src/encoding/json/encode.go:552 +0x1ca\nencoding/json.mapEncoder.encode(0x96a1a8, 0xc000522080, 0x8de820, 0xc0005aa270, 0x15, 0x8d0100)\n\t/usr/local/go/src/encoding/json/encode.go:813 +0x366\nencoding/json.(*encodeState).reflectValue(0xc000522080, 0x8de820, 0xc0005aa270, 0x15, 0xc000c10100)\n\t/usr/local/go/src/encoding/json/encode.go:360 +0x82\nencoding/json.(*encodeState).marshal(0xc000522080, 0x8de820, 0xc0005aa270, 0x8d0100, 0x0, 0x0)\n\t/usr/local/go/src/encoding/json/encode.go:332 +0xf9\nencoding/json.Marshal(0x8de820, 0xc0005aa270, 0xc000c19c58, 0x40c265, 0xc000499080, 0x4, 0xc000c19d90)\n\t/usr/local/go/src/encoding/json/encode.go:161 +0x52\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).write(0xc0000ab1a0)\n\tminer/chain/chia/prove.go:115 +0xb8\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).submitProve(0xc0000ab1a0, 0xc000e3e080)\n\tminer/chain/chia/prove.go:187 +0x566\nhpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0xc0000ab1a0)\n\tminer/chain/chia/prove.go:166 +0x125\ngithub.com/trying2016/common-tools/utils.SafeGo.func1(0x96a518, 0xc0000b9ed0)\n\tvendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f\ncreated by github.com/trying2016/common-tools/utils.SafeGo\n\tvendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49" f7="{loggers.go,logging.CPrint,156}" f8="{prove.go,chia.(*Prove).Start.func1,72}" f9="{utils.go,utils.SafeGo.func1.1,172}" tid=27
INFO[2021-05-07T23:31:40-07:00] new mining info                               capacity="156.36 TB" file=loggers.go func=logging.CPrint height=248966 jobId=248444978 line=168 scan consume=550 scan time="2021-05-07 23:31:32" tid=265

**Comment by herotm** [comment]
INFO[2021-05-07T23:36:49-07:00] new mining info                               capacity="148.34 TB" file=loggers.go func=logging.CPrint height=248989 jobId=318604164 line=168 scan consume=668 scan time="2021-05-07 23:36:36" tid=59
INFO[2021-05-07T23:36:56-07:00] new mining info                               capacity="148.34 TB" file=loggers.go func=logging.CPrint height=248989 jobId=1731041967 line=168 scan consume=668 scan time="2021-05-07 23:36:49" tid=59
INFO[2021-05-07T23:36:57-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=27
INFO[2021-05-07T23:36:58-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=27
INFO[2021-05-07T23:36:59-07:00]
