### ISSUE TITLE
Problem with ARM

### ISSUE THREAD

**Issue by CodeTraderEdge** [hpool-dev/chia-miner#121]
Greetings! I can't run the ARM-64 version I have a Raspberry Pi 4 and Ubuntu Desktop

**Comment by zimocode** [comment]
same problem

**Comment by wasanjantawong** [comment]
same problem

**Comment by CodeTraderEdge** [comment]
I solved!!! 
sudo apt install binfmt-support qemu qemu-user-static

And retry...

**Comment by wasanjantawong** [comment]
> I solved!!!
> sudo apt install binfmt-support qemu qemu-user-static
> 
> And retry...

i retry but and run ./hpool-chia-miner-linux-arm
-bash: ./hpool-chia-miner-linux-arm: No such file or directory

**Comment by CodeTraderEdge** [comment]
> > I solved!!!
> > sudo apt install binfmt-support qemu qemu-user-static
> > And retry...
> 
> i retry but and run ./hpool-chia-miner-linux-arm
> -bash: ./hpool-chia-miner-linux-arm: No such file or directory

You set sudo chmod + 400 ./hpool-chia-miner-linux-arm?
