### ISSUE TITLE
在线算力很久不更新

### ISSUE THREAD

**Issue by haowang1013** [hpool-dev/chia-miner#124]
设置了miner每10分钟扫描一下目录，在矿机汇总页面新加的plot能很快识别出来，但是在线算力很久都不·更新。
请解释一下算力更新的逻辑，有没有方法强制更新？

另外，我试了最新的1.2.0版本，也有同样的问题。

**Comment by trying2016** [comment]
在线算力1小时左右更新，请不要频繁重启软件
