### ISSUE TITLE
使用了1.2.0版本仍然出现离线的情况

### ISSUE THREAD

**Issue by jingyunex** [hpool-dev/chia-miner#125]
并且不会重新连回来，看日志有到矿池的链接报错，监测到链接地址的ip路由追踪，有3%左右的丢包率，是否是网络问题导致？

**Comment by trying2016** [comment]
请发下矿机日志，谢谢

**Comment by jingyunex** [comment]
稍等，为了节省您的时间，提高效率。我这边先整理一下，稍后给您

**Comment by jingyunex** [comment]
我是10点33分在微信收到关于矿机离线31分钟的消息，下面是查看日志中10点初产生的信息

**Comment by jingyunex** [comment]
![Uploading 图片.png…]()

**Comment by jingyunex** [comment]
10点这个时间段产生的error信息如下：

**Comment by jingyunex** [comment]
![Uploading 图片.png…]()

**Comment by jingyunex** [comment]
我想知道的是，我们的不稳定掉线是否和您的服务器有关系？

**Comment by trying2016** [comment]
图片没上传完，麻烦直接贴文本信息
需要查看日志才能确定什么问题导致

**Comment by jingyunex** [comment]
time="2021-05-08T10:24:52+08:00" level=info msg="new mining info" capacity="45.55 TB" file=loggers.go func=logging.CPrint height=248056 jobId=3806684419 line=168 scan consume=61626 scan time="2021-05-08 10:23:37" tid=256
time="2021-05-08T10:25:00+08:00" level=info msg="new mining info" capacity="44.46 TB" file=loggers.go func=logging.CPrint height=248056 jobId=3071052325 line=168 scan consume=61626 scan time="2021-05-08 10:23:37" tid=256
time="2021-05-08T10:25:16+08:00" level=error msg="read message fail" error="websocket: close 1006 (abnormal closure): unexpected EOF" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect.func1,108}" f9="{asm_amd64.s,runtime.goexit,1371}" tid=256
time="2021-05-08T10:25:16+08:00" level=error msg="connect fail" err="dial tcp 39.101.132.210:9032: connect: connection refused" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,86}" f9="{server.go,websocket.(*Server).check,62}" tid=86 url="ws://chia-hb2.hpool.com:9032/ws"
time="2021-05-08T10:25:17+08:00" level=error msg="connect fail" err="dial tcp 39.101.132.210:9032: connect: connection refused" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,86}" f9="{server.go,websocket.(*Server).check,62}" tid=86 url="ws://chia-hb2.hpool.com:9032/ws"
time="2021-05-08T10:25:19+08:00" level=info msg="connect success" file=loggers.go func=logging.CPrint line=168 tid=86 url="ws://chia-hb2.hpool.com:9032/ws"
time="2021-05-08T10:25:19+08:00" level=info msg="new mining info" capacity="43.57 TB" file=loggers.go func=loggi

**Comment by trying2016** [comment]
time="2021-05-08T10:24:52+08:00" level=info msg="new mining info" capacity="45.55 TB" file=loggers.go func=logging.CPrint height=248056 jobId=3806684419 line=168 scan consume=61626 scan time="2021-05-08 10:23:37" tid=256
scan consume 这个是扫盘耗时，您的扫盘时间太长，超过最大10s限制。建议分目录和检查硬件是否正常。
扫盘时间超10s的，扫出的答案是无效的

**Comment by jingyunex** [comment]
好的，那这个没问题了，但其他运行挖矿的机器没有日志报错，是否也是一样的问题离线的呢。不同机器挖的不同路径。日志上是没有查到对应时间有出现类似的报错的

**Comment by jingyunex** [comment]
time="2021-05-08T13:46:01+08:00" level=info msg="new mining info" capacity="2.38 TB" file=loggers.go func=logging.CPrint height=248807 jobId=685491554 line=168 scan consume=2388 scan time="2021-05-08 13:45:52" tid=73
time="2021-05-08T13:46:12+08:00" level=info msg="new mining info" capacity="2.38 TB" file=loggers.go func=logging.CPrint height=248808 jobId=723969009 line=168 scan consume=2388 scan time="2021-05-08 13:46:00" tid=73
time="2021-05-08T13:46:20+08:00" level=info msg="new mining info" capacity="2.38 TB" file=loggers.go func=logging.CPrint height=248808 jobId=2958549153 line=168 scan consume=2388 scan time="2021-05-08 13:46:20" tid=73
time="2021-05-08T13:46:28+08:00" level=info msg="new mining info" capacity="2.38 TB" file=loggers.go func=logging.CPrint height=248809 jobId=3779447271 line=168 scan consume=2388 scan time="2021-05-08 13:46:20" tid=73
这个就是正常的日志吧。您说的扫盘超过10s是因为这里的这个自动的scan吗。超过10s就会导致矿机离线？

**Comment by jingyunex** [comment]
这个10s最大支持扫的高度或者容量是多大。我这边新增文件的扫描任务已经关闭了的

**Comment by jingyunex** [comment]
scan consume=2388这个时间的单位是毫秒吗

**Comment by jingyunex** [comment]
如果在同一个挖矿机器上并发运行2个挖矿程序，是否会减少延迟？
