### ISSUE TITLE
借个地方问一下充值不到账的问题

### ISSUE THREAD

**Issue by wzxsydney** [hpool-dev/chia-miner#126]
我两天前向hpool的chia钱包地址充值，交易显示确认了，但是在hpool一直没有到账。写email不回，电话不接，微信客服根本加不上，请问能否解决一下这个问题？

**Comment by trying2016** [comment]
不建议将币充值回矿池
请联系官方客服微信：17717291449进行登记处理

**Comment by wzxsydney** [comment]
@trying2016 可是这个微信加不上啊，有其他联系方式吗？

**Comment by wzxsydney** [comment]
@trying2016 @hpool-dev 请让客服加我的微信：adsumma
