### ISSUE TITLE
HPool 出的图 Chia UI 钱包的不能识别，但是 Chia UI 钱包出的图可以用作 HPool

### ISSUE THREAD

**Issue by ychost** [hpool-dev/chia-miner#13]
Chia UI 钱包出图没有绑定矿池的 key，但是 HPool 能识别，用这个出的图绑定矿池的 key，Chia UI 缺识别不了

**Comment by h9-dev** [comment]
是可以识别的，本质上没有任何区别。CHIA 钱包对加入的 PLOT 文件有一些限制：

1. 必须要是钱包中私钥关联的PLOT；
2. 钱包必须同步完成所有区块数据。

通常遇到的问题可能是1。
