### ISSUE TITLE
No mining income v1.2.0-3

### ISSUE THREAD

**Issue by AloeKing** [hpool-dev/chia-miner#130]
The site hpool.com shows that my miner is online with all the plots. However in the row "Operating" there are "- -". Under tab "online plot" there is nothing, too. Tab "Revenue" shows no rewards at all. I am online for more than 3 hours now and i am getting zero reward. 

The hpool-miner-chia-gui.exe seems to be working properly. I have also tried the console but still got 0 reward.

**Comment by trying2016** [comment]
Need to set ApiKey in Miner

**Comment by AloeKing** [comment]
I believe i have done it. However I have one more question, i am using currently the plots which I have made before joining the pool. Do I have to create the plots to get it working?

![api key](https://user-images.githubusercontent.com/83868735/117543241-359d3480-b01c-11eb-8489-0f3aad6a9c67.png)

**Comment by AloeKing** [comment]
> I believe i have done it. 

I mean I have set up the API-key from the start. I do believe everything is setup accordingly to the Chinese manual - however I am still getting zero reward.

**Comment by AloeKing** [comment]
Alright I have solved the issue. I do believe the problem was with port forwarding. I was finally able to add rules for both the chia blockchain and the hpool miner.

**Comment by JoNiLiGhT** [comment]
what port?

**Comment by Obsttube** [comment]
@AloeKing could you please tell us what did you have to change? Is it 8444 port forwarding for incoming connections? Or what?

**Comment by AloeKing** [comment]
Hello, I will try my best to explain. 

1) because it was not working I have disabled all of my firewalls at my side (win 10, modem/router).
**it has solved all my issues however it was not the safest solution**.

2) afterwards I have contacted my friend which is an IT specialist in networking.
A) _we have completely disabled ipv6 for my PC and router/modem._ <-- UPDATE: THIS IS NOT TRUE! It has to be enabled because my router/modem lacks any setup for ipv4.
B) we have added exceptions for ports from 8440 until 8449 to both firewalls. <-- UPDATE: modem router sends ALL ports to this machine. Machine has enabled ports UTP 8443 and UTP 8444 + firewall exceptions for hpool + chia blockchain.
**everything was working just fine until this morning**: UPDATE: router/modem leased me another ipv6 so I have updated port forwarding on it.

3) right now I am again getting 0 rewards since 4:53 GMT.
- i suppose my ip lease has been expired and I need to add another exception for my new ip, gonna try it now.
UPDATE: router/modem leased me another ipv6 so I have updated port forwarding on it. Seems like the hpool miner is online again.

**I still have no idea why it is sometimes working and sometimes its not. Right now the ipconfig in cmd shows "Non-existent domain"**. UPDATE: solved by run cmd as administrator.

UPDATE: I will update this thread in few hours. Hopefully everything will be working by then and I will be getting rewards again.

**Comment by AloeKing** [comment]
> what port?



> @AloeKing could you please tell us what did you have to change? Is it 8444 port forwarding for incoming connections? Or what?

Please see my reply above.

**Comment by AloeKing** [comment]
> Hello, I will try my best to explain.
> 
> 1. because it was not working I have disabled all of my firewalls at my side (win 10, modem/router).
>    **it has solved all my issues however it was not the safest solution**.
> 2. afterwards I have contacted my friend which is an IT specialist in networking.
>    A) _we have completely disabled ipv6 for my PC and router/modem._ <-- UPDATE: THIS IS NOT TRUE! It has to be enabled because my router/modem lacks any setup for ipv4.
>    B) we have added exceptions for ports from 8440 until 8449 to both firewalls. <-- UPDATE: modem router sends ALL ports to this machine. Machine has enabled ports UTP 8443 and UTP 8444 + firewall exceptions for hpool + chia blockchain.
>    **everything was working just fine until this morning**: UPDATE: router/modem leased me another ipv6 so I have updated port forwarding on it.
> 3. right now I am again getting 0 rewards since 4:53 GMT.
> 
> * i suppose my ip lease has been expired and I need to add another exception for my new ip, gonna try it now.
>   UPDATE: router/modem leased me another ipv6 so I have updated port forwarding on it. Seems like the hpool miner is online again.
> 
> **I still have no idea why it is sometimes working and sometimes its not. Right now the ipconfig in cmd shows "Non-existent domain"**. UPDATE: solved by run cmd as administrator.
> 
> UPDATE: I will update this thread in few hours. Hopefully everything will be working by then and I will be getting rewards again.

New port forwarding rule solved the issue. Proofs below.

![image](https://user-images.githubusercontent.com/83868735/118375132-02304c00-b5c0-11eb-827b-a7c4e42a8b36.png)

![image](https://user-images.githubusercontent.com/83868735/118375184-589d8a80-b5c0-11eb-84bd-214d207a3d2d.png)

**Comment by igorduarte10** [comment]
Now my plots are online but i have no revenue

**Comment by AloeKing** [comment]
> Now my plots are online but i have no revenue

Run it for few hours - for me I always start getting reward 1-2 hours after the miner was started. Its only issue if it was down for long break (several hours) however.
