### ISSUE TITLE
1.20-4 版本 这个啥意思

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#134]
INFO[2021-05-08T08:43:07-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=12
INFO[2021-05-08T08:43:08-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=12
INFO[2021-05-08T08:43:09-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=12
INFO[2021-05-08T08:43:10-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=12
INFO[2021-05-08T08:43:12-07:00] write file fail                               error="open /root/hpool/chia: too many open files" file=loggers.go fileName=/root/hpool/chia func=logging.CPrint line=168 tid=12

**Comment by trying2016** [comment]
使用ulimit -a 65535 设置最大文件打开数
