### ISSUE TITLE
Which params, comes after ApiKey on Terminal Linux.

### ISSUE THREAD

**Issue by pierrediderot** [hpool-dev/chia-miner#139]
Hi guys,
I would like to know which params after ApiKey in the linux version?
Because I am not able to understand what are the necessary information to fill, after ApiKey in Terminal (Linux).
I appreciate the help.
Tks...

**Comment by jiangwei221** [comment]
Go to "Personal Center -> Pool -> Configuration", you'll see the API key value on the website.

**Comment by VRn00b** [comment]
turn your mind on and copy text to translator

**Comment by pierrediderot** [comment]
This configuration step on the hpool site, I already did.
I would like to know what data I enter in the Linux terminal, to start mining.
Believe me, I tried to translate, but it was not very clear what I need to inform.
What would be Chia Scan?
Thank you in advance.

**Comment by petrkr** [comment]
just go with config.yaml like this

```
token: ""
path:
- ....add folders with plots here...
- /mnt/farm1
- /mnt/farm2
- ....add folders with plots here...
minerName: some-miner-name
apiKey: YOUR-API-KEY
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
  line: ""
scanPath: true
scanMinute: 60
debug: ""
language: en
```

**Comment by pierrediderot** [comment]
Thanks very much @petrkr !
