### ISSUE TITLE
尽管HDD具有300GB，但只有101GB用于采矿

### ISSUE THREAD

**Issue by yuta-hidaka** [hpool-dev/chia-miner#14]
https://github.com/hpool-dev/chia-plotter/issues/5

**Comment by h9-dev** [comment]
CHIA 的 P 盘需要一定的容量作为缓存。

**Comment by yuta-hidaka** [comment]
即使是1TB的硬盘也仅使用100GB的容量。
我想我需要更改.bat文件中的参数，您能帮我吗？

**Comment by yuta-hidaka** [comment]
@hpool-dev
