### ISSUE TITLE
算力与贡献值不匹配

### ISSUE THREAD

**Issue by EverCurse** [hpool-dev/chia-miner#143]
例如在线矿机页面显示有300T  但是贡献值只识别了部分 折合只有200T 这类问题如何排查 我是linux环境

**Comment by trying2016** [comment]
更新到最新版本，会显示扫盘时间和扫盘消耗，扫盘时间过长会导致贡献点低情况
https://github.com/hpool-dev/chia-miner/releases

**Comment by EverCurse** [comment]
time="2021-05-09T11:35:37+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253381 jobId=311587543 line=168 scan consume=825 scan time="2021-05-09 11:35:37" tid=130
time="2021-05-09T11:35:45+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253384 jobId=284843827 line=168 scan consume=825 scan time="2021-05-09 11:35:45" tid=130
time="2021-05-09T11:35:53+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253384 jobId=1996674262 line=168 scan consume=825 scan time="2021-05-09 11:35:45" tid=130
time="2021-05-09T11:36:05+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253384 jobId=2156611095 line=168 scan consume=1322 scan time="2021-05-09 11:36:05" tid=130
time="2021-05-09T11:36:13+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253384 jobId=2607469667 line=168 scan consume=1322 scan time="2021-05-09 11:36:13" tid=130
time="2021-05-09T11:36:21+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253385 jobId=3401634737 line=168 scan consume=1322 scan time="2021-05-09 11:36:21" tid=130
time="2021-05-09T11:36:33+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253385 jobId=3190741727 line=168 scan consume=1322 scan time="2021-05-09 11:36:33" tid=130
time="2021-05-09T11:36:41+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=2686530195 line=168 scan consume=1322 scan time="2021-05-09 11:36:41" tid=130
time="2021-05-09T11:36:49+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=2380451627 line=168 scan consume=1322 scan time="2021-05-09 11:36:49" tid=130
time="2021-05-09T11:36:57+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=3789883050 line=168 scan consume=1322 scan time="2021-05-09 11:36:57" tid=130
time="2021-05-09T11:37:05+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=1805138869 line=168 scan consume=1322 scan time="2021-05-09 11:37:05" tid=130
time="2021-05-09T11:37:17+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=316700054 line=168 scan consume=1322 scan time="2021-05-09 11:37:17" tid=130
time="2021-05-09T11:37:29+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=951872515 line=168 scan consume=1322 scan time="2021-05-09 11:37:29" tid=130
time="2021-05-09T11:37:41+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=294706415 line=168 scan consume=1322 scan time="2021-05-09 11:37:41" tid=130
time="2021-05-09T11:37:49+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253388 jobId=4277667915 line=168 scan consume=1322 scan time="2021-05-09 11:37:49" tid=130
time="2021-05-09T11:37:57+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253391 jobId=3228009111 line=168 scan consume=1322 scan time="2021-05-09 11:37:57" tid=130
time="2021-05-09T11:38:05+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253391 jobId=557297434 line=168 scan consume=1322 scan time="2021-05-09 11:38:05" tid=130
time="2021-05-09T11:38:13+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253391 jobId=433431851 line=168 scan consume=1322 scan time="2021-05-09 11:38:13" tid=130
time="2021-05-09T11:38:25+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253391 jobId=989830848 line=168 scan consume=1322 scan time="2021-05-09 11:38:25" tid=130
time="2021-05-09T11:38:33+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253391 jobId=1064410278 line=168 scan consume=1322 scan time="2021-05-09 11:38:33" tid=130
time="2021-05-09T11:38:45+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253392 jobId=1087551332 line=168 scan consume=1322 scan time="2021-05-09 11:38:45" tid=130
time="2021-05-09T11:38:54+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253392 jobId=2044309151 line=168 scan consume=1322 scan time="2021-05-09 11:38:54" tid=130
time="2021-05-09T11:39:05+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253393 jobId=309267068 line=168 scan consume=1322 scan time="2021-05-09 11:39:05" tid=130
time="2021-05-09T11:39:13+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253393 jobId=663025628 line=168 scan consume=1322 scan time="2021-05-09 11:39:13" tid=130
time="2021-05-09T11:39:25+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253395 jobId=4207505449 line=168 scan consume=1322 scan time="2021-05-09 11:39:25" tid=130
time="2021-05-09T11:39:37+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253395 jobId=3653243673 line=168 scan consume=1322 scan time="2021-05-09 11:39:37" tid=130
time="2021-05-09T11:39:45+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253398 jobId=3392313645 line=168 scan consume=1322 scan time="2021-05-09 11:39:45" tid=130
time="2021-05-09T11:39:53+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253398 jobId=2109970682 line=168 scan consume=1322 scan time="2021-05-09 11:39:53" tid=130
time="2021-05-09T11:40:01+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253399 jobId=3146491801 line=168 scan consume=1322 scan time="2021-05-09 11:40:01" tid=130
time="2021-05-09T11:40:09+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253399 jobId=948800151 line=168 scan consume=1322 scan time="2021-05-09 11:40:09" tid=130
time="2021-05-09T11:40:21+08:00" level=info msg="new mining info" capacity="3.47 TB" file=loggers.go func=logging.CPrint height=253400 jobId=3020388349 line=168 scan consume=1322 scan time="2021-05-09 11:40:21" tid=130

**Comment by EverCurse** [comment]
@trying2016 这个单位是ms吗 其他原因可以排查吗？我感觉不是这个问题 因为文件本身就不多

**Comment by trying2016** [comment]
这个是正常的

**Comment by trying2016** [comment]
另外就是p盘的pubKey是一个吗

**Comment by trying2016** [comment]
需要确保P盘的公钥在矿池签名，后台才能有贡献点

**Comment by EverCurse** [comment]
@trying2016 是同一个 但是我一台机器同时P了两个账号 最终目标不一样 挖矿软件也启动了两个 这个影响吗

**Comment by EverCurse** [comment]
@trying2016 需要确保P盘的公钥在矿池签名，后台才能有贡献点 
这个我确认了 没问题 因为正常算力和共享点的机器挖矿参数是一致的  签名肯定是ok的 不然一点贡献值也不会有的

**Comment by trying2016** [comment]
目录分开就没影响的

**Comment by trying2016** [comment]
你在后台看下在线算力，看看数据是不是正常

**Comment by EverCurse** [comment]
@trying2016 算力正常的 都能识别每台机器 但是贡献值不匹配 低了很多啊

**Comment by trying2016** [comment]
账号发下

**Comment by EverCurse** [comment]
591356683@qq.com 谢谢

**Comment by trying2016** [comment]
好的，稍等会

**Comment by EverCurse** [comment]
感谢 感谢  我想知道贡献值是哪些机器贡献的 ，没有贡献的机器我就好去排查问题 现在就是不知道哪些机器有问题

**Comment by trying2016** [comment]
这个账号下的在线容量和和你矿机提交过来的数据是匹配的，你先在后台看下在线矿机和你开好的机器是不是匹配

**Comment by EverCurse** [comment]
我先核实下 感谢了 后续还需要麻烦老哥看下

**Comment by trying2016** [comment]
不客气
如果有问题 建议先在后台看矿机是否在线，矿机容量和本机容量是否匹配

**Comment by EverCurse** [comment]
贡献点的刷新是不是有缓存 会不会是矿机更新了 但是贡献值读cache去了

**Comment by EverCurse** [comment]
哥们儿 呢过不能帮忙查询提交有效算力的机器的名称 我这边核实下 谢谢

**Comment by trying2016** [comment]
新加机器会有在2小时内看到贡献点

**Comment by EverCurse** [comment]
@trying2016 我确认了 是我自己的问题 plot文件签名不是这个账号的 感谢~ close issue
