### ISSUE TITLE
Safe plotting with the chia app?

### ISSUE THREAD

**Issue by AloeKing** [hpool-dev/chia-miner#145]
1) I have disabled automatic plot search in hpool console. 
2) Also I am creating new plots with the official chia app. 

Can I get flagged as double farmer when I am farming with 1/2 plots on hpool and with another 1/2 as solo farmer?

**Comment by betterpi** [comment]
yes  you will  be ban

**Comment by AloeKing** [comment]
Alright thanks, for now I have closed it down.

**Comment by AloeKing** [comment]
So I see based on Chinese manual I can use the official wallet.

**How to use CHIA official wallet for P disk to avoid double mining?**

Step 1: When **adding a PLOT file to the farmland** , click on the advanced option of " **Select the amount to open up**" and check the " **Exclude final directory** "; 
exclude the final directory: This file will not be added to the wallet mining list after completing the P disk Inside, but after leaving the mining pool for mining, it can still be added back to the wallet solo normally.

![image](https://user-images.githubusercontent.com/83868735/117571502-190e0480-b0cf-11eb-8cf8-0076c4d9c201.png)

Step 2: If the path of the plot file stored in the wallet and the mining pool is the same, delete the original path in the wallet solo;

![image](https://user-images.githubusercontent.com/83868735/117571519-30e58880-b0cf-11eb-9868-e02173f4f3ed.png)
