### ISSUE TITLE
There has been a lot of revenue decrease after update

### ISSUE THREAD

**Issue by hgurkann** [hpool-dev/chia-miner#151]
pool power reduced 1354 from 1433
difficulty reduced 2810 from 3239
daily income for 1PB become 1.43 from 2.4 xch
there is something wrong in here.
did you guys raised your fee up to 60% ??
even uupool gives "much" more income, 2.12 xch for 1PB for "now"

**Comment by jackykwandesign** [comment]
肯定有些什麼問題吧，手續費升到50% 你們搞笑吧

**Comment by hgurkann** [comment]
I saw the annoucement now. okay

**Comment by h9-dev** [comment]
看看公告，是主网故障导致的。

Look at the announcement, it was caused by the mainnet failure.
