### ISSUE TITLE
收益真的少太多了?

### ISSUE THREAD

**Issue by timmmsn** [hpool-dev/chia-miner#153]
我相信不是只有我抱怨，收益真的少太多了!

**Comment by timmmsn** [comment]
Sorry，已看到消息，希望能盡快修復。

5月9日Chia主网瘫痪导致出块减少2021/05/10
由于Chia主网因BUG问题，导致5月9日晚主网于区块高度255108后（北京时间约20:50分）出现了严重的出块堵塞。原本全网每24小时正常出块均值应为4608个，当前近24小时全网出块约3500个，整体出块量减少了25%，全网算力及难度也出现了异常波动。
1，昨日晚上20:43分后出现结算收益延迟，此正因昨晚主网瘫痪导致。
2，当前结算收益受到昨日总出块量的减少而整体下降。
3，全网当前由官方提供的收益数据为理论数据，每日爆块量并非采集真实的爆块数量，导致理论收益和实际收益值在受到主网网络波动后差异化巨大。

目前官方已紧急修复了主网BUG问题，出块及收益将会慢慢恢复，请知悉。

**Comment by codename10086** [comment]
确实，今天收益大减，同样的算力昨天有0.06，今天增加了两块田反而只有0.04

**Comment by mukioZ** [comment]
现在按hpool自己标的全网算力是接近5.8，再按hpool官方说的减少的25%收益加到现在的收益，对比之下甚至还不到hpool自己标的5.9的收益，我觉得这点问题非常大了

**Comment by eddy16112** [comment]
我说怎么今天收益这么少，还以为自己P地速度太慢，赶不上算力的增加

**Comment by vay007** [comment]
这个收益如何计算的，大家有没有明白的啊，就看到一个贡献点。hpool首页显示的日平均收益 XCH/PB 和 [chiaexplorer](https://www.chiaexplorer.com/charts/xchTib) 展示的相差有点多。
