### ISSUE TITLE
你们的矿池地址分发服务器炸了。。。

### ISSUE THREAD

**Issue by frostashe** [hpool-dev/chia-miner#157]
https://chia.hpool.com/proxy/wslines
访问不了了

**Comment by AndrewWu1998** [comment]
是的

**Comment by AndrewWu1998** [comment]
连接不了了

**Comment by areyoufooled** [comment]
+1

**Comment by yinqf** [comment]
连不了，都掉线了，有反馈方式吗

**Comment by StormYudi** [comment]
+1

**Comment by liumingcun** [comment]
+1

**Comment by liumingcun** [comment]
所有版本hpool客户端都不可以

**Comment by vay007** [comment]
有没有官方群啊，加一下，添加客服总是说被加好友频繁。

**Comment by liumingcun** [comment]
> 有没有官方群啊，加一下，添加客服总是说被加好友频繁。

没找到官方群呀，同样也是添加不上客服

**Comment by liumingcun** [comment]
我的已经连上了，兄弟们。好像是修好了

**Comment by tschombe** [comment]
+1 same thing here

**Comment by VRn00b** [comment]
+1

**Comment by trying2016** [comment]
我们进行了修复，请更新到1.2.0-5版本
We have fixed it, please update to version 1.2.0-5

https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-5
