### ISSUE TITLE
扫盘时间，，被踢下线，找不到问题

### ISSUE THREAD

**Issue by niu12503** [hpool-dev/chia-miner#159]

**Comment by niu12503** [comment]
外怪USB3。5盘  扫盘时间偶尔会超时，也不知道啥问题吗，没注意就会被踢线，能否设定连续超时再踢下线啊，偶尔的超时就下线太麻烦了

**Comment by timmmsn** [comment]
我已建議過，一樣遇到相同問題，新版本加這功能應該要能夠調整時間，有些時候正在COPY資料，圖又多反應比較慢，也要踢

**Comment by trying2016** [comment]
更新到1.20.5版本，对扫盘进行过优化
