### ISSUE TITLE
用HPool提供得P图软件P出来的plot在1.0.4版本是识别的，但是到1.0.5就不识别了！官方P的通用

### ISSUE THREAD

**Issue by BigZzzzzzz** [hpool-dev/chia-miner#16]
用HPool提供得P图软件P出来的plot在1.0.4版本是识别的，但是到1.0.5就不识别了！官方P的通用

**Comment by outman3698** [comment]
遇到了 同样的问题。。

**Comment by h9-dev** [comment]
1.0.5 开始对文件做格式检查，如果文件格式错误的就不会加入到 Mining 队列。但是这个文件在Chia 钱包和之前版本的miner上是会被加入Mining 队列的，但是这个文件毫无作用，而且还会导致 miner 软件崩溃。你也可以用使用 官方的 ProofOfSpace 工具检查这个文件。
