### ISSUE TITLE
提現兩天還沒入帳

### ISSUE THREAD

**Issue by bloodzzero** [hpool-dev/chia-miner#161]
請問我5/8提現到官方錢包
目前都還未入帳？
請問是哪邊出了問題？

**Comment by codename10086** [comment]
你有没有检查你的钱包那里是否同步完成，有没有connection为0的情况，我两台电脑运行同一个账号的钱包，一台电脑的钱包迟迟不能同步完，connection为0，所以无法显示转出来的1.06个XCH；另一台电脑钱包则完全同步成功，有connection，就能显示出来那1.06个XCH。

**Comment by trying2016** [comment]
由于CHIA主网卡，到账时间可能有所延后
