### ISSUE TITLE
平均收益率计算方法

### ISSUE THREAD

**Issue by haowang1013** [hpool-dev/chia-miner#162]
能否解释一下矿池的平均收益率是怎么计算的？

现在矿池自己发布的数据是

- 矿池算力 1353.30 PB
- 24H爆块 1315
- 日平均收益 1.42 XCH/PB

难道平均收益不应该是1315 * 2 / 1353.30  = 1.94 XCH/PB?

**Comment by mukioZ** [comment]
矿池要吃饭的，所以写作费率0%，实际抽水至少30%，真是太厉害了

**Comment by timmmsn** [comment]
沒錯，每10TB 每天收益應該為0.03XCH，但這邊收益僅有0.02XCH，就是吸血30%

**Comment by nqzhang** [comment]
矿池自己数据作假都做的这么明显！！！！！！！！！

**Comment by Hubert51** [comment]
是有人在双挖吧

**Comment by mukioZ** [comment]
是有专门话术带双挖么，双挖现在出币是秒封，是有多少人双挖能每天都差出30%以上收益并且矿池算力能稳住？

**Comment by Hubert51** [comment]
有道理，我又去算力一下，2021 * 2 / 1354.0 =  2.98XCH/PB, 和2.05差得更多。虽然我感觉hpool现在的算力，24小时内爆不了2021块。但这个数据确实不太对

**Comment by haowang1013** [comment]
其实矿池抽水很正常，现在HP一家独大费率高也没什么办法。但我希望能够把费率透明化，让大家瞎猜体验很不好。

**Comment by trying2016** [comment]
1、矿池目前没有收取服务费
2、实际收益会有波动，爆块属于概率问题
3、矿池显示的是用户接入矿池的容量，其中还有未签名等其它无效算力影响

**Comment by Hubert51** [comment]
嗯嗯，我也是希望矿池能把怎么计算收益的方法告诉我们，并且哪里会有误差也告诉我们，我们能明白怎么计算收益。目前我每天的收益都比expected 收益要低不少，就觉得矿池在抽水

**Comment by trying2016** [comment]
1、官方预期收益是根据全网难度进行评估，并不准确
2、收益如果低的话，可以看矿池中的贡献点是否正常

**Comment by Hubert51** [comment]
贡献点挺正常的，我73t 算力，用chia explorer 计算应该有0.23左右的收益，但我每天都只有0.13 左右。会不会是我扫盘的问题？

**Comment by trying2016** [comment]
后台显示贡献点看看是不是有波动
扫盘问题可以现在1.2.0-5版本，会显示扫盘数据

**Comment by Hubert51** [comment]
没有波动，一条直线慢慢上升。我目前还在1.1.0版本

**Comment by trying2016** [comment]
建议更新到最新，有显示扫盘信息

**Comment by Hubert51** [comment]
好的，谢谢！

**Comment by haowang1013** [comment]
> 有波动，爆块属于概率问题
> 3、矿池显示的是用户接入矿池的容量，其中还有未签名等其它无效算力影响

爆块有波动很正常, 但完全可以统计前面N小时的量取平均啊.
另外如果矿池显示的总量包含无效算力, 单位算力的收益不是应该更高么？

**Comment by mukioZ** [comment]
爆块有波动正常，但是你们占了全网接近一半算力然后每天都差，还是都往少了差30%以上，是不是欺负人没学过概率论，而且空算力不该是收益更高？矿池有抽成很正常，写出来就好了。一边说着我们不抽成，一边偷人算力，那不是又当又立。

**Comment by arandomg** [comment]
根据chia explorer统计
![image](https://user-images.githubusercontent.com/83610215/117857281-987c0f00-b25a-11eb-9438-c90c6c8ee629.png)
Hpool自己写的
![image](https://user-images.githubusercontent.com/83610215/117857324-a2057700-b25a-11eb-9bb7-7b366875f0b3.png)

30%的差距出现在这里。那么有如下几种可能：
1. Hpool数据统计有误。但如果统计是根据实际爆块得到的话，收益也应该跟统计数据匹配
2. 故意夸大收益吸引矿工，赚提现手续费
3. 有30%的算力在双挖，且每天都在，爆了块也没被封
4. hpool自己吞掉了30%算力并且币也没有进入到大家所见的主要矿池地址，也可以某种程度上理解为hpool自己在双挖

**Comment by arandomg** [comment]
@trying2016 请正面解释
