### ISSUE TITLE
旷工程序显示new mining info ，后台在线矿机和离线矿机为空

### ISSUE THREAD

**Issue by jihchao** [hpool-dev/chia-miner#17]
miner 持续打印
dlopen err: dlopen(libchiapos.dylib, 9): image not found
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.0.5
**** BuildTime:2021-04-19-13:19:55 GMT
**** MinerName:****
***************************************************
INFO[2021-04-20T12:36:37+08:00] pool public key: a2def911c232aeabd50d286e0e8454bab22efe6e2c6335c815c2c28367ad3d46d7deceb60ebb8d96a3135bcce09b4c7d  file=loggers.go func=logging.CPrint line=168 tid=1
INFO[2021-04-20T12:36:37+08:00] switch line                                   chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=1 type=ws
INFO[2021-04-20T12:36:38+08:00] connect success                               file=loggers.go func=logging.CPrint line=168 tid=66 url="wss://chia-sh0.hpool.com/x-proxynode/ws"
INFO[2021-04-20T12:36:38+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156268 jobId=3281866943 line=168 tid=40
INFO[2021-04-20T12:36:43+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156268 jobId=2079950859 line=168 tid=40
INFO[2021-04-20T12:36:55+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156268 jobId=712855360 line=168 tid=40
INFO[2021-04-20T12:37:04+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156268 jobId=2543298889 line=168 tid=40
INFO[2021-04-20T12:37:15+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156269 jobId=1962593530 line=168 tid=40
INFO[2021-04-20T12:37:24+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156269 jobId=4084166630 line=168 tid=40
INFO[2021-04-20T12:37:31+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156269 jobId=3167556495 line=168 tid=40
INFO[2021-04-20T12:37:39+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156269 jobId=3624219087 line=168 tid=40
INFO[2021-04-20T12:37:52+08:00] new mining info                               file=loggers.go func=logging.CPrint height=156269 jobId=2224427907 line=168 tid=40

**Comment by jihchao** [comment]
已解决

**Comment by flybiubiu** [comment]
我也遇到了同样的问题, 这个是怎么解决的

**Comment by Yuyiba** [comment]
同样的问题 请问怎么解决的？

**Comment by 85256638** [comment]
> 已解决

怎么解决的？以后发问题，自己又解决了，麻烦说一下怎么解决可以吗？

**Comment by 85256638** [comment]
我等了大概一个多小时后网站上算力更新了，Dev 应该把这个写道帮助文件里面，要不然每个人都要问
