### ISSUE TITLE
HPool miner for arm64 asks me a chia scan?

### ISSUE THREAD

**Issue by almando** [hpool-dev/chia-miner#170]
Hi i am trying to run HPool using Raspberry Pi4 64bit on Ubuntu 64

this is what happens:

(venv) ubuntu@ubuntu:~/linux-arm64$ ./hpool-chia-miner-linux-arm64 -config /home/ubuntu/.chia/mainnet/config/config.yaml
dlsym err: /home/ubuntu/linux-arm64/libchiapos.so: undefined symbol: MySyscall
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.2.0
**** BuildTime:2021-05-08-12:46:55 GMT
**** MinerName:ubuntu
***************************************************
请输入Chia矿池ApiKey：
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (just hide my api key)
请输入Chia扫盘路径，结束请输入end：

What i have to to next? i have translated what is this chia scan?
Please, could you help me?

**Comment by niflying** [comment]
your plots folder path.
like this 
/home/plots/

**Comment by zhencode1** [comment]
it's asking for the path value equivalent in the config.yaml file and it's because your path is not configed in the config.ymal file.

in the config.yml , path takes a list of paths like this,

```
path:
- /path/path1
- /path/path2
- ""
minerName: miner123
...

```
instead of 

```
path: /path/path1
minerName: miner123

```
the above format will cause the executable not to detect the path value

Hope it helps

**Comment by almando** [comment]
I have changed and, Now it is working!!! 

Thanks!
