### ISSUE TITLE
SOLO挖矿怎么转矿池

### ISSUE THREAD

**Issue by koiNoCirculation** [hpool-dev/chia-miner#171]
如题，solo搞了9个T，但是所有的plots都是绑着自己的farmer key的，怎么转到hpool，难道要全部重来吗

**Comment by dream-rhythm** [comment]
這個問題現在要分兩階段
1. 在5/17前(也就是現在)
    HPool支持官方錢包的檔案無縫轉移
    這部份[HPool官網幫助中心](https://www.hpool.com/help/tutorial)就有詳細教程可以看
2. 5/17後chia官方會釋出支持礦池協議的版本([出處](https://twitter.com/bramcohen/status/1390407484179763202))
    若要使用礦池協議則需要replot
    但HPool是否會只支持新協議而放棄舊協議
    這點還要HPool開發人員確認

備註:
chia官方所說的5/17根據慣例是指太平洋時間5/17
換算北京時間將會是5/18的某一個時刻

**Comment by trying2016** [comment]
@koiNoCirculation 不需要的
https://www.hpool.com/help/tutorial/Chia挖矿教程
请参考教程，安装上面步骤操作即可加入矿池
