### ISSUE TITLE
HPOOL 官方客服 / 邮箱

### ISSUE THREAD

**Issue by chengyap98** [hpool-dev/chia-miner#172]
1. 官方的微信 从一开始到现在都加不了，一直提示频繁，请问下有没有官方的QQ 还是 微信群呢？方便联络客服还是官方人员啥的。
2. 写了几封邮件发给了官方邮箱都没收到回复，已经有几天的时间了，请问下一般需要多长时间才能收到回复呢？

**Comment by trying2016** [comment]
您可以把微信在GitHub上私信给我们，我们来加您。
有问题也可以在GitHub上提问

**Comment by chengyap98** [comment]
> 您可以把微信在GitHub上私信给我们，我们来加您。
> 有问题也可以在GitHub上提问

不好意思 我没找到Github私信的渠道，我就把我的微信放在这，麻烦你加一下。
微信号: xiaoye_98
谢谢你

**Comment by trying2016** [comment]
@chengyap98 已经转给客服，稍后会添加您微信，请注意查看

**Comment by wzxsydney** [comment]
> 您可以把微信在GitHub上私信给我们，我们来加您。
> 有问题也可以在GitHub上提问

@trying2016 也请加一下我的： https://github.com/hpool-dev/chia-miner/issues/126#issuecomment-839422587

**Comment by YamaXanadu830** [comment]
我也觉得啊，起码来个TG讨论群，discord群之类的啊，一天到晚，客服微信都是加好友太多

**Comment by oytp** [comment]
> 您 可以 把 微 信 在 GitHub 上 私 信 给 我们 ， 我们 来 加 您。
> 有可以在 GitHub 上 提问

如果您能回答GitHub,请告诉我HPool费率是多少?40%?

**Comment by andy118z** [comment]
我也是试试加客服 ！还是加不到！

🤣🤣🙈🙈🙈

还有我的挖矿软件一直自动关闭！
可以帮帮忙嘛？ 🙈🙈🙈🙈
