### ISSUE TITLE
dlsym err: undefined symbol: CreateDiskProver - Raspberry PI

### ISSUE THREAD

**Issue by KeramxD** [hpool-dev/chia-miner#173]
Hello,
When I try to start farming on Raspberry PI I see this:
`dlsym err: /home/pi/Desktop/linux-arm/hpool-chia-miner-linux-arm: undefined symbol: CreateDiskProver
ERRO[2021-05-11T21:13:50+02:00] add plot file                                 error= f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,179}" f9="{asm_arm.s,runtime.goexit,841}" file=/media/pi/Chia1/plot-k32-2021-04-12-21-52-104f8bc3599a24fa08a0034de8b69dc0cffbc2f76c00876fcf6894072a87dd77.plot tid=30
dlsym err: /home/pi/Desktop/linux-arm/hpool-chia-miner-linux-arm: undefined symbol: CreateDiskProver
`

It sees my plots but does not use it because after this error it shows:
`INFO[2021-05-11T21:23:02+02:00] new mining info capacity="0 B" file=loggers.go func=logging.CPrint height=265656 jobId=555669437 line=168 scan consume=0 scan time="1970-01-01 01:00:00" tid=64`

Can I solve it somehow?

**Comment by KeramxD** [comment]
Used wrong architecture

**Comment by Rayjrz** [comment]
Same issue with nvidia TX1, any way to solve this?
