### ISSUE TITLE
矿池有白帽子计划吗，我可能找到一个漏洞

### ISSUE THREAD

**Issue by ysh0566** [hpool-dev/chia-miner#176]

**Comment by m-d-z-z** [comment]
果然有（吃瓜+subscribe

**Comment by trying2016** [comment]
@ysh0566 如果发现1.2.0后的版本有相关的漏洞，请联系我们客服，会有奖励

**Comment by ysh0566** [comment]
@trying2016 我联系的到就不在这里找你了。。。

**Comment by ysh0566** [comment]
> @ysh0566 如果发现1.2.0后的版本有相关的漏洞，请联系我们客服，会有奖励

给我微信号，我来加你，或者微信号发我邮箱ysh0566@qq.com

**Comment by trying2016** [comment]
好的。我们添加您
