### ISSUE TITLE
PLOT 的文件 在 Chia 官网上的 1.0.4的版本能识别，但是HPOOL 的GUI 的 不能识别。

### ISSUE THREAD

**Issue by outman3698** [hpool-dev/chia-miner#18]
time="2021-04-20T11:40:26+08:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="E:\\chia\\plot-k32-2021-04-18-20-18-1b2df1ff04017c88283597ff71816d312c3aa9c6e33c77ba41ebb3d24560e55d.plot" tid=53
time="2021-04-20T11:40:26+08:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="E:\\chia\\plot-k32-2021-04-19-01-54-dc569b9c11bf843e9a19d82253a499044045da1bd3c05fce98becbe07f1153fc.plot" tid=53
time="2021-04-20T11:40:26+08:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="E:\\chia\\plot-k32-2021-04-20-02-28-d61c2b3b25f85f2057e8e1803875c22a241a9934cba8ceb84036dfb77a5a54f9.plot" tid=53
time="2021-04-20T11:40:26+08:00" level=info msg="pool public key: 9745a0942995d0b577beee601280d80bdec1ee4b7d9f7d0b8570d341e2ab69c046e946d7d79c52f434d8c40ecce6f706" file=loggers.go func=logging.CPrint line=168 tid=53

**Comment by outman3698** [comment]
另外1.0.5  PLOT 出来的文件，GUI好像 不能识别。

**Comment by h9-dev** [comment]
从 1.0.5 开始会检查文件的内容。官方钱包和 hpool miner的之前版本并不会检查文件格式。如果有错误的文件，会自动被1.0.5的 miner 排除，这也是之前版本会闪退的原因。官方钱包虽然识别了你的文件，但是在读取文件时同样会崩溃，只是你不会感知到，因为他会默默的被重新启动，但是这个文件不会挖到任何 XCH。

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
