### ISSUE TITLE
异地两台电脑一起挖，同一个HPOOL账号，怎么设置？

### ISSUE THREAD

**Issue by mikewubox** [hpool-dev/chia-miner#181]
把一台原来的挖矿软件客户端拷贝过去，plot文件是不重复的，直接登录会自动退出，是不是需要另外设置个钱包ID，建立新签名，绑定签名数据？

**Comment by codename10086** [comment]
不要拷贝过去，重新下载一份运行，输入API Key登录。

**Comment by mikewubox** [comment]
试挂了一晚，新ID,新签名，可以的。
