### ISSUE TITLE
超时被踢掉线

### ISSUE THREAD

**Issue by niu12503** [hpool-dev/chia-miner#183]
偶尔网络波动或者个别硬盘在大量读写导致超时掉线，最新版本的也不会自动上线啊， 自动上线这个要求很高吗，难道天天盯着电脑。晚上已掉线，一晚上全完蛋

**Comment by chchia** [comment]
同意，超时竟然不能重试？无语。

**Comment by niu12503** [comment]
同行的矿池都没有这个问题，希望尽快改进

**Comment by h9-dev** [comment]
要求扫盘时间不能大于5s，不理解为什么限制时间的可以看看这个。
https://github.com/Chia-Network/chia-blockchain/blob/1.1.5/chia/harvester/harvester_api.py#L201

**Comment by niu12503** [comment]
没有要看这个解释，关键掉线还不能自己连接！！（最新版），还有用你们的扫描经常超时，同行矿池的就不会，应该是你们扫描方法还需要改进。你们可以看下同行的扫描为什么不会经常出现超时

**Comment by h9-dev** [comment]
因为他们可能就没检测超时。

**Comment by niu12503** [comment]
看来没有用过他们的软件...  他们也有检测时间.

**Comment by jadesongplay** [comment]
> 因为他们可能就没检测超时。

人家提出的问题请正面回答，掉线自动重连这个问题能不能得到解决？ 难道一掉线就TDM要手动重启？

**Comment by h9-dev** [comment]
> > 因为他们可能就没检测超时。
> 
> 人家提出的问题请正面回答，掉线自动重连这个问题能不能得到解决？ 难道一掉线就TDM要手动重启？

一直超时是不会链接上的，扫盘时间过大，算力不会出块。不踢下线是在吸所有人收益。

**Comment by trying2016** [comment]
要求扫盘时间不能大于5s，不理解为什么限制时间的可以看看这个。
https://github.com/Chia-Network/chia-blockchain/blob/1.1.5/chia/harvester/harvester_api.py#L201
