### ISSUE TITLE
DNS error accessing hpool

### ISSUE THREAD

**Issue by PCManiacpt** [hpool-dev/chia-miner#185]
Hi, 

Since around 12 hours I am having DNS issues to connect o hpool.com and the miner
I did check some DNS propagation check tools and they tell me the domain is not properly/fully propagated. 

I am from Portugal

[miner.log-20210512-12.log](https://github.com/hpool-dev/chia-miner/files/6465611/miner.log-20210512-12.log)

**Comment by rudyzhou2** [comment]
same issue here, issue is still present
time="2021-05-12T10:22:55-04:00" level=info msg="update line fail" error="Get \"https://chia.hpool.com/proxy/wslines\": dial tcp 203.107.53.48:443: connect: no route to host"

**Comment by PCManiacpt** [comment]
I was having DNS issues. for some reason, virtualbox was picking up the connection. 
Fixed after disabling it.

**Comment by vfneves** [comment]
can you tell me how you did to solve it? i am from portugal too. and having the same problem

**Comment by PCManiacpt** [comment]
> can you tell me how you did to solve it? i am from portugal too. and having the same problem

Hey, on my side, the problem was that I had virtualbox and for some reason, that was picking up the DNS queries.
Fixed it by disabling virtualbox ethernet connection.

AFAIK, our ISP DNS are routing hpool's queries.

Good luck
