### ISSUE TITLE
贡献点上升和下降

### ISSUE THREAD

**Issue by BitSec01** [hpool-dev/chia-miner#191]
我所看到的
![image](https://user-images.githubusercontent.com/12982618/118023595-ff362100-b35d-11eb-9be3-6dd17a162495.png)

这就是我在在线矿机上看到的。但有时它们显示的空间较小
![image](https://user-images.githubusercontent.com/12982618/118023736-2b51a200-b35e-11eb-84f7-57b1bdd89e88.png)
![image](https://user-images.githubusercontent.com/12982618/118024638-38bb5c00-b35f-11eb-963b-aaaa7cc2321b.png)

| time                 | capacity  | scan consume | scan time           | tid |
|----------------------|-----------|--------------|---------------------|-----|
| 2021-05-12T18:10:58Z | 811.20 GB | 2            | 2021-05-12 18:10:49 | 75  |
| 2021-05-12T18:11:09Z | 709.80 GB | 579          | 2021-05-12 18:10:57 | 230 |
| 2021-05-12T18:11:09Z | 811.20 GB | 2            | 2021-05-12 18:10:58 | 75  |
| 2021-05-12T18:11:13Z | 811.20 GB | 2            | 2021-05-12 18:11:09 | 75  |
| 2021-05-12T18:11:13Z | 709.80 GB | 579          | 2021-05-12 18:11:09 | 230 |

我运行的命令
` nohup ./hpool-miner-chia > /dev/null &`

**Comment by BitSec01** [comment]
@trying2016 你知道发生什么事了吗

**Comment by EverCurse** [comment]
@RamonRobben same as me

**Comment by BitSec01** [comment]
@EverCurse I'm not exactly sure what the issue is. But I ran a quick `ps -ef | grep hpool` and I saw I had multiple processes with that command so maybe I accidentally started multiple of them. I stopped them all and then I ran a single command (also I downloaded latest version from their github)

**Comment by EverCurse** [comment]
> @EverCurse I'm not exactly sure what the issue is. But I ran a quick `ps -ef | grep hpool` and I saw I had multiple processes with that command so maybe I accidentally started multiple of them. I stopped them all and then I ran a single command (also I downloaded latest version from their github)

how about your  auto scan time, maybe you should change it bigger. , and try try to use latest version miner

**Comment by BitSec01** [comment]
> > @EverCurse I'm not exactly sure what the issue is. But I ran a quick `ps -ef | grep hpool` and I saw I had multiple processes with that command so maybe I accidentally started multiple of them. I stopped them all and then I ran a single command (also I downloaded latest version from their github)
> 
> how about your auto scan time, maybe you should change it bigger. , and try try to use latest version miner

My auto scan time was 15 minutes but now I changed it to 60 minutes and see if its more stable. I mean every 60 minutes is fine. I could even set it to every 2 - 4 hours if its still unstable on this current version / 60 minutes scan time. In the log file I do see that it has a scan time only few seconds apart so not sure why that is. I also updated to latest version miner.

**Comment by EverCurse** [comment]
@trying2016  老哥 这个问题怎么回事啊 我也遇到了 算力忽高忽低的

**Comment by BitSec01** [comment]
> @trying2016 老哥 这个问题怎么回事啊 我也遇到了 算力忽高忽低的

Mine seems to have been stable since 12:27 today. I made sure only one process is running with ` ps -ef | grep hpool`. Scan consume is now 0 every time. No downtime so far.
