### ISSUE TITLE
v1.3

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#196]
一开就是这个错误

INFO[2021-05-12T20:49:29-07:00] update line fail                              error="Get \"http://chia-0df3c2fd4e.hpool.xin/proxy/wslines\": dial tcp: lookup chia-0df3c2fd4e.hpool.xin on 4.2.2.2:53: no such host" file=loggers.go func=logging.CPrint line=168 tid=1
INFO[2021-05-12T20:49:30-07:00] update line fail                              error="Get \"http://chia-14413fb6c2.hpool.xin/proxy/wslines\": dial tcp: lookup chia-14413fb6c2.hpool.xin on 4.2.2.2:53: no such host" file=loggers.go func=logging.CPrint line=168 tid=15

扫硬盘也10分钟了， 没任何下文。。。

卡在这里了
Loading plotter files /data/31 (85/85) 100%

哎。。

**Comment by jiangwei221** [comment]
+1
```
time="2021-05-12T20:58:29-07:00" level=info msg="Logger Configuration." fields.level=info file=loggers.go func=logging.Init line=121 path=./log/
time="2021-05-12T20:58:29-07:00" level=info msg="update line fail" error="Get \"http://chia-14413fb6c2.hpool.xin/proxy/wslines\": dial tcp: lookup chia-14413fb6c2.hpool.xin: no such host" file=loggers.go func=logging.CPrint line=168 tid=1
time="2021-05-12T20:58:30-07:00" level=info msg="update line fail" error="Get \"http://chia-15116df3dd.hpool.cn/proxy/wslines\": dial tcp: lookup chia-15116df3dd.hpool.cn: no such host" file=loggers.go func=logging.CPrint line=168 tid=15
time="2021-05-12T20:58:31-07:00" level=info msg="update line fail" error="Get \"http://chia-4ad7d826df.hpool.cn/proxy/wslines\": dial tcp: lookup chia-4ad7d826df.hpool.cn: no such host" file=loggers.go func=logging.CPrint line=168 tid=15
time="2021-05-12T20:58:33-07:00" level=info msg="update line fail" error="Get \"http://chia-85627fe3f1.hpool.xin/proxy/wslines\": dial tcp: lookup chia-85627fe3f1.hpool.xin: no such host" file=loggers.go func=logging.CPrint line=168 tid=15
time="2021-05-12T20:58:34-07:00" level=info msg="update line fail" error="Get \"http://chia-5cfe939d68.hpool.cn/proxy/wslines\": dial tcp: lookup chia-5cfe939d68.hpool.cn: no such host" file=loggers.go func=logging.CPrint line=168 tid=15
time="2021-05-12T20:58:36-07:00" level=info msg="switch line" chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=15 type=ws
time="2021-05-12T21:00:43-07:00" level=info msg="pool public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" file=loggers.go func=logging.CPrint line=168 tid=52
```

**Comment by BoShiSheng** [comment]
我也一样，使用新版本的控制台没有打印任务日志，网页后台最后在线时间也没更新。老版本的V1.05 V1.1工作正常

**Comment by trying2016** [comment]
配置APiKey了吗

**Comment by rudyzhou2** [comment]
同样问题，换回1.2.0-5就没问题了

**Comment by qxzg** [comment]
+1，目前已退回1.2版本

**Comment by fAnchao1** [comment]
垃圾v1.3啊，官方能不能测试好再放出来

**Comment by trying2016** [comment]
v1.3.0-2版本优化加载速度
https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-2

**Comment by fAnchao1** [comment]
> v1.3.0-2版本优化加载速度
> https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-2

优化个屁，越来越慢

**Comment by BoShiSheng** [comment]
> v1.3.0-2版本优化加载速度
> https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-2



> 配置APiKey了吗

你好，我从1.05版本开始用，现在使用的是V1.1，试了下V1.3.0-2不能用，APikey配置过了，我还试了下V1.2.0-5的，可以用，就是现在这个V1.3用不了，没有任务信息，打印msg=”pool public key Xxxx“后就没动静了。

**Comment by vay007** [comment]
> v1.3.0-2版本优化加载速度
> https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-2

还是不行啊。

**Comment by trying2016** [comment]
v1.3.0-3处理了没任务问题
https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-3
