### ISSUE TITLE
v1.3.0版本载入一个小时还不行，官方都不测试好再放出来？

### ISSUE THREAD

**Issue by fAnchao1** [hpool-dev/chia-miner#199]
之前用的v1.1，贼稳定。今天看到公告换1.3，载入了一个多小时都不行，大家也是这样嘛。
好不负责任啊

**Comment by trying2016** [comment]
v1.3.0-2版本优化加载速度
https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-2

**Comment by herotm** [comment]
这个软件要考虑到 如果有一个硬盘同时被plot文件写入进去会影响扫描速度。。的话 就先跳过 那个directory。。 不然扫描都要半天 等文件写入完。。

我已经将近2个小时掉线了 就是因为他在一直等着扫

**Comment by trying2016** [comment]
加载慢的更新到最新版本

**Comment by herotm** [comment]
我现在用的就是1.0.3-2

**Comment by hxl9654** [comment]
1.3.0-2有卵用啊，加载是快了，结果卡在100%不开始挖矿。能不能测试好再发布，我们不是小白鼠
这个版本质量还想明天全量切130？？？
Loading plotter files /xxxxx (yyy/yyy) 100%
@trying2016

**Comment by herotm** [comment]
一直在这个正常么 。。。。

没动静

INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/0             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/1             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/2             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/3             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/4             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/5             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/6             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/7             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:10-07:00] scan chia plot directory: /data/8             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/9             file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/10            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/11            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/12            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/13            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/14            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/15            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/16            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/17            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/18            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/19            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/20            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/21            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/22            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/23            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/24            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/25            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/26            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/27            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:15:11-07:00] scan chia plot directory: /data/28            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:29-07:00] scan chia plot directory: /data/29            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:29-07:00] scan chia plot directory: /data/30            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:29-07:00] scan chia plot directory: /data/31            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:29-07:00] scan chia plot directory: /data/32            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:57-07:00] scan chia plot directory: /data/33            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:57-07:00] scan chia plot directory: /data/34            file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-12T22:16:57-07:00] scan chia plot directory: /data/35            file=loggers.go func=logging.CPrint line=168 tid=10

**Comment by rikka0w0** [comment]
On my machine, it seemed that it successfully scanned all plots (and found), but then stuck:
```
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.3.0
**** BuildTime:2021-05-13-04:53:18 GMT
**** MinerName:xxxxxxxx
***************************************************
INFO[2021-05-13T15:18:59+10:00] pool public key: xxxxxxxxxxxxxxxxxxxxxxx file=loggers.go func=logging.CPrint line=168 tid=41
INFO[2021-05-13T15:18:59+10:00] switch line                                   chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=15 type=ws
```

**Comment by trying2016** [comment]
v1.3.0-3处理了没任务问题
https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-3

**Comment by MeowFET** [comment]
v1.3.0-3 仍然不行，日志如下

INFO[2021-05-13T05:42:56Z] scan chia plot directory: /root/sda1/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:42:56Z] scan chia plot directory: /mnt/sdb/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:44:56Z] scan chia plot directory: /root/sda1/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:44:56Z] scan chia plot directory: /mnt/sdb/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:46:56Z] scan chia plot directory: /root/sda1/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:46:56Z] scan chia plot directory: /mnt/sdb/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:48:56Z] scan chia plot directory: /root/sda1/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:48:56Z] scan chia plot directory: /mnt/sdb/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10
INFO[2021-05-13T05:50:01Z] switch line                                   chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=15 type=ws
INFO[2021-05-13T05:50:56Z] scan chia plot directory: /root/sda1/plots/plots  file=loggers.go func=logging.CPrint line=168 tid=10


回退到 1.2.0，一切正常


INFO[2021-05-13T05:59:22Z] init server                                   file=loggers.go func=logging.CPrint line=168 tid=99 type=ws url="wss://chia-cd1.hpool.com/x-proxynode/ws"
INFO[2021-05-13T05:59:25Z] connect success                               file=loggers.go func=logging.CPrint line=168 tid=99 url="wss://chia-cd1.hpool.com/x-proxynode/ws"
INFO[2021-05-13T05:59:26Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273155 jobId=3786055947 line=168 scan consume=0 scan time="1970-01-01 00:00:00" tid=59
INFO[2021-05-13T05:59:35Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273156 jobId=473627561 line=168 scan consume=0 scan time="2021-05-13 05:59:26" tid=59
INFO[2021-05-13T05:59:46Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273156 jobId=706514147 line=168 scan consume=176 scan time="2021-05-13 05:59:35" tid=59
INFO[2021-05-13T05:59:53Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273158 jobId=3741320047 line=168 scan consume=176 scan time="2021-05-13 05:59:46" tid=59
INFO[2021-05-13T06:00:03Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273158 jobId=2028008247 line=168 scan consume=176 scan time="2021-05-13 05:59:53" tid=59
INFO[2021-05-13T06:00:09Z] new mining info                               capacity="10.50 TB" file=loggers.go func=logging.CPrint height=273159 jobId=3876829501 line=168 scan consume=176 scan time="2021-05-13 06:00:03" tid=59

**Comment by mukioZ** [comment]
都是他们自家写的1.3-3，和1.041，后者版本老但是还正常，前者新结果有问题，报告扫盘有问题就和机器人一样回复硬件问题，同一套硬件老版本能用新版本不能用能是硬件问题？说说还急到关issue...

**Comment by vay007** [comment]
一个目录里面50多个plot，扫一会儿就超时了。还不让继续挖了。

**Comment by trying2016** [comment]
扫盘时间和扫盘方式是官方的，如果出现扫盘超时，需要自行检测硬件。
就版本不检测不代表你扫盘就是合格。
要求扫盘时间不能大于5s，不理解为什么限制时间的可以看看这个。
https://github.com/Chia-Network/chia-blockchain/blob/1.1.5/chia/harvester/harvester_api.py#L201

**Comment by vay007** [comment]
打印了个warning，但是能继续挖啊。如果强制下线，估计很多算力会上不来。

**Comment by wyzmlr** [comment]
> 打印了个warning，但是能继续挖啊。如果强制下线，估计很多算力会上不来。

同意楼上说法，官方限制的超时时间准确说是30s提交中间区块到网络，5s仅仅是给个警告日志而已，只有超过30s才没有收益。
国外一个论坛也有人问类似问题，https://chiaforum.com/t/new-warning-this-should-be-below-5-seconds-to-minimize-risk-of-losing-rewards/1285。强制下线确实会导致算力为0。。。
