### ISSUE TITLE
频繁闪退

### ISSUE THREAD

**Issue by ChinaArJun** [hpool-dev/chia-miner#2]

**Comment by sumengliu** [comment]
我也是，什么时候能改好？

**Comment by flaredl** [comment]
same here, plz fix ...

**Comment by flaredl** [comment]
来个闪退再开的脚本先用着吧。。扫描间隔60s
-------------------
@echo off
:en
pushd D:\HPool-Miner-chia-v1.0.4.1\windows
set p=hpool-miner-chia-gui.exe
tasklist|findstr /i %p%||start "" "%p%"
ping -n 60 127.0.0.1>nul
goto en

**Comment by szdyg** [comment]
经常闪退

**Comment by h9-dev** [comment]
关于windows版本的闪退，已发步新版本来处理这个问题，请从 https://github.com/hpool-dev/chia-miner/releases/tag/v1.0.5 下载，这是测试版本。发生闪退，可能是您做的 PLOT 文件有问题，注意观察新版本 miner 的日志，这里回答输出错误的问题名称，这里需要你重新制作文件。

**Comment by h9-dev** [comment]
> ## 来个闪退再开的脚本先用着吧。。扫描间隔60s
> @echo off
> :en
> pushd D:\HPool-Miner-chia-v1.0.4.1\windows
> set p=hpool-miner-chia-gui.exe
> tasklist|findstr /i %p%||start "" "%p%"
> ping -n 60 127.0.0.1>nul
> goto en

请勿使用，这会导致你的贡献点无法上传。
