### ISSUE TITLE
when Raspberry pie

### ISSUE THREAD

**Issue by ghost** [hpool-dev/chia-miner#20]
When will hpool support Raspberry pie?
Hpool挖chia什么时候能支持树莓派呢？

**Comment by h9-dev** [comment]
我们正在计划支持 ARM 的 CPU，目前还没有确定的时间，请关注我们的更新日志。

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
