### ISSUE TITLE
1.3 -3版本一旦目录有tmp文件扫盘极慢

### ISSUE THREAD

**Issue by mukioZ** [hpool-dev/chia-miner#205]
你们能不能测一下再发啊，现在体验还不如最早的1.041，另外是把UI也开除了？

**Comment by trying2016** [comment]
Miner扫盘方式和CHIA官方是一致的。如果扫盘慢，建议检测硬件。

**Comment by vay007** [comment]
那为什么要强制升级呢？之前的版本是没有扫盘超时的，也能挖矿啊。

**Comment by mukioZ** [comment]
你们自家做的1.041扫盘很快，然后1.3-3扫盘有问题，换1.041扫盘又正常了，你说检测硬件？你咋不检测你脑袋呢？

**Comment by trying2016** [comment]
老版本没检测扫盘时间并不代表你扫盘没问题.
