### ISSUE TITLE
Invalid file 验证是否有问题?

### ISSUE THREAD

**Issue by 34010493** [hpool-dev/chia-miner#208]
今天尝试不同的客户端, 出现了以下奇怪问题:
在1.3.0-2下, 有一个文件被标记为 invalid.  然后在1.2.0-5下再次尝试加载, 同样也报错.
觉得可能是文件损坏了?
于是花了点时间装了Prooveofspace 准备去检查一下. 这时候过去了大概2小时了, 重新打开1.2.0-5,原本被标记为invalid的文件居然通过了...但是另一个目录中的一个文件被标记为invalid... 
然后立即用Prooveofspace去验证这个文件, 可以正常通过.

Proof verification suceeded. k = 32
Total success: 8/5, 160%.

**Comment by trying2016** [comment]
建议下载1.3.0-3版本尝试下
https://github.com/hpool-dev/chia-miner/releases/tag/v1.3.0-3

**Comment by 34010493** [comment]
感谢回复, 目前文件都扫出来了.
