### ISSUE TITLE
报错dlopen err: dlopen(libchiapos.dylib, 9): image not found

### ISSUE THREAD

**Issue by BaoTaoqi** [hpool-dev/chia-miner#21]
这个动态库文件在哪，下载的macos版本里没有，lib“chia“”pos”一看就是自己写的呀

**Comment by h9-dev** [comment]
> 这个动态库文件在哪，下载的macos版本里没有，lib“chia“”pos”一看就是自己写的呀

多谢提示。`dlopen err: dlopen(libchiapos.dylib, 9): image not found` 这个只是日志打印了，其实并不需要此文件，下个版本我们会删除这个日志。

**Comment by BaoTaoqi** [comment]
> > 这个动态库文件在哪，下载的macos版本里没有，lib“chia“”pos”一看就是自己写的呀
> 
> 多谢提示。`dlopen err: dlopen(libchiapos.dylib, 9): image not found` 这个只是日志打印了，其实并不需要此文件，下个版本我们会删除这个日志。

但是程序直接闪退呀……1.0.4.1是隔几十分钟闪退，1.0.5直接就闪退了
