### ISSUE TITLE
11106 - 无效的绑定数据

### ISSUE THREAD

**Issue by summitn** [hpool-dev/chia-miner#211]
![image](https://user-images.githubusercontent.com/14501789/118096005-678b0e00-b403-11eb-9316-149b56210b53.png)

请问这个是什么原因啊 需要怎么解决,今天才发现这个问题我已经白白打工好多天了...

**Comment by summitn** [comment]
官网电话没人接 微信加不进 QQ没人回 邮件也一样,快救救我 快救救我 快救救我

**Comment by trying2016** [comment]
绑定数据需要用私钥在签名软件中获取签名数据。
https://www.hpool.com/help/tutorial/Chia挖矿教程

**Comment by summitn** [comment]
解决了,之前生成的不能重复使用么 - -|
