### ISSUE TITLE
误判双挖

### ISSUE THREAD

**Issue by chengyap98** [hpool-dev/chia-miner#219]
我已经联络了客服，但是客服没有回复。我有矿池收益错开的证据截图，邮件也根据官方的格式，给出了相应的资料。不过从5月6号到今天都未收到任何官方的回复，昨天加上了官方的微信，也没回复。 

到底是要多久呢？？？

有没有官方可以给个回复？

**Comment by zky001** [comment]
是呀  完全没人回复  我也不知道是开着chiap图还是不p

**Comment by zky001** [comment]
这都已经好长时间了

**Comment by chengyap98** [comment]
我无可奈何下 现在只能开着官方的来solo了，只从加入矿池后都好久没有solo了，没想到被两个矿池误封，具体的收益错开证据都提交了，不过都没有收到任何回复。

**Comment by zky001** [comment]
> 我无可奈何下 现在只能开着官方的来solo了，只从加入矿池后都好久没有solo了，没想到被两个矿池误封，具体的收益错开证据都提交了，不过都没有收到任何回复。

我是开着hpool的在那里跑  但是没有任何收益的显示 但是后台日志看好像还在挖

**Comment by chengyap98** [comment]
> > 我无可奈何下 现在只能开着官方的来solo了，只从加入矿池后都好久没有solo了，没想到被两个矿池误封，具体的收益错开证据都提交了，不过都没有收到任何回复。
> 
> 我是开着hpool的在那里跑 但是没有任何收益的显示 但是后台日志看好像还在挖

我也有测试，后台确实有在跑，也有显示矿机在线，不过没有收益，怎么挖啊，心累啊

**Comment by zky001** [comment]
> 我也有测试，后台确实有在跑，也有显示矿机在线，不过没有收益，怎么挖啊，心累啊

我直接重装系统，重新挖

**Comment by chengyap98** [comment]
> > 我也有测试，后台确实有在跑，也有显示矿机在线，不过没有收益，怎么挖啊，心累啊
> 
> 我直接重装系统，重新挖

有用么？重装系统就能有收益了？

**Comment by zky001** [comment]
en

**Comment by chengyap98** [comment]
没有官方人员可以给个解决方案吗？

**Comment by zky001** [comment]
> 没有官方人员可以给个解决方案吗？

官方太不靠谱

**Comment by chengyap98** [comment]
@hpool-dev @trying2016 有没有解决方案？你们发出的让矿工写邮件给你们，5月6号写到今天，一个星期了，一个回复的邮件都没有。也不知道到底我们还需要提交那些资料。

**Comment by 85256638** [comment]
就是啊，一直没有人回复

**Comment by 85256638** [comment]
> @hpool-dev @trying2016 有没有解决方案？你们发出的让矿工写邮件给你们，5月6号写到今天，一个星期了，一个回复的邮件都没有。也不知道到底我们还需要提交那些资料

给你解封了吗大兄弟
