### ISSUE TITLE
> 这个动态库文件在哪，下载的macos版本里没有，lib“chia“”pos”一看就是自己写的呀

### ISSUE THREAD

**Issue by BaoTaoqi** [hpool-dev/chia-miner#22]
> 这个动态库文件在哪，下载的macos版本里没有，lib“chia“”pos”一看就是自己写的呀

多谢提示。`dlopen err: dlopen(libchiapos.dylib, 9): image not found` 这个只是日志打印了，其实并不需要此文件，下个版本我们会删除这个日志。

_Originally posted by @hpool-dev in https://github.com/hpool-dev/chia-miner/issues/21#issuecomment-823422704_

**Comment by BaoTaoqi** [comment]
但是1.0.5直接闪退呀……1.0.4.1隔几十分钟闪退，1.0.5直接就闪退了

**Comment by h9-dev** [comment]
> 但是1.0.5直接闪退呀……1.0.4.1隔几十分钟闪退，1.0.5直接就闪退了

请联系客服帮你做兼容性调试。

**Comment by BaoTaoqi** [comment]
> > 但是1.0.5直接闪退呀……1.0.4.1隔几十分钟闪退，1.0.5直接就闪退了
> 
> 请联系客服帮你做兼容性调试。

开发辛苦了...但是你们客服不鸟我……我已经给他发了十几条消息了

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
