### ISSUE TITLE
1.30-3  exception : Invalid file plot-k32-2021-05-02-06-30-xxxxxxxxxxxxxxxxxxxxxxxxx.plot

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#220]
扫硬盘的时候几乎都是 这些错误。。。

我300多T的就 显示
capacity="137.05 TB" file=loggers.go func=logging.CPrint height=274141 jobId=1329193891 line=168 scan consume=540 scan time="2021-05-13 03:23:39" tid=356

怎么回事

**Comment by herotm** [comment]
ERRO[2021-05-13T03:26:18-07:00] 您的扫盘时间(20.06s)超过最大时间限制(10.00s)                f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,126}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=356
ERRO[2021-05-13T03:26:21-07:00] update line fail                              error="Get \"https://chia-1bca46b45f.hpool.com/proxy/wslines\": dial tcp: lookup chia-1bca46b45f.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:22-07:00] update line fail                              error="Get \"http://chia-15116df3dd.hpool.cn/proxy/wslines\": dial tcp: lookup chia-15116df3dd.hpool.cn on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:23-07:00] update line fail                              error="Get \"http://chia-14413fb6c2.hpool.xin/proxy/wslines\": dial tcp: lookup chia-14413fb6c2.hpool.xin on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:24-07:00] update line fail                              error="Get \"http://chia-5cfe939d68.hpool.cn/proxy/wslines\": dial tcp: lookup chia-5cfe939d68.hpool.cn on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:25-07:00] update line fail                              error="Get \"https://chia-2b9c5cc653.hpool.com/proxy/wslines\": dial tcp: lookup chia-2b9c5cc653.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:26-07:00] update line fail                              error="Get \"http://chia-0df3c2fd4e.hpool.xin/proxy/wslines\": dial tcp: lookup chia-0df3c2fd4e.hpool.xin on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:27-07:00] update line fail                              error="Get \"https://chia-e365767716.hpool.com/proxy/wslines\": dial tcp: lookup chia-e365767716.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:28-07:00] update line fail                              error="Get \"http://chia-4ad7d826df.hpool.cn/proxy/wslines\": dial tcp: lookup chia-4ad7d826df.hpool.cn on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:29-07:00] update line fail                              error="Get \"http://chia-85627fe3f1.hpool.xin/proxy/wslines\": dial tcp: lookup chia-85627fe3f1.hpool.xin on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:29-07:00] 扫盘超时                                          file=loggers.go func=logging.CPrint line=156 path=/data/6 scan limit=10000 scan time=20059 tid=356
INFO[2021-05-13T03:26:29-07:00] new mining info                               capacity="133.09 TB" file=loggers.go func=logging.CPrint height=274152 jobId=3230218859 line=168 scan consume=20059 scan time="2021-05-13 03:26:17" tid=356
ERRO[2021-05-13T03:26:29-07:00] 您的扫盘时间(20.06s)超过最大时间限制(10.00s)                f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,126}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=356
ERRO[2021-05-13T03:26:30-07:00] update line fail                              error="Get \"https://chia.hpool.com/proxy/wslines\": dial tcp: lookup chia.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:31-07:00] update line fail                              error="Get \"https://chia-1bca46b45f.hpool.com/proxy/wslines\": dial tcp: lookup chia-1bca46b45f.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:32-07:00] update line fail                              error="Get \"http://chia-15116df3dd.hpool.cn/proxy/wslines\": dial tcp: lookup chia-15116df3dd.hpool.cn on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:33-07:00] update line fail                              error="Get \"http://chia-14413fb6c2.hpool.xin/proxy/wslines\": dial tcp: lookup chia-14413fb6c2.hpool.xin on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:34-07:00] update line fail                              error="Get \"http://chia-5cfe939d68.hpool.cn/proxy/wslines\": dial tcp: lookup chia-5cfe939d68.hpool.cn on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:35-07:00] update line fail                              error="Get \"https://chia-2b9c5cc653.hpool.com/proxy/wslines\": dial tcp: lookup chia-2b9c5cc653.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:36-07:00] update line fail                              error="Get \"http://chia-0df3c2fd4e.hpool.xin/proxy/wslines\": dial tcp: lookup chia-0df3c2fd4e.hpool.xin on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30
ERRO[2021-05-13T03:26:37-07:00] update line fail                              error="Get \"https://chia-e365767716.hpool.com/proxy/wslines\": dial tcp: lookup chia-e365767716.hpool.com on 8.8.8.8:53: dial udp 8.8.8.8:53: socket: too many open files" f7="{loggers.go,logging.CPrint,156}" f8="{manager.go,line.(*Manager).update,114}" f9="{timer.go,utils.StartTime.func1,26}" tid=30

**Comment by zky001** [comment]
求官方人员联系！

**Comment by zky001** [comment]
联系不上官方人员！

**Comment by a1147211355** [comment]
me too!!!

**Comment by zky001** [comment]
> me too!!!

算了算了  重新弄个钱包solo吧  再也不信hpool了
