### ISSUE TITLE
为什么Mac挖的时候，HPool没有显示矿机在线？

### ISSUE THREAD

**Issue by PresidentCake** [hpool-dev/chia-miner#25]

**Comment by bobyuxinyang** [comment]
遇到同样的问题，待解决中

**Comment by PresidentCake** [comment]
而且我发现我把田文件已去，终端执行文件依旧是那个样子，好像一开始就没有在耕田……不知道是设置不对还是怎样，教程是按Linux来的，官方也没有相关的操作说明

**Comment by only145** [comment]
同样问题，挖矿程序显示new mining info 什么什么的，但是矿池里没有矿机

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
