### ISSUE TITLE
HPool-Miner-Chia v1.3.0-3 Undistribute Mined does not run after 10:30 am 14/05/2021 (utc + 7)

### ISSUE THREAD

**Issue by toy23** [hpool-dev/chia-miner#253]
![image](https://user-images.githubusercontent.com/80647088/118310819-4a486380-b519-11eb-9a56-b98ae1c85498.png)

![image](https://user-images.githubusercontent.com/80647088/118311401-0dc93780-b51a-11eb-93ff-c72c5a061a04.png)

Undistribute Mined does not run after 10:30 am (utc + 7)

Please help me.....

**Comment by oit63** [comment]
me too, from centos

**Comment by Grzesiek83** [comment]
Same here... from block height 280850 (20:17 CET) @Windows

**Comment by repe4t** [comment]
me too…
＠Windows

**Comment by RishabhKumarRK** [comment]
i am having same problem, has it solved yet?

**Comment by HuoYuanjia07** [comment]
Same for me, stopped at 10:30AM @Windows and @BootCampWindows
"278660 | 2021/05/14 10:31:19"

**Comment by JohnUSL** [comment]
updated but still it is not running... is there anybody who solved??

**Comment by HuoYuanjia07** [comment]
I'm using the 1.2.0 (build5) and it works

**Comment by toy23** [comment]
> I'm using the 1.2.0 (build5) and it works

seriously..??

**Comment by HuoYuanjia07** [comment]
> > I'm using the 1.2.0 (build5) and it works
> 
> seriously..??

Yes

**Comment by toy23** [comment]
> > > I'm using the 1.2.0 (build5) and it works
> > 
> > seriously..??
> 
> Yes

can display the revenue tab ?

**Comment by HuoYuanjia07** [comment]
> > > > I'm using the 1.2.0 (build5) and it works
> > > 
> > > 
> > > seriously..??
> > 
> > 
> > Yes
> 
> can display the revenue tab ?

![Revenue Tab](https://user-images.githubusercontent.com/68485405/118396467-f42a0c00-b64f-11eb-9e2a-866a732ef08b.PNG)

**Comment by toy23** [comment]
> 
> 
> 
> > > > > I'm using the 1.2.0 (build5) and it works
> > > > 
> > > > 
> > > > seriously..??
> > > 
> > > 
> > > Yes
> > 
> > can display the revenue tab ?
> 
> ![Revenue Tab](https://user-images.githubusercontent.com/68485405/118396467-f42a0c00-b64f-11eb-9e2a-866a732ef08b.PNG)

Wow... 😁
Houw much plot?

**Comment by HuoYuanjia07** [comment]
I have 16 plot for the moment haha
But I have only 6.35To in total I have to buy more HDD haha

**Comment by 0x4res** [comment]
> J'ai 16 parcelles pour le moment haha
> Mais je n'ai que 6,35 Au total, je dois acheter plus de disque dur haha

Your miner still works now ?

**Comment by HuoYuanjia07** [comment]
Yes still work
