### ISSUE TITLE
能否选择网络映射的磁盘

### ISSUE THREAD

**Issue by xiongz-c** [hpool-dev/chia-miner#26]
p完的盘挂载在nas的磁盘上，软件的选择位置不能选择网络磁盘，chia的钱包是可以的。不知道是软件的问题还是权限的问题？

**Comment by firstfsx** [comment]
建议支持，官方原版可以支持选择网络驱动器作为存储路径

**Comment by h9-dev** [comment]
多谢反馈，我们将在下一个版本更新中支持。

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by clhaaaa** [comment]
![image](https://user-images.githubusercontent.com/13366961/116823583-e5efe080-abb7-11eb-9ee6-5e7641e6ef0b.png)
当真修复了???

**Comment by clhaaaa** [comment]
![image](https://user-images.githubusercontent.com/13366961/116823605-015aeb80-abb8-11eb-828c-cad520f558d7.png)
真的修复了吗?
