### ISSUE TITLE
建议加入一个防硬盘休眠功能

### ISSUE THREAD

**Issue by Onion-Official** [hpool-dev/chia-miner#265]
我使用了外置硬盘盒，硬盘盒带有自动休眠功能并且无法关闭。
我只好下载了一个小工具，每隔一段时间向硬盘内写入一个小文件并删除。
唯一的需求就是可自定义重复时间

**Comment by h9-dev** [comment]
多谢反馈，确实需要做一个这个功能。之前我们BHD 的锄头是有这个功能的。
对于8T 的硬盘满文件是每10s 左右就会有读取数据，通常也不应该出现休眠问题，小硬盘可能会出现问题。

现在你可以通过做一个定时脚本执行dir 命令来防止休眠。
