### ISSUE TITLE
算力突然全部离线

### ISSUE THREAD

**Issue by wzxsydney** [hpool-dev/chia-miner#269]
矿机显示正常算力在线，但是在线算力全部显示离线，没有收益，日志没有任何异常

**Comment by manfye** [comment]
+1

**Comment by zgglj2** [comment]
+1

**Comment by BJ5129** [comment]
+1

**Comment by frangere** [comment]
+1
最后一次收益 283390  2021/05/15 14:36:13，之后就没有任何收益了。全部算力离线，log里面也没有其他错误。矿机显示都在线。

**Comment by gaoterry** [comment]
+1

**Comment by andrejreimer** [comment]
Same here alll miners are online but no income...

**Comment by qqqqww1** [comment]
+1

**Comment by reason211** [comment]
+2

**Comment by artemka13722** [comment]
+3

**Comment by anonfarmer** [comment]
Last height 283390. No revenue.

**Comment by mikewubox** [comment]
+1

**Comment by qingyufei** [comment]
+1

**Comment by marciomvm** [comment]
I had the same issue yesterday. I stopped everything and started again. After that, I started seeing again. No idea what is the problem
