### ISSUE TITLE
能否支持arm64架构呀

### ISSUE THREAD

**Issue by biolzhu** [hpool-dev/chia-miner#27]
我的电脑，树莓派都是arm64架构的，硬盘挖矿好像并不需要那么高的能耗，树莓派好像就够了，编译个arm64版本吧，求求啦

**Comment by yiday** [comment]
同求，在树莓派原生系统上运行出错，不知道将树莓派系统改为centos能不能运行

**Comment by tanxjian** [comment]
> 同求，在树莓派原生系统上运行出错，不知道将树莓派系统改为centos能不能运行

直接修改系统不行，现在的版本是intel x86 架构，不支持arm64 cpu架构，需要他们重新编译一份支持arm64的运行文件

**Comment by sf2046** [comment]
同求

**Comment by betterA** [comment]
同求

**Comment by Sinowrt** [comment]
用qemu可以在树莓派上面运行hpool-miner-chia，效率如何就不清楚了，参考[这篇博文](https://blog.sinowrt.cn/2021/2021-04-23t1847-how-to-run-chia-miner-of-hpool-on-raspberry-pi4/)

**Comment by Sinowrt** [comment]
用qemu可以在树莓派上面运行hpool-miner-chia，效率如何就不清楚了，参考[这篇博文](https://blog.sinowrt.cn/2021/2021-04-23t1847-how-to-run-chia-miner-of-hpool-on-raspberry-pi4/)

**Comment by rmokerone** [comment]
hpool太封闭了，还是等官方的池协议出来吧。

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
