### ISSUE TITLE
HP这波操作666

### ISSUE THREAD

**Issue by BJ5129** [hpool-dev/chia-miner#273]
![image](https://user-images.githubusercontent.com/37569731/118353800-896ac900-b59a-11eb-9b39-516120d2742b.png)
![image](https://user-images.githubusercontent.com/37569731/118353806-9687b800-b59a-11eb-819f-b5a6219781f2.png)
  这图就说明了很多问题 其实那些算力根本没掉线 看全网算力还是在线的 内幕？

**Comment by ganyao114** [comment]
傻逼有 bug，我朋友收益突然double，而我掉线了

**Comment by cooshare** [comment]
吃相太难看

**Comment by BJ5129** [comment]
![image](https://user-images.githubusercontent.com/37569731/118355694-e7e87500-b5a3-11eb-95df-2ff8528f8f86.png)
掉0了  官方也联系不上  有没有来扯蛋的

**Comment by trying2016** [comment]
服务器在维护升级，升级完后，会重新修正不正常收益数据。
