### ISSUE TITLE
14:36 分以後任何收益也沒有，軟件也在運行，究竟要不要繼續?

### ISSUE THREAD

**Issue by chiagod77** [hpool-dev/chia-miner#277]
![image](https://user-images.githubusercontent.com/84200636/118355334-02215380-b5a2-11eb-9e17-858a92bab7b3.png)

**Comment by alexJew322** [comment]
same

**Comment by michaellaw2000** [comment]
same

**Comment by h9-dev** [comment]
等待数据同步，从1点开始重新分配收益。

**Comment by b02505048** [comment]
Hi @hpool-dev，請問何時會完成收益的重新分配呢？
目前已經可以看見新的收益，但5月15日下午 1 點後的收益依舊還沒顯示
