### ISSUE TITLE
官方钱包和这个可以同时挖吗?

### ISSUE THREAD

**Issue by FOnlyJack** [hpool-dev/chia-miner#28]

**Comment by hkfires** [comment]
开可以同时开，就是不知道会不会生效

**Comment by h9-dev** [comment]
不可以共用同一份文件，复制出来的也不可以。如果检测到你在非矿池钱包出块，那么就会对你的账户做出惩罚。双挖对任何人都是不利的，我们矿池有完善的防多挖机制。

**Comment by yanest** [comment]
如果想退出矿池，之前通过hpool p的图，我导入官方钱包可以不

> 不可以共用同一份文件，复制出来的也不可以。如果检测到你在非矿池钱包出块，那么就会对你的账户做出惩罚。双挖对任何人都是不利的，我们矿池有完善的防多挖机制。

**Comment by jonny77** [comment]
> 不可以共用同一份文件，复制出来的也不可以。如果检测到你在非矿池钱包出块，那么就会对你的账户做出惩罚。双挖对任何人都是不利的，我们矿池有完善的防多挖机制。

plot文件不多的情况下, 如果官方的出块,封了就封了呗, 有什么关系

**Comment by PresidentCake** [comment]
同时的话，官方挖的会失效，但我一般两个都放着，因为用官方软件p

**Comment by kamike** [comment]
官方的出块就封了？无法停止在p盘过程中官方钱包自己挖矿啊？难道你们软件提供p盘功能？

**Comment by PresidentCake** [comment]
现在官网上已经有提供操作方式不双挖了

**Comment by PresidentCake** [comment]
至于p盘的程序早就有了

**Comment by FOnlyJack** [comment]
关闭
