### ISSUE TITLE
Hpool跑路了

### ISSUE THREAD

**Issue by HailongZhu** [hpool-dev/chia-miner#281]
挖矿没收益，官网登不上，客服无回复，怕是跑路了。

**Comment by mukioZ** [comment]
全网块一直在出，算力也没爆降，那就意味着我们的算力文件一直在工作，但是收益没有了，这中间的收益到时候还给不给了？

**Comment by trying2016** [comment]
服务器在维护升级，服务器升级不影响挖矿。请勿散播不实言论

**Comment by HailongZhu** [comment]
> 全网块一直在出，算力也没爆降，那就意味着我们的算力文件一直在工作，但是收益没有了，这中间的收益到时候还给不给了？

开玩笑，之前封禁双挖用户冻结的收益给了吗？

**Comment by breakertt** [comment]
迫真大言不惭....两点多大家都掉了啊....还不影响
