### ISSUE TITLE
收益正常个头

### ISSUE THREAD

**Issue by HailongZhu** [hpool-dev/chia-miner#282]
算力全掉超过三个小时了，期间零收益，现在直接官网维护，客服也找不到，开issue就关，还骗鬼说收益正常？

**Comment by trying2016** [comment]
维护后，之前收益会重新计算

**Comment by jeppsp** [comment]
维修时间预测是多少？

**Comment by breakertt** [comment]
按照什么时间的有效算力重新计算收益呢

**Comment by mukioZ** [comment]
你们就几个客服微信，基本加不到，qq客服从来不回，官网一有事就是维护中，那官网能不能维护页面加下公告，因为什么维护，大概多久？总不能每次来这发言辞激烈的issue才有回应吧

**Comment by breakertt** [comment]
这期间能不能换到 uupool 去？

**Comment by trying2016** [comment]
会按照正常在线时间的收益计算，不影响挖矿收益。

**Comment by BigUncle** [comment]
我暂时先转UUPOOL了

**Comment by breakertt** [comment]
那两点多掉的那波么 有没有补偿

**Comment by trying2016** [comment]
实际没掉线，数据同步问题。收益数据都在。

**Comment by h9-dev** [comment]
会从1点开始重新分发收益。

**Comment by trying2016** [comment]
是按照正常收益走，不存在补偿的问题

**Comment by breakertt** [comment]
所以到时候贡献的那个图也会修复 对吗

**Comment by teklab-de** [comment]
完美的。谢谢

**Comment by Huziyi** [comment]
加油解决吧，矿工增长太快，赶快增添服务器和人手咯，实在不行限制一下新会员注册，免得客户流失率，飙咯。

**Comment by h9-dev** [comment]
> 加油解决吧，矿工增长太快，赶快增添服务器和人手咯，实在不行限制一下新会员注册，免得客户流失率，飙咯。

嗯，希望大家理解。业务增长远超了预期。问题很快解决，为大家发放收益。

**Comment by mezhangyes** [comment]
说好的重新算呢？直接算我下线？

**Comment by ChenCai** [comment]
偷收益，偷收益，偷收益。

**Comment by HailongZhu** [comment]
> > 加油解决吧，矿工增长太快，赶快增添服务器和人手咯，实在不行限制一下新会员注册，免得客户流失率，飙咯。
> 
> 嗯，希望大家理解。业务增长远超了预期。问题很快解决，为大家发放收益。

所谓解决问题就是不但“掉线”后的算力不补，连掉线前的收益都扣了？

**Comment by arandomg** [comment]
> 是按照正常收益走，不存在补偿的问题

你这天天拉跨不补偿，人家氪金手游定期维护都补偿

**Comment by trying2016** [comment]
收益数据在排队结算，用户收益数据都在，不会少。
需要注意的是Miner不能离线

**Comment by fgc0109** [comment]
吊炸天哦
我原本一天看都是在线,你们所谓的补收益,全部算我下线?????????
把我补给别人??????????
你们这是在解决问题??今天的收益被你们扣的还不到平时的一半

**Comment by h9-dev** [comment]
> 吊炸天哦
> 我原本一天看都是在线,你们所谓的补收益,全部算我下线?????????
> 把我补给别人??????????
> 你们这是在解决问题??今天的收益被你们扣的还不到平时的一半

还没发完啊，你看时间都每跟上。
