### ISSUE TITLE
可以给的预估恢复正常的时间吗？

### ISSUE THREAD

**Issue by cklogic** [hpool-dev/chia-miner#287]

**Comment by trying2016** [comment]
预计2小时

**Comment by ddrcpddr** [comment]
你们网站倒是能进了，5月15日的收益直接给我清零了？明明下午14:00左右还有几次收益，现在给我回滚到昨天了？@trying2016

**Comment by trying2016** [comment]
用户数据从下午1点开始重新结算，用户数比较多
您今天的收益可能会迟到，但是肯定会到，请放心
