### ISSUE TITLE
问题何时解决？

### ISSUE THREAD

**Issue by Ruslame** [hpool-dev/chia-miner#288]
技术工作需要多长时间？ 从昨天起，与筏的问题，他们被关闭在早上，今天上午10点付款后，太。 这个问题何时解决，是否会有任何补偿？ 我的采矿不断工作，但付款不收取。

**Comment by h9-dev** [comment]
收益会发给有贡献的矿工的，请保持矿机在线。

**Comment by Ruslame** [comment]
> 收益会发给有贡献的矿工的，请保持矿机在线。

禁用筏子的问题是否会得到解决？

**Comment by inSight-mk1** [comment]
> > 收益会发给有贡献的矿工的，请保持矿机在线。
> 
> 禁用筏子的问题是否会得到解决？

You can post in English. Developers can read English.

**Comment by trying2016** [comment]
收益数据在排队结算，用户收益数据都在，不会少。
需要注意的是Miner不能离线

**Comment by h9-dev** [comment]
已经解决。
