### ISSUE TITLE
你们直接清零5月15日的收益，把收益明细回滚到昨天这波操作真的牛！

### ISSUE THREAD

**Issue by ddrcpddr** [hpool-dev/chia-miner#293]
请问我5月15日的收益去哪儿了？ @trying2016 @hpool-dev

**Comment by ludwigjer** [comment]
是的，还说让我不要乱说。 跟我说什么维护的时候收益是有的。真会骗。

**Comment by ddrcpddr** [comment]
@trying2016 @hpool-dev  吃相这么难看 你们不想做了 明说出来，吊着这多么无辜的群众号称自己在维护？ 你们维护的啥？解决了啥问题，你们矿池这个地址一直在出块！请你们给个合理的解释  https://www.chiaexplorer.com/blockchain/address/xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj

**Comment by BigUncle** [comment]
> @trying2016 @hpool-dev 吃相这么难看 你们不想做了 明说出来，吊着这多么无辜的群众号称自己在维护？ 你们维护的啥？解决了啥问题，你们矿池这个地址一直在出块！请你们给个合理的解释 https://www.chiaexplorer.com/blockchain/address/xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj

区块链的技术就是全部记录公开可查，就看他们的吃相了。

**Comment by trying2016** [comment]
收益数据在排队结算，用户收益数据都在，不会少。
需要注意的是Miner不能离线
