### ISSUE TITLE
垃圾Hpool疯狂偷收益

### ISSUE THREAD

**Issue by HailongZhu** [hpool-dev/chia-miner#294]
日常收益低20%我们忍了，可是无缘无故掉线扣收益是为什么？
不但掉线期间的收益为0，连掉线之前发放的收益都被扣了！官网掉线前今日收益是0.04，一维护就给扣到0.029，真是666
掉线期间hpool共挖了2000+的币，直接入账2000多万，暴富原来如此简单！！！

**Comment by trying2016** [comment]
收益数据在排队结算，用户收益数据都在，不会少。
需要注意的是Miner不能离线
