### ISSUE TITLE
如果不解决偷收益的问题，建议官方投诉

### ISSUE THREAD

**Issue by ChenCai** [hpool-dev/chia-miner#295]

**Comment by HailongZhu** [comment]
官方也管不了hpool，区块链就是这样，唉。
只能等官方的pool出来之后跳槽了。

**Comment by arandomg** [comment]
投诉有个屁用你走就完了腿在你自己身上清醒点兄弟

**Comment by nero13854** [comment]
我记得eth和eos都封过地址，它不解决我建议向bram提议把它封了，反正bram也看hpool不顺眼

**Comment by trying2016** [comment]
收益数据在排队结算，用户收益数据都在，不会少。
需要注意的是Miner不能离线

**Comment by tivizi** [comment]
https://www.chiaexplorer.com/blockchain/address/xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj

**Comment by hpool-dev** [comment]
> https://www.chiaexplorer.com/blockchain/address/xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj
> 每分钟都在出块，为什么我的收益隔几十分钟才有一条？

不是一个出块对应一条收益，收益是合并的，10-50区块一次。另外发放还在排队。
