### ISSUE TITLE
请帮忙取消谷歌验证器绑定 有币取不出现在

### ISSUE THREAD

**Issue by feiyangssc** [hpool-dev/chia-miner#297]
由于不小心将哈池谷歌验证器那个码删除 现在提现获取不到谷歌验证码 麻烦帮忙取消我账户绑定的谷歌验证器 或者帮忙再发一次哈池谷歌验证器那个秘钥 谢谢。我哈池账号:3209421895@qq.com 验证器秘钥你可以发我这个邮箱 或者帮忙直接取消那个谷歌验证器绑定 麻烦了

**Comment by feiyangssc** [comment]
![Uploading mmexport1621091342841.jpg…]()

**Comment by h9-dev** [comment]
这种情况需要你去找到客服在 KYC 的，我们这边没法操作这个，也没法验证你是否被盗号。

**Comment by feiyangssc** [comment]
肯定不是盗号啊 我现在发信息给你的邮箱就是我自己的邮箱 主要你们客服联系了一个礼拜都没有一个人答复我 在线也留言了 QQ 微信 电话 还有短信 没有一个人给我解决这个问题 如果盗号 能把QQ 微信 还有手机号全盗了吗？你们可以让我使用手机验证码来验证是不是盗号了。现在账户的币取不出来 我找谁去&nbsp;



---原始邮件---
发件人: "HPool ***@***.***&gt;
发送时间: 2021年5月15日(周六) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hpool-dev/chia-miner] 请帮忙取消谷歌验证器绑定 有币取不出现在 (#297)




 
这种情况需要你去找到客服在 KYC 的，我们这边没法操作这个，也没法验证你是否被盗号。
