### ISSUE TITLE
不能随开机或者登陆自动启动？

### ISSUE THREAD

**Issue by NoooBird** [hpool-dev/chia-miner#3]
如题，不管是加入启动项还是计划任务都不行

**Comment by hotcpu1949** [comment]
等修改吧，可能的原因见我回复

**Comment by h9-dev** [comment]
> 如题，不管是加入启动项还是计划任务都不行

通常加入系统启动项即可。是否报告错误了呢？

**Comment by chenfangshuo** [comment]
> 如题，不管是加入启动项还是计划任务都不行

可以用nssm打包那个console版本成服务

**Comment by siben168** [comment]
> > 如题，不管是加入启动项还是计划任务都不行
> 
> 通常加入系统启动项即可。是否报告错误了呢？

我的情况是1.4版本的时候是可以直接加入任务计划开机无需登录启动, 1.6不行了, 换了启动项,做成服务都报错. 
错误内容"The service process could not connect to the service controller."

**Comment by trying2016** [comment]
miner已经支持命令行添加服务。
用管理员运行CMD，CD 到软件目录下.
安装：hpool-miner-chia-console.exe -service install
运行：hpool-miner-chia-console.exe -service start
具体说明：hpool-miner-chia-console.exe --help

**Comment by siben168** [comment]
> miner已经支持命令行添加服务。 用管理员运行CMD，CD 到软件目录下. 安装：hpool-miner-chia-console.exe -service install 运行：hpool-miner-chia-console.exe -service start 具体说明：hpool-miner-chia-console.exe --help

感谢及时回复! 已经试过可以了.  这个issue可以关了.

给后来人参考:  有部分网盘需要等待网络服务, 可以设成自动(延迟)服务 效果最佳.
