### ISSUE TITLE
bug.: 连不上wss://chia-sh0.hpool.com/x-proxynode/ws

### ISSUE THREAD

**Issue by oldthreefeng** [hpool-dev/chia-miner#31]
(*Server).connect,67}" f9="{server.go,websocket.(*Server).check,43}" tid=130 url="wss://chia-sh0.hpool.com/x-proxynode/ws"
time="2021-04-22T20:06:51+08:00" level=error msg="connect fail" err="websocket: bad handshake" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,67}" f9="{server.go,websocket.(*Server).check,43}" tid=130 url="wss://chia-sh0.hpool.com/x-proxynode/ws"
time="2021-04-22T20:06:52+08:00" level=error msg="connect fail" err="websocket: bad handshake" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,67}" f9="{server.go,websocket.(*Server).check,43}" tid=130 url="wss://chia-sh0.hpool.com/x-proxynode/ws"
time="2021-04-22T20:06:53+08:00" level=error msg="connect fail" err="websocket: bad handshake" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,67}" f9="{server.go,websocket.(*Server).check,43}" tid=130 url="wss://chia-sh0.hpool.com/x-proxynode/ws"

**Comment by h9-dev** [comment]
有时链接可能不稳定，会自动重新链接上。如果一直无法连接，请查看`chia-sh0.hpool.com`DNS 解析的 IP，并用ping查看是否可以连通。

**Comment by sophware** [comment]
hia-sz2-2448f44696.hpool.com/x-proxynode/ws"
time="2021-05-21T23:32:20-04:00" level=error msg="connect fail" err="websocket: bad handshake" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,86}" f9="{server.go,websocket.(*Server).check,62}" tid=77 url="ws://chia-sz2-2448f44696.hpool.com/x-proxynode/ws"
time="2021-05-21T23:32:21-04:00" level=error msg="connect

I've been getting this all day. When I try to resolve chia-sz2-2448f44696.hpool.com or the fqdn you posted above, they get me some host at aliyunddos1003.com. Does the "ddos" in there mean I'm being treated as a one-person DDoS attack?

It's unfortunate to lose a day (or more) of mining, especially now.
