### ISSUE TITLE
Miner running but not showing online in the website

### ISSUE THREAD

**Issue by Gokuref** [hpool-dev/chia-miner#310]
> INFO[2021-05-15T17:34:14Z] new mining info                               capacity="0 B" file=loggers.go func=logging.CPrint height=285723 jobId=1030126873 line=168 scan consume=0 scan time="2021-05-15 17:34:06" tid=507
> INFO[2021-05-15T17:34:27Z] new mining info                               capacity="0 B" file=loggers.go func=logging.CPrint height=285723 jobId=758008024 line=168 scan consume=0 scan time="2021-05-15 17:34:14" tid=507
> INFO[2021-05-15T17:34:34Z] new mining info                               capacity="0 B" file=loggers.go func=logging.CPrint height=285723 jobId=3386803107 line=168 scan consume=0 scan time="2021-05-15 17:34:27" tid=507
> INFO[2021-05-15T17:34:42Z] new mining info                               capacity="0 B" file=loggers.go func=logging.CPrint height=285725 jobId=777733152 line=168 scan consume=0 scan time="2021-05-15 17:34:34" tid=507
> 

Guys, I'm running the miner cli, it's all configured, api keys, bind signature, plots and all stuff, but I see no miners online.
So, let me ask: 
- In Configurations, what's the pool address over API key? Do I need to use that address in any config?
- in Pointing, what's that srouce address? I need to use it in any config?

As far as I can see, the miner is connected and running, but there's zero miners online in the website... It's been more that 7 hours that its online and the status didn't change.  Can someone give me help? 
Thx!

img:
![12c](https://user-images.githubusercontent.com/33708227/118373312-92549e00-b58c-11eb-9474-53f9b912bf2f.jpg)

**Comment by markschrik** [comment]
It has a capacity of 0 B, which means there are no (valid) plots detected. That could be the reason.

Edit;
The API is fine, you don't need to do anything with the pool address and pointing. You should check the config if the plot locations are correct.

**Comment by h9-dev** [comment]
The friend above is right, the machine with 0 capacity will not be synchronized.
