### ISSUE TITLE
Plots are signed and im online as a miner. Reveneu problem

### ISSUE THREAD

**Issue by salvadordali1** [hpool-dev/chia-miner#313]
Plots are signed and im online as a miner. I was taking revenue until yesterday. But even everything is normal i cant earn anything. Is this situation temporary or permanent? Thank you

**Comment by DovaNuts** [comment]
Same here

**Comment by sax-ru** [comment]
Same here.  I dont have a revenue for mining process since 2021/05/14 06:30:00

**Comment by jeppsp** [comment]
Normal revenue here but Undistribute Mined has stopped.

**Comment by JohnUSL** [comment]
Undistribute Mined seems has stopped for me since 2021/05/14 06:30:00

**Comment by salvadordali1** [comment]
Hello everyone. Before post this issue i wasnt take revenue but i can right now. Maybe they are fixing problem step by step. We should wait to reflect our revenues to undistribute mined. Keep wait.

**Comment by h9-dev** [comment]
The unsettled total is updated asynchronously, and the real-time data is subject to the income details. 

Now updated. please check.

**Comment by 0x4res** [comment]
The problem as not resolved
