### ISSUE TITLE
Mining revenue had decreased

### ISSUE THREAD

**Issue by gaddars** [hpool-dev/chia-miner#316]
Hello, after the maintenance , the mining revanue had decreased.

For example if i were gathering 4000- 6000 points in one time, now i can get  only 800-1500

is it the same for you?

**Comment by salvadordali1** [comment]
what is your point by hour? its the important one

**Comment by gaddars** [comment]
in totally it decreased also

**Comment by h9-dev** [comment]
The allocation before maintenance is completely wrong, so we can only choose to roll back and recalculate.
