### ISSUE TITLE
WHAT WILL BE OUR GAINS?

### ISSUE THREAD

**Issue by alikorayozcilingir** [hpool-dev/chia-miner#318]
My entire system is active 7 hours, I cannot see an income in the revenue section. How will they fix it and give our earnings?

**Comment by sax-ru** [comment]
Same here

**Comment by PatrickCampeol** [comment]
Same here, last update of revenue was 07 hours ago.

**Comment by h9-dev** [comment]
We will create a discord channel, this problem needs to be solved by customer service.

**Comment by alikorayozcilingir** [comment]
what s your discord account sir ?
