### ISSUE TITLE
The balance does not change

### ISSUE THREAD

**Issue by Ruslame** [hpool-dev/chia-miner#319]
I get accruals, but the balance is still the same as before. It's already 3 o'clock.

![image](https://user-images.githubusercontent.com/40713656/118379536-d030e100-b5e3-11eb-86d0-386a7816dd76.png)
![image](https://user-images.githubusercontent.com/40713656/118379540-d921b280-b5e3-11eb-802c-9e63fa9ce91a.png)

**Comment by PatrickCampeol** [comment]
yes, same here, undistribute mined freezed for 07 hours at least.

**Comment by Ruslame** [comment]
> yes, same here, undistribute mined freezed for 07 hours at least.

That is, payments are credited after 7 hours?

**Comment by kursatjr** [comment]
Same here. Revenue page updates regularly and i see new block incomes but no change on undistributed mined balance for about 6-7 hours

**Comment by PatrickCampeol** [comment]
> Same here. Revenue page updates regularly and i see new block incomes but no change on undistributed mined balance for about 6-7 hours

Exact!!

**Comment by salvadordali1** [comment]
> Same here. Revenue page updates regularly and i see new block incomes but no change on undistributed mined balance for about 6-7 hours

same..

**Comment by Ruslame** [comment]
I do not understand why the administration will not fix it, because there are also downtime of equipment because of this money is lost...

**Comment by SinonCute** [comment]
same

**Comment by h9-dev** [comment]
The unsettled total is updated asynchronously, and the real-time data is subject to the income details.
