### ISSUE TITLE
connect fail

### ISSUE THREAD

**Issue by some27** [hpool-dev/chia-miner#32]
ain=CHIA file=loggers.go func=logging.CPrint line=168 tid=1 type=ws

ERRO[2021-04-22T20:11:32+08:00] connect fail                                  err="websocket: bad handshake" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,67}" f9="{server.go,websocket.NewServer,18}" tid=16 url="wss://chia-sh0.hpool.com/x-proxynode/ws"

**Comment by h9-dev** [comment]
Sometimes this happens when configuring the proxy server, please check the log later.
