### ISSUE TITLE
腾讯云cos（对象存储）挖矿算力问题

### ISSUE THREAD

**Issue by FreeBoys** [hpool-dev/chia-miner#328]
为什么我腾讯云cos（对象存储）有400TB文件，实际挖矿算力在线总算力只有 97.83 TB

**Comment by OodavidsinoO** [comment]
放弃用云服务挖吧...你网速不够快，扫盘时间超过5s，那三百多T被踢下线

**Comment by Tjianke** [comment]
> 为什么我腾讯云cos（对象存储）有400TB文件，实际挖矿算力在线总算力只有 97.83 TB

Did you manage to improve delay now?

**Comment by FreeBoys** [comment]
> > 为什么我腾讯云cos（对象存储）有400TB文件，实际挖矿算力在线总算力只有 97.83 TB
> 
> Did you manage to improve delay now?
>
>Yes, use cosfs provided by Tencent Cloud 
`cosfs chia-[*] /mnt/cos -ourl=http://cos.ap-beijing.myqcloud.com -onoxattr -oallow_other -omax_stat_cache_size=1000000 -oparallel_count=15 -omax_prefetch_bytes=0`

**Comment by FreeBoys** [comment]
> > 为什么我腾讯云cos（对象存储）有400TB文件，实际挖矿算力在线总算力只有 97.83 TB
> 
>>> Did you manage to improve delay now?
>>>> Yes, use cosfs provided by Tencent Cloud
>>>> `cosfs chia-[*] /mnt/cos -ourl=http://cos.ap-beijing.myqcloud.com -onoxattr -oallow_other -omax_stat_cache_size=1000000 -oparallel_count=15 -omax_prefetch_bytes=0`
