### ISSUE TITLE
账号封禁会变成什么样，账号封禁会没有收益吗？

### ISSUE THREAD

**Issue by JensonSuen** [hpool-dev/chia-miner#337]
我的账号从前天开始一直没有收益，有被封过账号的吗？账号被封是直接不能登录，还是不能提现

**Comment by fjh1997** [comment]
我是新用户，也没收益。

**Comment by BJ5129** [comment]
![image](https://user-images.githubusercontent.com/37569731/118392329-b935d180-b66b-11eb-9d5d-f64b1b6a1484.png)
唠嗑闲聊交流
