### ISSUE TITLE
linux 报错 Dynamic loading not supported

### ISSUE THREAD

**Issue by fgc0109** [hpool-dev/chia-miner#34]
Dynamic loading not supported
没有加载到文件,算力没有生效
操作系统是 linux mint 20 ,没有更多信息能提供

配置文件不知道怎么改成 debug 
debug : "" 
改成 ture 还是填什么字符串
还是 log level 可以改 debug 

现在连个说明文档也没有,配置文件也没个注释
全靠猜

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
