### ISSUE TITLE
程序显示new mining info ，后台在线矿机和离线矿机为空

### ISSUE THREAD

**Issue by flybiubiu** [hpool-dev/chia-miner#35]
<img width="1249" alt="Screen Shot 2021-04-23 at 11 36 39 AM" src="https://user-images.githubusercontent.com/20927755/115814708-2d43d780-a428-11eb-8480-bd6041daa180.png">
<img width="1173" alt="Screen Shot 2021-04-23 at 11 36 56 AM" src="https://user-images.githubusercontent.com/20927755/115814739-37fe6c80-a428-11eb-83e2-96671229e301.png">
好久了

**Comment by trying2016** [comment]
出现这种情况有2个可能：
1、没设置p好盘的路径，或者还没有p好的问题
2、apiKey可能填写错误，miner下面的config.yaml 中需要填写chia矿池的apiKey

**Comment by PresidentCake** [comment]
p好盘路径是外接移动硬盘是否可行？我设置好路径和填写好key后也是这种情况

**Comment by h9-dev** [comment]
> p好盘路径是外接移动硬盘是否可行？我设置好路径和填写好key后也是这种情况

可以的，过程中占用的带宽比较小。

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
