### ISSUE TITLE
 1.3.0 (build 3) . "Online miner" counter stuck and decreas space.  After 420 plots

### ISSUE THREAD

**Issue by Magby123** [hpool-dev/chia-miner#355]
I have joined with 460+ plots , miner ( win 64)  get all plots and count corectly.   But  in couple hours  i notice that space DECREASE  ( looks like each autorefresh 10 min  and load new files automatically).  So after 420 plots in  4 hours  i just stuck on 426 plots ( in online counter wth  4 plots offline. And total space in miner decreases from total 46TB ( 460 plots) to  42TB ( about 420 plots)
    Looks like glitch...
<img width="960" alt="Glitch1" src="https://user-images.githubusercontent.com/78310118/118413147-79d8a680-b6a6-11eb-8ff8-6872ea19427b.png">

**Comment by 95289527** [comment]
我也遇见了同样的问题 文件明明好好的 就显示掉线的 同目录其他文件没有掉线

![image](https://user-images.githubusercontent.com/12559853/118414933-018bd880-b6da-11eb-8121-e430e29e4690.png)
![image](https://user-images.githubusercontent.com/12559853/118414941-17010280-b6da-11eb-93e0-544e1833abb1.png)

**Comment by nqzhang** [comment]
![Uploading image.png…]()

**Comment by reverside85** [comment]
我这里也是一样的问题 。。。。。 昨天开始就是离线

**Comment by Magby123** [comment]
The solution was founded - IT WAS ERROR in plots quality. So miner just recount total space for actual plots after check.
