### ISSUE TITLE
跑的正常， 一会儿就   1.03-4 Panic 请看看

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#368]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x73bf4e]

goroutine 151 [running]:
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetFilename(...)
        miner/chain/chia/common/chiapos/chia.go:196
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).hasFile(0xc00044e000, 0xc000a3d3b0, 0x68, 0x0)
        miner/chain/chia/plotterSpace.go:462 +0x8e
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc00044e000, 0xc0000db218, 0x8, 0x1)
        miner/chain/chia/plotterSpace.go:196 +0x1e5
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:63 +0x253

**Comment by h9-dev** [comment]
1.3.0.5 对一些可能的不稳定做了修正，请尝试一下。
