### ISSUE TITLE
这个有关系吗？

### ISSUE THREAD

**Issue by reverside85** [hpool-dev/chia-miner#370]
time="2021-05-17T11:17:19+09:00" level=info msg="new mining info" capacity="6.93 TB" file=loggers.go func=logging.CPrint height=292613 jobId=2026152555 line=168 scan consume=218 scan time="2021-05-17 11:17:12" tid=1203
time="2021-05-17T11:17:27+09:00" level=info msg="new mining info" capacity="6.93 TB" file=loggers.go func=logging.CPrint height=292615 jobId=2547948878 line=168 scan consume=257 scan time="2021-05-17 11:17:19" tid=1203
time="2021-05-17T11:17:36+09:00" level=info msg="new mining info" capacity="6.93 TB" file=loggers.go func=logging.CPrint height=292615 jobId=3868378197 line=168 scan consume=257 scan time="2021-05-17 11:17:36" tid=1203
time="2021-05-17T11:17:47+09:00" level=info msg="new mining info" capacity="6.93 TB" file=loggers.go func=logging.CPrint height=292615 jobId=3190703794 line=168 scan consume=257 scan time="2021-05-17 11:17:47" tid=1203
time="2021-05-17T11:17:48+09:00" level=info msg="switch line" chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=57 type=ws url="wss://chia-hb2.hpool.com/x-proxynode/ws"
time="2021-05-17T11:17:48+09:00" level=info msg="init server" f7="{loggers.go,logging.CPrint,168}" f8="{server.go,server.(*Server).initServer,128}" f9="{server.go,server.(*Server).updateLine,116}" tid=61 type=ws url="wss://chia-hb2.hpool.com/x-proxynode/ws"
time="2021-05-17T11:17:48+09:00" level=error msg="read message fail" error="read tcp 192.168.0.7:4357->39.101.132.210:9033: use of closed network connection" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect.func1,108}" f9="{asm_amd64.s,runtime.goexit,1371}" tid=1203
time="2021-05-17T11:17:48+09:00" level=info msg="connect success" file=loggers.go func=logging.CPrint line=168 tid=61 url="wss://chia-hb2.hpool.com/x-proxynode/ws"
time="2021-05-17T11:18:28+09:00" level=info msg="upload status" file=loggers.go func=logging.CPrint interval=180 line=168 pre upload time="2021-05-17 11:15:28" tid=1239
time="2021-05-17T11:18:44+09:00" level=error msg="read message fail" error="websocket: close 1006 (abnormal closure): unexpected EOF" f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect.func1,108}" f9="{asm_amd64.s,runtime.goexit,1371}" tid=1252
time="2021-05-17T11:18:46+09:00" level=info msg="connect success" file=loggers.go func=logging.CPrint line=168 tid=1253 url="wss://chia-hb2.hpool.com/x-proxynode/ws"

**Comment by h9-dev** [comment]
看起来没什么问题。
