### ISSUE TITLE
試了兩小時，後台顯示已連線，但在線算力全部都當是離線，貢獻點也看不到

### ISSUE THREAD

**Issue by chiagod77** [hpool-dev/chia-miner#371]
已試過 1.3.0 build 4 / build 3
1.2.0 build 5 同樣效果
全部算力都是離線，昨天23:29 前也還有收益，是什麼問題嗎?
![image](https://user-images.githubusercontent.com/84200636/118428573-52172c00-b702-11eb-8b61-6ba474085fc5.png)
![image](https://user-images.githubusercontent.com/84200636/118428603-62c7a200-b702-11eb-807f-816ee6c05769.png)
![image](https://user-images.githubusercontent.com/84200636/118428617-6d823700-b702-11eb-904b-290e54d33ca4.png)
![image](https://user-images.githubusercontent.com/84200636/118428668-8b4f9c00-b702-11eb-9a55-ac0c2f9c670d.png)

**Comment by herotm** [comment]
同一个问题， 没人回复

**Comment by h9-dev** [comment]
请查看 #375

**Comment by chiagod77** [comment]
12:00運行
14:30看到文件已簽名
15:30看到貢獻點
15:40未有任何payout
會再觀察

**Comment by chiagod77** [comment]
15:31 第一條payout記錄
12:00至15:00的我想是沒有了
