### ISSUE TITLE
为什么linnx软件已经开始跑了。但是web页面的在线矿机没有linnx的机器？

### ISSUE THREAD

**Issue by betterpi** [hpool-dev/chia-miner#383]
![image](https://user-images.githubusercontent.com/30262839/118459457-59ecc580-b72e-11eb-8829-97cb5153ef02.png)

**Comment by mikewubox** [comment]
客户端上线与服务端认可上线貌似有延时，多久那要问一下客服。，等官方矿池出来

**Comment by trying2016** [comment]
扫盘目录没设置
