### ISSUE TITLE
收益明细正常。待结算收益已经几个小时没变化了。

### ISSUE THREAD

**Issue by tiancaiyanyan** [hpool-dev/chia-miner#385]
如题。待结算收益不正常显示了。

**Comment by 34010493** [comment]
+1

**Comment by tiancaiyanyan** [comment]
14:30+8程序闪退过一次。15:00左右收到提醒，再上线之后，待结算收益就不增加了。看了收益明细正常。其他也都正常。希望超管能看一眼什么情况。而且最近几天软件老闪退。从我后台应该能看出来。tiancaiyanyan@gmail.com

**Comment by NicNem55** [comment]
+1
