### ISSUE TITLE
莫名奇妙的离线

### ISSUE THREAD

**Issue by 75557032** [hpool-dev/chia-miner#400]
早上5点报告矿机离线，结果发现矿机还在接任务，正常运行
![微信图片_20210518101733](https://user-images.githubusercontent.com/3348125/118580348-5014a200-b7c2-11eb-80a5-db60fe1edb4d.jpg)
![微信图片_20210518101748](https://user-images.githubusercontent.com/3348125/118580559-ae418500-b7c2-11eb-8bda-c23ec01de6cd.jpg)

**Comment by trying2016** [comment]
需要升级到1.3.0-5版本
https://github.com/hpool-dev/chia-miner/releases
