### ISSUE TITLE
1.3.0-5 有贡献点问题， 麻烦官方检查下

### ISSUE THREAD

**Issue by herotm** [hpool-dev/chia-miner#402]
昨晚半夜晚上跑了一会儿后后面就没有贡献点了 一个晚上 损失了很多

在线矿机算力 显示正常， 贡献点跟签名完全是不存在。

1. 本机Linux
2. 算力 -> 100TB
3. 文件肯定没有重复挖 有cron查重复文件 没有任何重复的plot， 今天早上起来换1.30-4 贡献点跟签名又正常了

**Comment by Zweelee** [comment]
贡献点怎样计算的？我的算力是9t，贡献点是9000吗？

**Comment by herotm** [comment]
1.3.0-4 碰到宕机 马上软件自动重启的时候会出现这个情况。。

exception : Invalid file /data/4/plot-k32-2021-04-13-28-07-64849d912da82c2e85c3378e324f82a30e8ef718d26851cc7d8a046eaa79efb6.plot
exception : Invalid file /data/22/plot-k32-2021-05-03-07-13-5311144d729290fa30d52183a9414b414442bb908f8415047119ca82e7f7345b.plot
INFO[2021-05-17T22:58:58-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298371 jobId=1856299910 line=168 scan consume=373 scan time="2021-05-17 22:58:50" tid=284
exception : Invalid file /data/21/plot-k32-2021-05-00-07-08-36fe808857b5f7b2db6ed5d2f2d54d665625c5e43218f414e8b2fab28d055034.plot
exception : Invalid file /data/24/plot-k32-2021-04-08-22-05-653f9c234afb550fb5b8f0d44d592cab728a3d98c694754d75d0ead33cc898a3.plot
exception : Invalid file /data/29/plot-k32-2021-04-21-30-18-a4170434d480de76bfbcc8752f9b7f24960e3d5d148f7c1bbe4fddd99dc29c8b.plot
exception : Invalid file /data/32/plot-k32-2021-05-12-03-45-24ab50b271b7c5f5437fb95e0f466a7217c3e33c696212e4293a741f7d9db4b1.plot
INFO[2021-05-17T22:59:10-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298371 jobId=3128194989 line=168 scan consume=373 scan time="2021-05-17 22:58:58" tid=284
exception : Invalid file /data/10/plot-k32-2021-05-02-05-50-f3722633bdcfb313f723122814b7d4042bbff703b63be9148697a293a5d9b84c.plot
exception : Invalid file /data/21/plot-k32-2021-04-06-30-18-57a947548ada74e641fabb6e348c51e0236b99d089887f9fecd346df7d48ce1c.plot
INFO[2021-05-17T22:59:18-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298374 jobId=694710829 line=168 scan consume=373 scan time="2021-05-17 22:59:10" tid=284
exception : Invalid file /data/30/plot-k32-2021-05-09-03-55-6c780a1bde59f256bce2ed4bbe642312ab7565dec5efc70daa9bf89172d75c89.plot
exception : Invalid file /data/29/plot-k32-2021-05-06-10-42-a18588086e93e928b4dda67115f0500d6b9e294b421e022b1e29907bf9b22f26.plotexception : Invalid file /data/4/plot-k32-2021-04-06-29-36-bdc9e793b8905f0aaf34900e7f63290075cd79da3116579dae9d0cd069f00dee.plot

INFO[2021-05-17T22:59:26-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298374 jobId=1813138686 line=168 scan consume=373 scan time="2021-05-17 22:59:18" tid=284
exception : Invalid file /data/26/plot-k32-2021-05-09-11-47-ee19707433cac67d11b852f78fa9ec9980c7dd3efd3fa494983c49f993eb5954.plot
INFO[2021-05-17T22:59:34-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298375 jobId=2373800078 line=168 scan consume=373 scan time="2021-05-17 22:59:26" tid=284
exception : Invalid file /data/23/plot-k32-2021-05-04-02-00-e71386a54c429de221850aae5abeb76b58574441d3de6753e2f5effd208e9055.plot
exception : Invalid file /data/27/plot-k32-2021-05-09-11-30-f2e83f6c9e7b465cf5b5e28c8fe1ead849c3929fce4e0e00daf42209d334fa53.plot
INFO[2021-05-17T22:59:46-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298375 jobId=2197991109 line=168 scan consume=373 scan time="2021-05-17 22:59:34" tid=284
INFO[2021-05-17T22:59:50-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298377 jobId=3508154608 line=168 scan consume=373 scan time="2021-05-17 22:59:46" tid=284
exception : Invalid file /data/11/plot-k32-2021-04-01-23-36-8927caefc2dd8fd4296c56a325be3d10fbbfb58191a4bdb28ab6d4597b425126.plot
exception : Invalid file /data/25/plot-k32-2021-05-11-05-54-022f98f0b0d4880ea3d86b6a32ba6d31a13b7086c2681ca27d5cb4a2041126fe.plot
INFO[2021-05-17T23:00:02-07:00] new mining info                               capacity="262.12 TB" file=loggers.go func=logging.CPrint height=298377 jobId=840681925 line=168 scan consume=373 scan time="2021-05-17 22:59:50" tid=284
exception : Invalid file /data/29/plot-k32-2021-05-10-02-47-3988e71a1fb00d26459eaf594398c1c0b48aa952923df447d5ae557dc0861d0d.plot
exception : Invalid file /data/31/plot-k32-2021-05-02-18-51-c72d74a7e86fb4edfa04756c22dbbe525fec35903ba80e08765c0fea2475fa91.plot
exception : Invalid file /data/5/plot-k32-2021-05-07-01-21-cbf066cc89444a930f76742483ddbdef5ff27d796717f5cbe1f9dfe2ffb7d33f.plot
exception : Invalid file /data/19/plot-k32-2021-05-12-09-01-509f5df63b19916a0b074e07f1cfd0a3d01eeca5f5e6b11bb729a123d3106d18.plot
exception : Invalid file /data/4/plot-k32-2021-05-10-01-56-39e06bcb044fcdc1a120e940a71d2899620344f9565d006a6ca6fca311814b58.plot
exception : Invalid file /data/4/plot-k32-2021-04-04-29-08-192e12b42e0b082825f85a4b124755e1d50ed61a526d9fbf3e89a77e5f280ea6.plot


@trying2016 @hpool-dev

**Comment by jpouza** [comment]
Same here, pool killed my main contribuitor rig 1h ago and miner is online, everything OK, also revenue is abismal low due to this fact, I think pool is stealing from us somehow.

There is no reasonable explanation, since devs do not respond to nothing and delete/close topics...I"m going back to SOLO mining and wait for official pooling protocol, this one is stealing my money for a while, enough of this joke.
