### ISSUE TITLE
Creating New Plots

### ISSUE THREAD

**Issue by jedocampo** [hpool-dev/chia-miner#407]
I just moved my plots to Hpool and close my Chia GUI. My next step is how do i create new plots? do i create plots on the chia gui and just removed my my finished plots on the directory so it doesn't farm them? sorry if this question been asked before its just so hard to navigate in here with the language. if there is a "how to" on this subject i appreciate the link.

**Comment by Kayuii** [comment]
for sign
```sh
docker run -it --rm \
  kayuii/chia-plotter:v0.11 chia-plotter-linux-amd64 \
  -action sign -sign-mnemonic "24 mnemonics"
plotter
```
save fpk ppk signature

for plot
```sh
docker run -itd --rm --name plot00 \
  -v "/mnt/tmp/00:/mnt/tmp" \
  -v "/mnt/dst/00:/mnt/plot" \
  -v "/opt/chialogs:/mnt/logs" \
  kayuii/chia-plotter:v0.11 bash -c "sleep 30m && chia-plotter-linux-amd64 -action plotting \
  -plotting-fpk '0x9480...66c87b7' \
  -plotting-ppk '0x96d4d7...fff952f709' \
  -plotting-n 1 -r 2 -b 3390 -e -p -d /mnt/plot -t /mnt/tmp |tee /mnt/logs/chia_00.log"
```

The signature is bound to the pool of hpool

**Comment by Huziyi** [comment]
1.remove the directory for farming of chia GUI.   
2.click the option of "Exclude final directory " when u plot with the chia GUI.

**Comment by jedocampo** [comment]
Thank you
