### ISSUE TITLE
能帮忙编译一个linux 下arm64版本运行文件吗？

### ISSUE THREAD

**Issue by tanxjian** [hpool-dev/chia-miner#41]

**Comment by sf2046** [comment]
同求

**Comment by rmokerone** [comment]
需要一个树莓派4B上能运行

**Comment by swiftczz** [comment]
需要+1，很需要一个ARM版本的可执行文件，手里没有x86电脑，现在ARM已经很普遍了，麻烦编译一个ARM的可执行文件吧

**Comment by h9-dev** [comment]
下一个版本会支持 ARM.

**Comment by yiday** [comment]
> 下一个版本会支持 ARM.

赞，大概会在什么时候支持？真的很期待

**Comment by nuistzj2014** [comment]
> 下一个版本会支持 ARM.

先把AMD64支持好再说吧，经常进程莫名就没了，掉线收益不算，重新启动还要再扫一遍plot文件，浪费时间

**Comment by ychost** [comment]
需要+1，手上的树莓派就等着挖矿了

**Comment by betterA** [comment]
需要+1，很需要一个ARM版本的可执行文件

**Comment by GameOSX** [comment]
Same here - can't wait to run my farm from little pi ;)

**Comment by Sinowrt** [comment]
用qemu可以在树莓派上面运行hpool-miner-chia，效率如何就不清楚了，参考[这篇博文](https://blog.sinowrt.cn/2021/2021-04-23t1847-how-to-run-chia-miner-of-hpool-on-raspberry-pi4/)

**Comment by songshuailin** [comment]
需要+1，很需要一个ARM版本的可执行文件

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
