### ISSUE TITLE
solo p过文件，如何加入矿池，难道要重p，反过来呢？矿池回归solo怎么搞？

### ISSUE THREAD

**Issue by phyerbarte** [hpool-dev/chia-miner#46]
找了好久就说是互相承认，那说明里面生成p文件的时候不是要指定钥匙？那意思我solo的时候P的好几十p都白p了？那从池子回到solo难道也要重p？不过用池子软件倒是能认出过去p的文件，也能在网站上确认矿机，这算是正常开动了？望解惑谢谢。

**Comment by qq253044370** [comment]
就怕回到solo，p出来的算力 还算到矿池。那就崩了。。我也想知道如何回到solo。

**Comment by roamerxv** [comment]
那就用官方的程序来 plot

**Comment by nuistzj2014** [comment]
> 就怕回到solo，p出来的算力 还算到矿池。那就崩了。。我也想知道如何回到solo。

你 solo以后，它都拿不到你的plot文件，怎么可能算矿池收益，矿池收益是绑定xch_address

**Comment by h9-dev** [comment]
> 就怕回到solo，p出来的算力 还算到矿池。那就崩了。。我也想知道如何回到solo。

多虑了。
