### ISSUE TITLE
why stop giving reward 7-8houirs lost !! what happen? im Online that time..

### ISSUE THREAD

**Issue by andy118z** [hpool-dev/chia-miner#463]
![image](https://user-images.githubusercontent.com/83979862/119230377-7d5ca980-bb4e-11eb-8263-c3527d69fc4e.png)

can help fix the BUG.. its not fair for us ONLINE and no reward

**Comment by andy118z** [comment]
please help !! 11:30am to 9PM !! nothing get... what happen?? 贡献点没有掉哦！全部都在线上 ！

**Comment by remiliacn** [comment]
Same here.

**Comment by andy118z** [comment]
> e here.

sad aiks.. keep ggot bug..

**Comment by toy23** [comment]
How much ploting?
