### ISSUE TITLE
Invalid Proof issue

### ISSUE THREAD

**Issue by Forsen-Baj** [hpool-dev/chia-miner#465]
![image](https://user-images.githubusercontent.com/81097023/119241545-e3056180-bb5f-11eb-8672-00ff496feb71.png)

Hi guys. I noticed that on my new disk this plot became invalid due to "Invalid Proof", however, when I checked it in official wallet, it's fine. What can be the reason for it and how to fix it? Thanks

**Comment by trying2016** [comment]
There is a problem with the file, you can re-plot
