### ISSUE TITLE
1.3.0.6 linux客户端不会自动扫描加入新的plot

### ISSUE THREAD

**Issue by westzhou666** [hpool-dev/chia-miner#466]
1.3.0.6 linux客户端不会自动扫描加入新的plot

**Comment by Neppumuck** [comment]
hi, in my case, he didn´t scan for plots. the miner does nothing, nothing in the logs:
time="2021-05-23T11:07:08+02:00" level=info msg="Logger Configuration." fields.level=info file=loggers.go func=logging.Init line=121 path=./log/

config:
path: /NAS
minerName: Linux253
apiKey: ********-****-****-****-************
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
scanPath: false
scanMinute: 60

what did i wrong ?

greetings

**Comment by haowang1013** [comment]
You need to set scanPath to true...

**Comment by westzhou666** [comment]
> You need to set scanPath to true...

of course  i  setted
![image](https://user-images.githubusercontent.com/83916204/119299379-62df1900-bc91-11eb-8bbe-4b09ef2bb8e0.png)
it  still not use

**Comment by westzhou666** [comment]
i know ,when you start the bash, it will create a new config file, you need  edit it ,  "scanPath: ture",thanks

**Comment by wishwanto** [comment]
perhaps it is because of the spelling mistake .. "scanPath: ture" should be "scanPath: **true**"

**Comment by BJ5129** [comment]
![image](https://user-images.githubusercontent.com/37569731/119445811-f3842a80-bd5f-11eb-83d2-e6f31e258719.png)
闲聊 扯谈 吐槽
