### ISSUE TITLE
chia pool dc? why cannot connect to SERVER Error?? someone help?

### ISSUE THREAD

**Issue by andy118z** [hpool-dev/chia-miner#469]
![image](https://user-images.githubusercontent.com/83979862/119261088-5662ae00-bc08-11eb-8e7b-94e4c735b962.png)

its never can connect... please help. !

**Comment by robsonds2** [comment]
I've the same issue, and all my plots are offline since 00:43, the revenue is stoped also, but the status of online miner it's ok.
