### ISSUE TITLE
chia miner no tasks!

### ISSUE THREAD

**Issue by zinovich2101** [hpool-dev/chia-miner#472]
From 09:37 CET 05.21.21, my miner was stopped and i have no task till now.

**Comment by zinovich2101** [comment]
![1](https://user-images.githubusercontent.com/84704338/119314146-1093fd00-bc7d-11eb-9626-5bf5c624a10a.png)

**Comment by brasrox** [comment]
hey dude, check if u have the build 6 version!

**Comment by zinovich2101** [comment]
Yep, I have 1.3.0-6 build and it doesnt work :(

**Comment by zinovich2101** [comment]
![2](https://user-images.githubusercontent.com/84704338/119394507-ecff9f80-bcda-11eb-8431-2d40197c5602.png)

**Comment by zinovich2101** [comment]
In logs i havent got mesages about mining info ( capasity, consume time etc.)
