### ISSUE TITLE
Can not see total plot

### ISSUE THREAD

**Issue by cexmad** [hpool-dev/chia-miner#474]
Hello,

I can not see total plot quantity under "miner-->online plot" section.
"miner-->online miner" section and hpool gui seems normal and total plot number shown exactly true.
I have 66 plot and online plot seems like 7. 
Has anyone faced such a problem like this?

Thanks for your helps.

**Comment by brasrox** [comment]
just like me i got only 25 of 249 plots i have  haha 

all fine in contribution too

but they add a new label note here

![image](https://user-images.githubusercontent.com/21345109/119391726-17366a80-bca5-11eb-8739-ec793740eea0.png)
