### ISSUE TITLE
When moving plotts to different folder gui does't recongize it ! 请帮忙 ！

### ISSUE THREAD

**Issue by aresstokrat** [hpool-dev/chia-miner#48]
What should i ? Its shows 0 plots in folder.
I sent reports to email a week ago - no answer!

in console .exe it shows this errors:

`time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-53-d6e106d20933ec9b2726c3a409610e906cb25eaa27948eff1ceb524a3b3ab8d3.plot" tid=1
An exception was caught in __except.1/Download3/plots (10/22) 45%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-53-e333c4106a7cfe6142e88f5b1121805a8f6ff9301b2ad3cc5fa01b90079c1e0f.plot" tid=1
An exception was caught in __except.1/Download3/plots (11/22) 50%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-55-21bae630199559f1bce2a4ebb3d13691f264a5e75f32d5fd59cf15c87f5b51b2.plot" tid=1
An exception was caught in __except.1/Download3/plots (12/22) 54%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-03-c9c0cc708b9796d80f763820377a97981d7c20c180865a522a3ef4af1fc81801.plot" tid=1
An exception was caught in __except.1/Download3/plots (13/22) 59%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-03-e9301f29320c46ae8f37e8892ae1f0e6e43d19af6a79df2afc5c173ac18c81ae.plot" tid=1
An exception was caught in __except.1/Download3/plots (14/22) 63%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-26-b26c888a96ccc9224720025f4fa20f33f605354be4843664b42d177eecee1da2.plot" tid=1
An exception was caught in __except.1/Download3/plots (15/22) 68%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-03-01-5002ec81901d9db099bf5228b198d8316d6080642c14c598aea59d5672ae0dca.plot" tid=1
An exception was caught in __except.1/Download3/plots (16/22) 72%
time="2021-04-26T05:28:11+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-03-01-b00563ad751cd4fbae88f44462e5d2c8b18dca1310190cee6a36168e77d71a11.plot" tid=1
time="2021-04-26T05:28:14+03:00" level=info msg="pool public key: a93b0499e3284f8bcfade97bba36f2e972acc296687496e8ff8630b3b431e4412b299236e10ab5003a2cf4f400fbb14a" file=loggers.go func=logging.CPrint line=168 tid=1`

**Comment by roamerxv** [comment]
The network file is not support 。

**Comment by aresstokrat** [comment]
> The network file is not support 。

but why? original chia miner support it without a problem!

**Comment by trying2016** [comment]
The v1.1.0 version has been fixed
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.0
