### ISSUE TITLE
启动程序显示Plot文件错误

### ISSUE THREAD

**Issue by 0xBayMax** [hpool-dev/chia-miner#482]
ERRO[2021-05-25T20:17:19+08:00] add plot file                                 error="invalid plot file format" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,242}" f9="{asm_arm64.s,runtime.goexit,1130}" file=/mnt/sdh2/plot-k32-2021-05-21-02-56-8f774bd52a9dfd07c6d284aa5f0b20ff41f6803b5d2fa41d3804cc400cf5540d.plot tid=57

**Comment by 75557032** [comment]
哥们是换了1.4.0-1版本出现的吗？

**Comment by 0xBayMax** [comment]
> 哥们是换了1.4.0-1版本出现的吗？

1.3.0，我用的树莓派+阵列，1.4.0还没有aarch64的版本

**Comment by 75557032** [comment]
我是换了1.4.0-1出现的，咱俩还不是一个问题

**Comment by 0xBayMax** [comment]
> 我是换了1.4.0-1出现的，咱俩还不是一个问题

那应该不是一个问题

**Comment by paranoiagu** [comment]
1.4.0-1 好垃圾。退回1.3.0了

**Comment by sky7282** [comment]
一样退回了1.3.0 有1/3文件失效

**Comment by trying2016** [comment]
#487
