### ISSUE TITLE
从1.3.0 升级到 1.4.0 有好多PLOT文件无效，换回1.3.0可以正常使用

### ISSUE THREAD

**Issue by sky7282** [hpool-dev/chia-miner#487]
多次尝试，都有这个问题存在，希望得到解决，谢谢。

**Comment by trying2016** [comment]
麻烦将1.4.0加载错误的日志文件发下

**Comment by sky7282** [comment]
本来我有76TB，现在加载了一半，就不加载了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] 从1.3.0 升级到 1.4.0 有好多PLOT文件无效，换回1.3.0可以正常使用 (#487)





 
麻烦将1.4.0加载错误的日志文件发下

**Comment by trying2016** [comment]
如果加载不动了，说明你磁盘读取卡住了，需要检查硬件

**Comment by 75557032** [comment]
@trying2016 我也遇到了，我可以提供我的日志文件
[miner.log-20210525-25.log](https://github.com/hpool-dev/chia-miner/files/6546233/miner.log-20210525-25.log)

**Comment by 75557032** [comment]
@trying2016 我昨天试了新版本后，全部是无效，赶紧退回了1.3.0-6版本，然后晚上又试验了一下钱包加载，钱包可以正确识别

**Comment by HailongZhu** [comment]
今天更新了1.4.1，linux客户端加载没问题，但是在线算力变成只有识别一半，且700+plots显示为一条。贡献点也随之下降。

**Comment by keprice** [comment]
我也是，我12盘服务器，只有第一个盘的文件是有效的，其他的也都是invalid plot file format

**Comment by sky7282** [comment]
@trying2016 换回1.3.0没有问题啊。不是硬盘问题，我MD3800F  RAID5 阵列，怎么可能会出问题。

**Comment by sky7282** [comment]
如果硬盘问题，肯定DELL MD3800F 磁盘柜会报警，并没有，换回。1.3.0 一下就同步好了，已经发了日志程序了。

**Comment by keprice** [comment]
> 
> 
> 如果硬盘问题，肯定DELL MD3800F 磁盘柜会报警，并没有，换回。1.3.0 一下就同步好了，已经发了日志程序了。

我就是说的1.4.0有问题啊，我之前用的1.3.0啥问题都没，加载也快

**Comment by trying2016** [comment]
如果出现大量或者是全部文件加载失败，可以升级到1.4.0-2版本，当前版本会将失败原因打印出来
使用1.4.0-2版本后，有疑问可以再发日志过来

https://github.com/hpool-dev/chia-miner/releases

**Comment by sky7282** [comment]
@trying2016 刚试过，问题依旧，没有得到改善，谢谢。

**Comment by trying2016** [comment]
发日志过来给你看看

**Comment by sky7282** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] 从1.3.0 升级到 1.4.0 有好多PLOT文件无效，换回1.3.0可以正常使用 (#487)





 
如果出现大量或者是全部文件加载失败，可以升级到1.4.0-2版本，当前版本会将失败原因打印出来
 使用1.4.0-2版本后，有疑问可以再发日志过来
 
https://github.com/hpool-dev/chia-miner/releases

**Comment by sky7282** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] 从1.3.0 升级到 1.4.0 有好多PLOT文件无效，换回1.3.0可以正常使用 (#487)





 
发日志过来给你看看

**Comment by 75557032** [comment]
@trying2016 你好，我昨天提供日志后，不知道为什么我的账号就被锁定了，提现也被拒绝了，请问是因为我使用钱包测试文件有效性导致的吗？如果是，能不能帮忙解锁一下，谢谢。账号是:2524153@163.com

**Comment by sky7282** [comment]
@

> 发日志过来给你看看

请问有没有查看，具体什么原因导至

**Comment by trying2016** [comment]
@sky7282 你并没有发日志过来

**Comment by sky7282** [comment]
我发了邮件呢。没有收到？

**Comment by sky7282** [comment]
@trying2016 已经发了邮件日志文件，查收一下。看看有没有收到，谢谢。

**Comment by trying2016** [comment]
你发的不是日志

**Comment by sky7282** [comment]
@trying2016 请问日志文件路径是在当前目录里的LOG还是，已经重发

**Comment by sky7282** [comment]
tid=127
time="2021-05-27T10:55:45+08:00" level=error msg="add plot file" error="wrong farmer public key" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}"

**Comment by sky7282** [comment]
tid=127
time="2021-05-27T10:55:42+08:00" level=error msg="add plot file" error="wrong farmer public key" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}"

**Comment by sky7282** [comment]
tid=127
time="2021-05-27T10:55:42+08:00" level=error msg="add plot file" error="wrong farmer public key" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}"

**Comment by sky7282** [comment]
tid=103
time="2021-05-27T10:54:58+08:00" level=info msg="new mining info" capacity="30.70 TB" file=loggers.go func=logging.CPrint height=342209 jobId=3437558683 line=168 scan consume=0 scan time="2021-05-27 10:54:45" tid=57
time="2021-05-27T10:54:58+08:00" level=error msg="add plot file" error="wrong farmer public key" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}"

**Comment by sky7282** [comment]
类似这样的错误 @trying2016

**Comment by trying2016** [comment]
@sky7282 你p盘出问题了，ppk和fpk用的是一个，这种是无效文件

**Comment by trying2016** [comment]
要全部重P

**Comment by sky7282** [comment]
我不知道你们那里出问题了，如果是这样的话，你1.3.0 版本没问题。那是不可能的呢。都是用的官方P的盘。怎么会呢，如果是这样的话，那应该全不能用。

**Comment by sky7282** [comment]
反正发了邮件给你了。日志你们分析一下吧，具体我们也不清楚。 @trying2016 不会让我们重新P新文件吧。P是小事。

**Comment by trying2016** [comment]
日志上来看，你p的文件确实有问题。如果你认为文件没问题，可以SOLO

**Comment by sky7282** [comment]
@trying2016 我查看了那些文件的日期，都是早期用官网软件P的盘，现在你们这个官网P的都不能用了？

**Comment by sky7282** [comment]
早期用的是软件自带的功能P的盘。后面用的命令行，不知道你们这个软件是不是早期关于这些文件换效。

**Comment by sky7282** [comment]
@trying2016 我查看了一下，分析了一下，你的1.3.0 版本的可以读出 Pubkey 你的1.4.0版本一部分早期用chia 软件P的盘。读不出pubkey 导至加载不了。应该不是我一个人有这样的问题。明明你的1.3.0 读出来的pubkey 读出来的我核实了。ppk和fpk不是一样来的

**Comment by trying2016** [comment]
1.4.0版本加强了文件内容相关检测，没通过的就是有问题。

**Comment by sky7282** [comment]
好吧。反正就一天的时间重P这些有问题就行了。
