### ISSUE TITLE
1.4.0-2 在线算力和贡献点以及挖矿软件上显示的算力不匹配

### ISSUE THREAD

**Issue by jingchengdeng** [hpool-dev/chia-miner#492]
**首先挖矿软件上显示22.78T算力：**
![微信截图_20210526130158](https://user-images.githubusercontent.com/23201193/119702229-378c3380-be23-11eb-8868-95dafc59db44.png)

**在线矿机以及贡献点也同样证明22.78T算力：**
![微信截图_20210526130419](https://user-images.githubusercontent.com/23201193/119702313-538fd500-be23-11eb-8286-56801836c260.png)
![微信截图_20210526130454](https://user-images.githubusercontent.com/23201193/119702328-568ac580-be23-11eb-8cd1-5c20ae20a8c3.png)

**但是在 在线算力 里面 显示的已签名文件只有22.25TB，文件为230个 少了10个**
![微信截图_20210526130430](https://user-images.githubusercontent.com/23201193/119702490-7de19280-be23-11eb-8c7d-bb2a4b012a9e.png)

**所以收益计算到底以哪个为准？造成这种情况的原因是什么呢**

**Comment by trying2016** [comment]
以贡献点为准
