### ISSUE TITLE
Linux云存储1.4.0.2开多个挖矿软件只识别出一个的状态

### ISSUE THREAD

**Issue by exqmjmz** [hpool-dev/chia-miner#493]
1.4.0.2云存储挖矿，按照官网的QA开多个挖矿软件，在官网上看到的算力只有单个软件的算力。
如：
每个软件接入2T，多开5个，总算力10T，但是官网只显示2T的算力

**Comment by trying2016** [comment]
需要看扫盘是不是超时

**Comment by trying2016** [comment]
另外MinerName不能相同。
