### ISSUE TITLE
掉算力問題（1.4.0-2）

### ISSUE THREAD

**Issue by overdoignism** [hpool-dev/chia-miner#498]
目前會發生一個現象就是，miner統計的算力，過一段時間會掉
但GUI沒有發生任何報錯或是警告，不知道是檔案損壞或掃盤超時。

這問題從1.2.X以來就一直存在。附上該相關部分log

time="2021-05-27T08:11:12+08:00" level=info msg="new mining info" capacity="5.05 TB" file=loggers.go func=logging.CPrint height=341673 jobId=1152939967 line=168 scan consume=4431 scan time="2021-05-27 08:11:04" tid=15878
在這之前都是5.05TB

time="2021-05-27T08:11:14+08:00" level=warning msg="prove invalid" file=loggers.go func=logging.CPrint line=162 tid=12
這行之後就變4.95TB

time="2021-05-27T08:11:24+08:00" level=info msg="new mining info" capacity="4.95 TB" file=loggers.go func=logging.CPrint height=341673 jobId=2346191703 line=168 scan consume=4431 scan time="2021-05-27 08:11:12" tid=15878

如果是檔案有損壞，能否在下一個版本指出是哪一個檔案？

**Comment by trying2016** [comment]
GUI版本中，点击文件路径，选择plot文件，文件列表中，可以看到无效文件
