### ISSUE TITLE
the process is always gone

### ISSUE THREAD

**Issue by nuistzj2014** [hpool-dev/chia-miner#50]
OS is ubuntu20.0.4, twice a day !  What a fucking software!
Is it difficult to fix it?

**Comment by trying2016** [comment]
The v1.1.0 version has been fixed.
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.0

**Comment by PPGOli** [comment]
Beware there is no source code deposit behind this project. It might be a complete scam.
