### ISSUE TITLE
Unbind from google authenticator

### ISSUE THREAD

**Issue by rufless** [hpool-dev/chia-miner#501]
How could I unbind my account from google authenticator if I have access to sms and email? My google authenticator app was broken. I sent message to hpoolverification@163.com but didn't get answer. My login is grufless@gmail.com

**Comment by rufless** [comment]
Could you give me an answer?
@trying2016 @hpool-dev

**Comment by tokenhoki** [comment]
i have problem too before, dont scan , but copy thats code. time clock must sync with hpool

**Comment by rufless** [comment]
> i have problem too before, dont scan , but copy thats code. time clock must sync with hpool

My google app doesn't work and I can't use it. Because of it I need to unbind my account from it.

**Comment by lazadoor** [comment]
is your problem solved?

**Comment by rufless** [comment]
> is your problem solved?

No, I didn't receive any answer from support...

**Comment by gizd32** [comment]
I have the same problem, still no answer from hpool. Please let me know if You solved it.

**Comment by gizd32** [comment]
Worked fine for me, somebody from support unbinded my google account and i had to bind again.

**Comment by rufless** [comment]
Yes, also today somebody unbinded my account from google, Problem was solved!

**Comment by WhiteSide111** [comment]
Same isue for my acc: smart97rus@yandex.ru, can't unbind and support is not answering...
