### ISSUE TITLE
无法运行Hpool在Linux中  Error: terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by AndyX-Net** [hpool-dev/chia-miner#51]
Run app "Hpool-Miner-Chia v1.0.5" in ubuntu environment.

**The detailed OS information as following:**
-----------------------------------
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
-----------------------------------

**The detailed dump message as following:**
-----------------------------------
terminate called after throwing an instance of 'char const*'
SIGABRT: abort
PC=0xae6ecd m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0xae6ecd
stack: frame={sp:0x7fff5f6af3d8, fp:0x0} stack=[0x7fff5f69cc48,0x7fff5f6bbc80)
00007fff5f6af2d8:  0000000000000000  00007fff5f6bbc10
00007fff5f6af2e8:  0000000000472c50 <runtime.asmcgocall+112>  0000000000000000
00007fff5f6af2f8:  0000000000000000  0000000000000000
00007fff5f6af308:  00000000009977b0  4000000000000000
00007fff5f6af318:  0000000000000000  0000000000000000
00007fff5f6af328:  0000000000000000  0000000000000000
00007fff5f6af338:  0000000000000000  0000000000000000
00007fff5f6af348:  0000000000000000  0000000000000000
00007fff5f6af358:  0000000000000000  0000000000000000
00007fff5f6af368:  0000000000000000  0000000000000000
00007fff5f6af378:  0000000000000000  0000000000000000
00007fff5f6af388:  0000000000000000  0000000000000000
00007fff5f6af398:  0000000000000000  000000000000000b
00007fff5f6af3a8:  000000000000002a  0000000000a6dd80
00007fff5f6af3b8:  00007fff5f6af460  0000000000000000
00007fff5f6af3c8:  0000000000000000  0000000000000000
00007fff5f6af3d8: <0000000000ae6f07  0000000000000000
00007fff5f6af3e8:  0000000000000000  000000000292a700
00007fff5f6af3f8:  000000000000000b  00007fff5f6af150
00007fff5f6af408:  0000000000ae7a52  00000000016f3c48
00007fff5f6af418:  0000000000000000  0000000000d440a4
00007fff5f6af428:  0000000000000002  0000000000000001
00007fff5f6af438:  0000000000000001  0000000000d440a4
00007fff5f6af448:  0000000000000002  00000000012bfac0
00007fff5f6af458:  000000000292bbe0  0000000002997b90
00007fff5f6af468:  0000000000ae0ee6  00000000012bfac0
00007fff5f6af478:  000000000292a700  0000000000000000
00007fff5f6af488:  0000000000002710  000000000292bbe0
00007fff5f6af498:  00000000009c6fd9  0000000002997b90
00007fff5f6af4a8:  0000000000404ac1  0000000000000000
00007fff5f6af4b8:  0000000000000000  000000000292bbe0
00007fff5f6af4c8:  00000000012a4d20  0000000000000000
runtime: unknown pc 0xae6ecd
stack: frame={sp:0x7fff5f6af3d8, fp:0x0} stack=[0x7fff5f69cc48,0x7fff5f6bbc80)
00007fff5f6af2d8:  0000000000000000  00007fff5f6bbc10
00007fff5f6af2e8:  0000000000472c50 <runtime.asmcgocall+112>  0000000000000000
00007fff5f6af2f8:  0000000000000000  0000000000000000
00007fff5f6af308:  00000000009977b0  4000000000000000
00007fff5f6af318:  0000000000000000  0000000000000000
00007fff5f6af328:  0000000000000000  0000000000000000
00007fff5f6af338:  0000000000000000  0000000000000000
00007fff5f6af348:  0000000000000000  0000000000000000
00007fff5f6af358:  0000000000000000  0000000000000000
00007fff5f6af368:  0000000000000000  0000000000000000
00007fff5f6af378:  0000000000000000  0000000000000000
00007fff5f6af388:  0000000000000000  0000000000000000
00007fff5f6af398:  0000000000000000  000000000000000b
00007fff5f6af3a8:  000000000000002a  0000000000a6dd80
00007fff5f6af3b8:  00007fff5f6af460  0000000000000000
00007fff5f6af3c8:  0000000000000000  0000000000000000
00007fff5f6af3d8: <0000000000ae6f07  0000000000000000
00007fff5f6af3e8:  0000000000000000  000000000292a700
00007fff5f6af3f8:  000000000000000b  00007fff5f6af150
00007fff5f6af408:  0000000000ae7a52  00000000016f3c48
00007fff5f6af418:  0000000000000000  0000000000d440a4
00007fff5f6af428:  0000000000000002  0000000000000001
00007fff5f6af438:  0000000000000001  0000000000d440a4
00007fff5f6af448:  0000000000000002  00000000012bfac0
00007fff5f6af458:  000000000292bbe0  0000000002997b90
00007fff5f6af468:  0000000000ae0ee6  00000000012bfac0
00007fff5f6af478:  000000000292a700  0000000000000000
00007fff5f6af488:  0000000000002710  000000000292bbe0
00007fff5f6af498:  00000000009c6fd9  0000000002997b90
00007fff5f6af4a8:  0000000000404ac1  0000000000000000
00007fff5f6af4b8:  0000000000000000  000000000292bbe0
00007fff5f6af4c8:  00000000012a4d20  0000000000000000

goroutine 1 [syscall]:
runtime.cgocall(0x9977b0, 0xc0000c7490, 0x447400)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000c7460 sp=0xc0000c7428 pc=0x40a3fb
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Cfunc_GetQualitiesForChallenge(0x292a640, 0xc000295300, 0xc000604f00, 0x0)
        /var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build1199295552/b147/_cgo_gotypes.go:136 +0x49 fp=0xc0000c7490 sp=0xc0000c7460 pc=0x7901a9
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetQualitiesForChallenge.func1(0xc000386a40, 0xc000295300, 0x20, 0x40, 0xc000604f00, 0xc0000c7500)
        miner/chain/chia/common/chiapos/chia.go:197 +0x7f fp=0xc0000c74c8 sp=0xc0000c7490 pc=0x7917bf
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetQualitiesForChallenge(0xc000386a40, 0xc000295300, 0x20, 0x40, 0x0, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:197 +0x105 fp=0xc0000c7568 sp=0xc0000c74c8 pc=0x790ec5
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc0005cb7a0, 0x6f, 0xc0005cb7a0, 0x6f, 0x16f65a0)
        miner/chain/chia/common/chiapos/chia.go:78 +0x15a fp=0xc0000c75e0 sp=0xc0000c7568 pc=0x7905ba
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc0000763c0, 0xc000302c40, 0x10)
        miner/chain/chia/plotterSpace.go:99 +0x145 fp=0xc0000c7870 sp=0xc0000c75e0 pc=0x974d25
hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace(0xc000302c40, 0x10, 0xc0003f1950, 0x10b863199a)
        miner/chain/chia/plotterSpace.go:59 +0x1cf fp=0xc0000c78c0 sp=0xc0000c7870 pc=0x97484f
hpool.com/dev/miner-client/miner/chain/chia.(*Miner).AddPath(0xc000464960, 0xc000302c40, 0x10, 0x16f4bd8, 0xc3ccd9)
        miner/chain/chia/miner.go:164 +0x47 fp=0xc0000c7918 sp=0xc0000c78c0 pc=0x970fc7
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0xc00017cd80, 0x3, 0x0)
        miner/wrapper_miner.go:78 +0x190 fp=0xc0000c7c30 sp=0xc0000c7918 pc=0x9944d0
hpool.com/dev/miner-client/platform.Run(0xc00028ff50, 0xc00008a2a0, 0xd26c38, 0xc00017cd80)
        platform/console.go:53 +0x628 fp=0xc0000c7ed0 sp=0xc0000c7c30 pc=0x97a4e8
main.main()
        main.go:83 +0x3de fp=0xc0000c7f88 sp=0xc0000c7ed0 pc=0x99705e
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000c7fe0 sp=0xc0000c7f88 pc=0x43f6f6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000c7fe8 sp=0xc0000c7fe0 pc=0x472fe1

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x7fc177dfdeb8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000c2a18, 0x72, 0xf00, 0xf5c, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000c2a00, 0xc00038d000, 0xf5c, 0xf5c, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000c2a00, 0xc00038d000, 0xf5c, 0xf5c, 0xf57, 0xc0002aefa0, 0xd)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010fc0, 0xc00038d000, 0xf5c, 0xf5c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc000602fc0, 0xc00038d000, 0xf5c, 0xf5c, 0xc0000639f8, 0x1311920, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0002af078, 0xd15600, 0xc000602fc0, 0x412285, 0xb83dc0, 0xc18040)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0002aee00, 0xd166c0, 0xc000010fc0, 0x5, 0xc000010fc0, 0x40)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0002aee00, 0x0, 0x0, 0x43fbdc)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0002aee00, 0xc00038c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
net/http.(*persistConn).Read(0xc000316b40, 0xc00038c000, 0x1000, 0x1000, 0xc0001a3b60, 0xc000063d40, 0x40c335)
        /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0001afec0)
        /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0001afec0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
        /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc000316b40)
        /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 16 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc0003f1950)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc000316b40)
        /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0xc9c

goroutine 18 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc0003eee80, 0xc000010030)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 19 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc0003f1980)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 20 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc0003f19e0)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 21 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0xc0003eeeb0, 0xc000010038)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

rax    0x0
rbx    0x0
rcx    0xae6ecd
rdx    0x0
rdi    0x2
rsi    0x7fff5f6af3e0
rbp    0xd4012c
rsp    0x7fff5f6af3d8
r8     0x292bc00
r9     0x7fff5f6aeeb0
r10    0x8
r11    0x246
r12    0x12bfac0
r13    0x292a700
r14    0x0
r15    0x2710
rip    0xae6ecd
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
-----------------------------------

**Request:**
Please help check why hpool can't run in the current OS environment. Thank you!

**Comment by rmokerone** [comment]
我也遇到过，原因未知，换成v1.0.4.1就行了

**Comment by AndyX-Net** [comment]
> 我也遇到过，原因未知，换成v1.0.4.1就行了

谢谢，我试一下。

**Comment by trying2016** [comment]
v1.1.0版本对这个问题进行了修复https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.0
