### ISSUE TITLE
ARM 版本 内存错误

### ISSUE THREAD

**Issue by 496238742** [hpool-dev/chia-miner#510]
GPU是四核ARM Mali450
1G内存
硬件是玩客云刷机ArmBian
启动是可以起来的,并且可以认出来p图文件
日志中出现一次capacity='101GB' 的日志
但是第二次出现这个日志之后就会紧接着报错Segmentation fault

**Comment by trying2016** [comment]
内存不够会导致异常崩溃

**Comment by 496238742** [comment]
需要的最小内存是多少?





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] ARM 版本 内存错误 (#510)





 
内存不够会导致异常崩溃

**Comment by 496238742** [comment]
> 内存不够会导致异常崩溃

需要的最小内存是多少?
我的设备是1G内存应该够用吧
