### ISSUE TITLE
After 1h scan time goes up to 15.00s

### ISSUE THREAD

**Issue by Gokuref** [hpool-dev/chia-miner#512]
Hello guys!

I'm plotting and farming with a few pcs, but since the update, I'm facing these "Your scan time (15.00s) exceeds the maximum time limit (10.00s)".

Ok, I get that the scan time is way too high, but why is it happening? I mean, this farm is the only one facing this problem. It runs for a while, like 40m~1h, then I get these "time limit issue", and it only starts working again when I re-open hpool-miner-chia-console. 
Could it be because in this pc I'm using cloud storage? I have a 2Tb plan and I start uploading it there, I don't plan to use cloud cuz I bought a few HDD, but since most of HDD that I have are plotting, I decided to use cloud till they delivery my hardware. 

> time="2021-05-28T03:54:24-03:00" level=info msg="new mining info" capacity="608.40 GB" file=loggers.go func=logging.CPrint height=347743 jobId=824307839 line=168 scan consume=0 scan time="2021-05-28 03:54:24" tid=573
> time="2021-05-28T03:54:33-03:00" level=debug msg=scanner consume=0 file=loggers.go func=logging.CPrint line=174 tid=11
> time="2021-05-28T03:54:33-03:00" level=info msg="new mining info" capacity="608.40 GB" file=loggers.go func=logging.CPrint height=347743 jobId=3393208188 line=168 scan consume=0 scan time="2021-05-28 03:54:33" tid=573
> time="2021-05-28T03:54:44-03:00" level=info msg="new mining info" capacity="608.40 GB" file=loggers.go func=logging.CPrint height=347743 jobId=2564856323 line=168 scan consume=0 scan time="2021-05-28 03:54:33" tid=573
> time="2021-05-28T03:54:49-03:00" level=info msg="new mining info" capacity="608.40 GB" file=loggers.go func=logging.CPrint height=347743 jobId=1482988563 line=168 scan consume=0 scan time="2021-05-28 03:54:33" tid=573
> time="2021-05-28T03:54:51-03:00" level=warning msg="scanner timeout" consume=10000 file=loggers.go func=logging.CPrint line=162 tid=11
> time="2021-05-28T03:54:51-03:00" level=debug msg=scanner consume=0 file=loggers.go func=logging.CPrint line=174 tid=11
> time="2021-05-28T03:54:57-03:00" level=error msg="Scan timeout" f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path="C:\\Users\\PC4\\Desktop\\open" scan limit=10000 scan time=15000 tid=573
> time="2021-05-28T03:54:57-03:00" level=debug msg=scanner consume=0 file=loggers.go func=logging.CPrint line=174 tid=11
> time="2021-05-28T03:54:57-03:00" level=info msg="new mining info" capacity="0 B" file=loggers.go func=logging.CPrint height=347743 jobId=3677420672 line=168 scan consume=15000 scan time="2021-05-28 03:54:57" tid=573
> time="2021-05-28T03:54:57-03:00" level=error msg="Your scan time (15.00s) exceeds the maximum time limit (10.00s)" f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,125}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=573
> time="2021-05-28T03:55:09-03:00" level=error msg="Scan timeout" f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path="C:\\Users\\PC4\\Desktop\\open" scan limit=10000 scan time=15000 tid=573
> time="2021-05-28T03:55:09-03:00" level=debug msg=scanner consume=1 file=loggers.go func=logging.CPrint line=174 tid=11
> time="2021-05-28T03:55:09-03:00" level=info msg="new mining info" capacity="0 B" file=loggers.go func=logging.CPrint height=347743 jobId=837946400 line=168 scan consume=15000 scan time="2021-05-28 03:55:09" tid=573
> time="2021-05-28T03:55:09-03:00" level=error msg="Your scan time (15.00s) exceeds the maximum time limit (10.00s)" f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,125}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=573
> time="2021-05-28T03:55:09-03:00" level=info msg="scan chia plot directory: C:\\Users\\PC4\\Desktop\\open" file=loggers.go func=logging.CPrint line=168 tid=37
> time="2021-05-28T03:55:17-03:00" level=error msg="Scan timeout" f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path="C:\\Users\\PC4\\Desktop\\open" scan limit=10000 scan time=15000 tid=573
> time="2021-05-28T03:55:17-03:00" level=debug msg=scanner consume=0 file=loggers.go func=logging.CPrint line=174 tid=11

Thanks!

**Comment by trying2016** [comment]
Using cloud storage will cause the scan time to exceed the limit. It is recommended to use a local HDD to store plot files

**Comment by Gokuref** [comment]
Fixed. It wasn't about the storage neither miner, it was the software I was using to mount the storage as drive.

**Comment by hxl9654** [comment]
@Gokuref could you please tell me which software did you use. and how to fix it?

**Comment by Gokuref** [comment]
Sup, mate! Sure!  I was using "odrive", which is a good software, but somehow it was causing my ping to get alot higher to the storage(130~300ms), and that was the real problem. I'm like 13ms from the storage, it's really close, and 13ms is not high enough to cause timeout, then I knew there was something wrong. Now I'm using ExpanDrive, which does the same thing as "odrive", but my ping is not getting higher, it still like 13~14ms to the storage, and that's how I fixed it.
I won't be using cloud for long because it's clearly a disadvantage comparing to who mine with HD in home, that's why I've bought more HDD's, but I can't stop the plotting, so I'm using the storage till the HDDs arrive.

**Comment by Gokuref** [comment]
@hxl9654 Sup, mate! Sure!  I was using "odrive", which is a good software, but somehow it was causing my ping to get alot higher to the storage(130 to 300ms), and that was the real problem. I'm like 13ms from the storage, it's really close, and 13ms is not high enough to cause timeout, then I knew there was something wrong. Now I'm using ExpanDrive, which does the same thing as "odrive", but my ping is not getting higher, it still like 13 to14ms to the storage, and that's how I fixed it.
I won't be using cloud for long because it's clearly a disadvantage comparing to who mine with HD in home, that's why I've bought more HDD's, but I can't stop the plotting, so I'm using the storage till the HDDs arrive.

**Comment by hxl9654** [comment]
> 
> 
> @hxl9654 Sup, mate! Sure! I was using "odrive", which is a good software, but somehow it was causing my ping to get alot higher to the storage(130 to 300ms), and that was the real problem. I'm like 13ms from the storage, it's really close, and 13ms is not high enough to cause timeout, then I knew there was something wrong. Now I'm using ExpanDrive, which does the same thing as "odrive", but my ping is not getting higher, it still like 13 to14ms to the storage, and that's how I fixed it.
> I won't be using cloud for long because it's clearly a disadvantage comparing to who mine with HD in home, that's why I've bought more HDD's, but I can't stop the plotting, so I'm using the storage till the HDDs arrive.

thx

**Comment by lakingsfan29** [comment]
I’m currently having this issue as well. I don’t believe I’m using any mounting software, but I could be wrong. I just plug the drive in and it automatically is found. Should I download expandrive? Thanks in advance.

**Comment by Gokuref** [comment]
@lakingsfan29 Let me see if I'm getting it right. You're having timeout without using cloud storage? 
If your drive is local, you were not suppose to get timeout, and if so, you probably are not using any software cuz it won't be needed.  ExpanDrive only have use if you actually are using a cloud storage, but the thing is; you need to be really close to your storage in order for it work without timeout.  My storage is in the next city, like 70km from here, the ping is really amazing and thats why I'm not getting the timeout anymore. If you live far from your storage, I'd not recommend using softwares to mount it, because you'd get timeout anyway.
But if you're getting timeout with local driver, then there's something really wrong. I couldn't tell you the exactly reason... Is there something different in the logs?

**Comment by Tjianke** [comment]
same situation here, it took several hours before timeout, I wonder why. @Gokuref Would you mind telling me how you find out the location of your cloud storage and test the connection speed of storage?

**Comment by lakingsfan29** [comment]
@Gokuref I’m using a local external HDD drive which is why this doesn’t make any sense. Not sure where to go from here. It’s 10TB and almost full. There are 6 invalid plots on the drive, but I put them in a different folder and made sure they were not included in the directory I directed hpool to. Can the invalid plots have something to do with this?

**Comment by Gokuref** [comment]
@Tjianke I've send a support message asking where was the datacenter based. In my case, it's in Phoenix, AZ.
I've checked my connection using trace route and ping. 
I'm removing the plots from the cloud already, cuz once or twice a day I still get the timeout error, but of course, it's not like before, when I could use it for max 1h.  Nothing will be better than local HDD and since my HDDS have arrived, I'm already downloading it all back to local, there's 1Tb left to download, I think today it will be all in local again, finally! :D

From cloud:
![scan](https://user-images.githubusercontent.com/33708227/120361498-4752be80-c2e0-11eb-99b0-49590fb1a58e.jpg)


@lakingsfan29 Dude, it shouldn't be happenning for sure! Try to put all your plots at same location to avoid more scan consume, but even if the plots are in different locations in your HDD, it really should not happen.
And by invalid plots, you mean those that you're processing, or it's invalid when you check? 
But anyway, those unfinished/invalid plots would not cause this issue. 
Whats the avg scan consume you're getting?
