### ISSUE TITLE
1.4 新版本大量plot文件出现plot id check fail

### ISSUE THREAD

**Issue by mengsuenyan** [hpool-dev/chia-miner#513]
问题描述：
从1.3升级到1.4后，有很多机器的plot文件报plot id check fail，经查官方chiapos中并没有该报错，应是hpool miner中报的错误;

使用官方的ProofOfSpace check这些报错的plot文件，均能通过验证，故我们的plot文件应该是没有损坏，且是能通过验证的正常的plot的文件；

请hpool帮忙提供plot文件检查的更多信息，以协助检查报错原因，以降低我们的收益损失；亦或提供加了更多日志的新版本，我们重新测试反馈测试结果，协助你们查找问题;

问题日志如下: 
`
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-10-20-35-1769942333b144dbd8cb968da5df82bdcbde9a0cd4aa3d396ee635292c654bee.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-10-20-55-32fc726b8c130353341bc7dcc52a57be62fbb964ce58a447ba5162bf48d4cd36.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-10-23-26-9bb9e332804d6c5623789d4c5c7660fa92c1c0e515d8dc0e9f17e960b6e4b6f4.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-10-23-53-c373e070c4800ffb34be26b68a79c241a76179e8315569649fb714484fe2c8ca.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-01-05-10c80e01e151a043841df273589c150660413af99798a17d67065cc7a49e1f5e.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-02-39-0b6eab81367039208fb039abc18f9cbf6705ed028c805d46449dc55f4762c97e.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-02-54-479236011f9cc5ac28c63e8baebca6604011b14a2c87f3f749afcf1c3f5c1d7f.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-05-33-255ef79caa343171d0ddfdfa0c5916c7a7770c26f8aad119fec03b43028f4420.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-06-03-ad5c707befd6a82304a4e5a49d5b85d34d69545ac6e4685f7d4a9bb695730e33.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-07-18-25e4d8bfae618fe709afb3f702dc94be9cebc633e58263de2a89be46e296273f.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-08-32-a4b375551b672f5a7b53259ca277580fb2a6573e0e1ad78e680faf50a831140a.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/data1/plot-k32-2021-05-11-08-53-b9495473fb0198c2d4450fea34744a511894b25212a6cb43d82b93e31dcbb2b4.plot tid=60
time="2021-05-28T16:21:39+08:00" level=error msg="add plot file" error="plot id check fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,@@@
22 lines yanked                                                               
`

**Comment by trying2016** [comment]
P的文件有问题，需要重新P盘

**Comment by mengsuenyan** [comment]
@trying2016 那为什么ProofOfSpace能够check通过，且同一台机器有的plot文件报错，有的没有报错?
也许你那边可以帮忙提供写你们文件检查的更多信息，或则提供详细日志的版本;

**Comment by mengsuenyan** [comment]
@trying2016

**Comment by trying2016** [comment]
plot id是需要通过签名来进行校验，官方的ProofOfSpace并没有这项检查。这些文件已经失效
