### ISSUE TITLE
Account verification by phone number for Russia and Ukraine

### ISSUE THREAD

**Issue by MikhailZelenkov** [hpool-dev/chia-miner#52]
When will you fix it?
Or are you deliberately not letting Russians and Ukrainians into the pool?!?

**Comment by PPGOli** [comment]
Beware there is no source code deposit behind this project. It might be a complete scam.

**Comment by h9-dev** [comment]
> When will you fix it?
> Or are you deliberately not letting Russians and Ukrainians into the pool?!?

Недавно было обнаружено, что большое количество SMS-сообщений было отправлено с номеров из России и Украины, поэтому эти два региона временно заблокированы. В настоящее время для отправки СМС подпись не требуется, ее можно использовать в обычном режиме. Мы все еще обсуждаем конкретные решения.

**Comment by MikhailZelenkov** [comment]
> > When will you fix it?
> > Or are you deliberately not letting Russians and Ukrainians into the pool?!?
> 
> Недавно было обнаружено, что большое количество SMS-сообщений было отправлено с номеров из России и Украины, поэтому эти два региона временно заблокированы. В настоящее время для отправки СМС подпись не требуется, ее можно использовать в обычном режиме. Мы все еще обсуждаем конкретные решения.

Ясно. И когда же ждать решения? Я, например, активировал аккаунт через телефонный номер чужой страны (Финляндия),
так как не нашёл другого выхода. Смогу ли я в последствии изменить этот номер телефона на свой, реальный номер?

**Comment by MikhailZelenkov** [comment]
У вас неверно указан телефонный код России. Он не +007, а +7!
Так же, это касается и Казахстана.
