### ISSUE TITLE
1.4.0.2云存储报错，badbit or failbit after reading size 104 at position 0

### ISSUE THREAD

**Issue by exqmjmz** [hpool-dev/chia-miner#527]
windows 1.4.0.2版本 云存储挂载
运行miner提示
level=error msg="add plot file" error="badbit or failbit after reading size 104 at position 0" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,240}" f9="{asm_amd64.s,runtime.goexit,1371}"
所有的plot文件无法加载进来

**Comment by tokenhoki** [comment]
same here. always eror using 1.4.02 T_T

**Comment by trying2016** [comment]
@ljm000 需要检测网络是否正常。这个错误是读取文件有问题

**Comment by Khunmatthew** [comment]
> @ljm000 需要检测网络是否正常。这个错误是读取文件有问题

怎么检测呀？网络是没问题的呀。我也显示同样的问题。

**Comment by iamchriswick** [comment]
6000!!! plots invalid with the new miner. WTF is going on?!?

**Comment by tayanov** [comment]
+1

**Comment by brunoap** [comment]
+1

**Comment by rverdeiros** [comment]
Try this:
Close the console and GUI, then remove all LOG files and open the console again.
It worked for me here.

**Comment by lok960821** [comment]
@ljm000 請問大大如何挂载云存储 可以保持10sec以下
小弟在用rclone挂载 但經常10sec以上

**Comment by exqmjmz** [comment]
> @ljm000 請問大大如何挂载云存储 可以保持10sec以下
> 小弟在用rclone挂载 但經常10sec以上

不行了，以前1.0.5还可以，现在新版的都不行了，特别是网盘挂载
