### ISSUE TITLE
用命令行程序挖矿，经常出现断开连接然后又重新连接的现象

### ISSUE THREAD

**Issue by inSight-mk1** [hpool-dev/chia-miner#53]
信息如图
![image](https://user-images.githubusercontent.com/18531373/116400477-a98d4f00-a85c-11eb-8fb3-3ad13f8add7f.png)
这个会影响收益吗？

**Comment by rmokerone** [comment]
+1

**Comment by h9-dev** [comment]
偶尔的几次并不会影响收益。
