### ISSUE TITLE
Hpool在线算力看不到plot但是矿机在线

### ISSUE THREAD

**Issue by SNGDude** [hpool-dev/chia-miner#54]
已经确认绑定没错误了，plot是用官方钱包之前P的。
![1](https://user-images.githubusercontent.com/33142810/116443442-3c8eaf00-a886-11eb-8f87-00eec73f4a61.png)
![2](https://user-images.githubusercontent.com/33142810/116443445-3ef10900-a886-11eb-97f2-d805b6411f4a.png)
![3](https://user-images.githubusercontent.com/33142810/116443447-40223600-a886-11eb-8a3a-c8dddb237786.png)

**Comment by DWRex** [comment]
我也遇到这个问题，不清楚怎么解决

**Comment by hufh** [comment]
我也有同样的问题。与楼主的情况完全相同，官方工具P的图，“在线矿机”页面显示正常，但“在线算力”和”贡献点“没有任何内容。这个问题看起来很普遍，如果是个bug，请尽快fix，如果不是问题，请更新帮助文件。

**Comment by hufh** [comment]
打开"在线算力"，点击“未签名”，可以看到PLOT文件，但是按照网站上的提示完成签名操作后，仍然无法对算力进行签名。

**Comment by 85256638** [comment]
> 打开"在线算力"，点击“未签名”，可以看到PLOT文件，但是按照网站上的提示完成签名操作后，仍然无法对算力进行签名。

我也是同样的问题， “在线矿机”页面显示正常，但“在线算力”和”贡献点“没有任何内容， 然后未签名里面也看不到 plot文件

**Comment by h9-dev** [comment]
> 打开"在线算力"，点击“未签名”，可以看到PLOT文件，但是按照网站上的提示完成签名操作后，仍然无法对算力进行签名。
出现这个中问题通常是签名的不是你的这个算力，请检查你的 pool public key 是否一致。

**Comment by 85256638** [comment]
我等了大概一个多小时后网站上算力更新了，Dev 应该把这个写道帮助文件里面，要不然每个人都要问
