### ISSUE TITLE
Incorrect calculation of Plots

### ISSUE THREAD

**Issue by Magby123** [hpool-dev/chia-miner#547]
1. Total plots ( 99% of plots checked succesfully ) 861  !
<img width="650" alt="3333" src="https://user-images.githubusercontent.com/78310118/120293507-0356be00-c2ce-11eb-8456-8189c451a8f4.png">
1.1
![image](https://user-images.githubusercontent.com/78310118/120294177-9e4f9800-c2ce-11eb-9a62-ecaee2b948dc.png)

2 .Online on site only 679
  ![image](https://user-images.githubusercontent.com/78310118/120293416-ea4e0d00-c2cd-11eb-8412-96c96bb77778.png)

 2 miners was online more than a week

**Comment by Magby123** [comment]
![image](https://user-images.githubusercontent.com/78310118/120294077-837d2380-c2ce-11eb-9c91-7608dfd1ecc9.png)

**Comment by Magby123** [comment]
![image](https://user-images.githubusercontent.com/78310118/120294396-d1922700-c2ce-11eb-89c6-d7ed8f17cc23.png)

**Comment by williamchangck86** [comment]
Same issue like this

**Comment by williamchangck86** [comment]
> 1. Total plots ( 99% of plots checked succesfully ) 861  !
> 
> <img width="650" alt="3333" src="https://user-images.githubusercontent.com/78310118/120293507-0356be00-c2ce-11eb-8456-8189c451a8f4.png">
> 
> 1.1
> 
> ![image](https://user-images.githubusercontent.com/78310118/120294177-9e4f9800-c2ce-11eb-9a62-ecaee2b948dc.png)
> 
> 
> 
> 2 .Online on site only 679
> 
>   ![image](https://user-images.githubusercontent.com/78310118/120293416-ea4e0d00-c2cd-11eb-8412-96c96bb77778.png)
> 
> 
> 
>  2 miners was online more than a week

Same issue

**Comment by jedocampo** [comment]
check your plots load time if it can't got thru it less than 5 secs. they get drop.

**Comment by Magby123** [comment]
> check your plots load time if it can't got thru it less than 5 secs. they get drop.

What command you use to do that ? No errors  in Hpool miner logs

**Comment by bertybassett** [comment]
same here 91Tb in farm but only 40TB online

**Comment by Magby123** [comment]
884 olotson the site  from 901 in miner.... Looks it arent count well

**Comment by Magby123** [comment]
No more actual.

**Comment by bertybassett** [comment]
and the fix was?  there isn't one so I moved to pool core good bye

P.S my plots were on USB disks on USB 3.0 so I know there were passing the 5 seconds rule. Also check the logs and not plots failing the 5 second rule.

**Comment by Magby123** [comment]
> and the fix was? there isn't one so I moved to pool core good bye
> 
> P.S my plots were on USB disks on USB 3.0 so I know there were passing the 5 seconds rule. Also check the logs and not plots failing the 5 second rule.
Its just pool calculation delay -no  any errors in my logs from pool and info now actual on site... You arent see such updates.
