### ISSUE TITLE
Online plot has been empty for a very long time

### ISSUE THREAD

**Issue by danil-ar** [hpool-dev/chia-miner#549]
Hi, I ask for help. My list of online plot is empty for over a day

**Comment by alperaslan** [comment]
Can you tell me your ownership is netspace?

**Comment by danil-ar** [comment]
9.80TB + 3.56TB
total 13.36TB

**Comment by kamieal** [comment]
Hi, same the issue come last night and after the hpool version.

**Comment by williamchangck86** [comment]
I also facing same problem, submitted 48.92T, but only showing me 11.78T and everything our side n internet is normal

**Comment by Alijambo** [comment]
Same problem.  375 plots were added 10 hours ago and still not showing under online plots.  Total online power shows, binding shows as successful and miner is online.

**Comment by xazes** [comment]
for me it work. MAYBE because i had set in config.yaml scanpath to true and scanminute = 15

**Comment by Ratzoletto** [comment]
This worked for me on Windows 10 with HPool Chia-v1.4.1-0.

I had the same issue for about 8 hours. I fixed it by adding all directorys to the GUI. Restart the GUI and wait until all your TiB are visible on HPool Online Miner. I waited another 2 hours and nothing happened with "Online Plots".

Check your config.yaml file. All directorys must be listed in your config file.

Right after checking my config file I closed the GUI app and startet farming via console app. After 2 hours **all** my plots went to "Online Plots".

Scan time set to 15 min.

**Comment by bluemoon21** [comment]
Many thanks to everyone on this forum.
Been plotting on the Chia Farm Gui for 6 weeks with Linux. Transferred to Hpool 4 days ago with some 240 plots. But the Hpool site will only recognise 10% !!
Made sure the config.yaml has them listed 10 hours ago [only had 2 HDD not 6] and made Scan time 15mins thanks to Ratzoletto etc.
When the current plots are finished, will try reloaded everything. 
I am VERY happy with free Linux Mint [for 5 years] and I hate MS Windows [blot & pay for EVERYTHING]. 
Being 74 yo with a stroke [one hand now] and Dysphasia [writing/speech difficulty] I don't use Terminal much, mainly have to use GUI [Swar Chia Plot Manager too hard?]. 
Do I have to load Windows to effectively trade Hpool?

**Comment by bluemoon21** [comment]
ps and BTW; Hpool keeps dropping out every few hours [ 5 or 6 times a day]. What to do?
Also in Hpool with plotting, in the main Chai farm Gui with harvest/farming turned off, gui the plots now take 20% or longer to plot than when solo. Any suggestion?

Sorry if the text is long etc,
 I am disabled old fart.
