### ISSUE TITLE
为啥farming时 CPU还占用14%。solo时CPU占用几乎为0

### ISSUE THREAD

**Issue by Cricetulus** [hpool-dev/chia-miner#55]

**Comment by gcuuf** [comment]
为什么这个问题没有人回到？有人说软件在偷跑挖罗门币是真的吗？请开放源码

**Comment by trying2016** [comment]
最新版本解决了内存和CPU占用问题 
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by h9-dev** [comment]
> 为什么这个问题没有人回到？有人说软件在偷跑挖罗门币是真的吗？请开放源码

跑起来门罗，CPU 和内存都会很高很高 。
