### ISSUE TITLE
树莓派版本 v1.4.0-2 报错无法打开软件

### ISSUE THREAD

**Issue by peterwong3000** [hpool-dev/chia-miner#551]
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x152a8ff0 pc=0xffff7c327848]

runtime stack:
runtime.throw(0x97c280, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall]:
runtime.cgocall(0x709208, 0x40000df618, 0x40000c6140)
        /usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x40000df5e0 sp=0x40000df5a0 pc=0x403d60
os/user._Cfunc_mygetpwuid_r(0x3e8, 0x400013a990, 0x153bd060, 0x400, 0x40000c6140, 0x200000000)
        /tmp/go-build2748417885/b104/_cgo_gotypes.go:172 +0x44 fp=0x40000df610 sp=0x40000df5e0 pc=0x6815a4
os/user.lookupUnixUid.func1.1(0x3e8, 0x400013a990, 0x40000a1c20, 0x40000c6140, 0x40000df6c8)

**Comment by Kayuii** [comment]
用 docker 跑吧，少问题
可以看 [issue#399](https://github.com/hpool-dev/chia-miner/issues/399)

**Comment by Cattigrew** [comment]
> fatal error: unexpected signal during runtime execution
> fatal error: unexpected signal during runtime execution
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x152a8ff0 pc=0xffff7c327848]
> 
> runtime stack:
> runtime.throw(0x97c280, 0x2a)
> /usr/local/go/src/runtime/panic.go:1117 +0x54
> runtime.sigpanic()
> /usr/local/go/src/runtime/signal_unix.go:718 +0x29c
> 
> goroutine 1 [syscall]:
> runtime.cgocall(0x709208, 0x40000df618, 0x40000c6140)
> /usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x40000df5e0 sp=0x40000df5a0 pc=0x403d60
> os/user._Cfunc_mygetpwuid_r(0x3e8, 0x400013a990, 0x153bd060, 0x400, 0x40000c6140, 0x200000000)
> /tmp/go-build2748417885/b104/_cgo_gotypes.go:172 +0x44 fp=0x40000df610 sp=0x40000df5e0 pc=0x6815a4
> os/user.lookupUnixUid.func1.1(0x3e8, 0x400013a990, 0x40000a1c20, 0x40000c6140, 0x40000df6c8)

issue#537里提供了解决方法，用arm32v7/ubuntu docker下可以正常运行

**Comment by peterwong3000** [comment]
ubuntu@ubuntu:~$ sudo docker logs miner
{1048576 1048576}
Rlimit Final {999999 999999}
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.4.0 2
**** BuildTime:2021-05-26-15:00:00 GMT
**** MinerName:Pi
**** ApiKey:e14d713b-0631-4d6e-a6fd-67a08b1594b2
***************************************************
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3b381ff0 pc=0xffff77f09848]

runtime stack:
runtime.throw(0x97c280, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall]:
runtime.cgocall(0x709208, 0x400011b618, 0x4000010150)
        /usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x400011b5e0 sp=0x400011b5a0 pc=0x403d60


Docker 一样的错误。这个要抛弃ARM版本了么。

**Comment by Kayuii** [comment]
我测得是 pi 的原始版本，没用过 pi 的 ubuntu 版本
