### ISSUE TITLE
更新1.4.0-2后arm64版本报错

### ISSUE THREAD

**Issue by Cattigrew** [hpool-dev/chia-miner#552]
似乎是go语言的问题，不知道该怎么解决
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x2c4d8ff0 pc=0xffff74259848]
> 
> runtime stack:
> runtime.throw(0x97c280, 0x2a)
>         /usr/local/go/src/runtime/panic.go:1117 +0x54
> runtime.sigpanic()
>         /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

**Comment by StormYudi** [comment]
好多issues反馈这个问题了，只能等官方解决了

**Comment by ferdiina** [comment]
没人管的

**Comment by Kayuii** [comment]
用 docker 跑吧，少问题
可以看 [issue#399](https://github.com/hpool-dev/chia-miner/issues/399)

**Comment by Cattigrew** [comment]
> 用 docker 跑吧，少问题
> 可以看 [issue#399](https://github.com/hpool-dev/chia-miner/issues/399)

我就是用Ubuntu 20.04的docker跑的，不过[issue#537](https://github.com/hpool-dev/chia-miner/issues/537)里提供了解决方法，用arm32v7/ubuntu docker可以正常运行

**Comment by zl319** [comment]
![image](https://user-images.githubusercontent.com/85951548/122090578-7b7ac300-ce3a-11eb-84c1-af8d903be916.png)



Operating environment：
Quad core arm cortex-a55 processor @ 1.9 GHz
4GB DDR3 / 64GB eMMC
Debian GNU/Linux 10 (buster) with Linux 5.4.108

HPool-Miner-chia-v1.4.1-0-arm、HPool-Miner-chia-v1.4.1-0-aarch64 cannot execute

Unable to run, important error

seek help
seek help
seek help
seek help
