### ISSUE TITLE
No revenue, no chart 

### ISSUE THREAD

**Issue by Aleksandarmkd** [hpool-dev/chia-miner#555]
Hi,
I have an issue, minner seems OK, 42Tb, represented in Online Miner tab.
In configuration, binding check was recently changed from auditing to successful. 
I hoped this will resolve the problem, but still no revenue after block 343420. 
Also in Contribution no chart is presented even though the miner seems to function normally.

**Comment by Aleksandarmkd** [comment]
So, the solution is: when the new version of hpool miner is installed, you will need to resign again with all the api key, mnemonic signature, config file modification, everything that was done in the first place when you installed the miner, you will have to re-do it again and this will solve the issue.

**Comment by desstannoz** [comment]
@Aleksandarmkd I can't solve it. Can you help me?
