### ISSUE TITLE
1.1.0 cpu占用率很高.并且使用内存一直在变大.

### ISSUE THREAD

**Issue by icelove88** [hpool-dev/chia-miner#57]
1.1.0 cpu占用率很高. 并且使用内存一直在变大.

**Comment by LXY1226** [comment]
+1我也是

**Comment by ferdiina** [comment]
直接单核100%

**Comment by momax929** [comment]
问题一：cpu占用过高
问题二：内存泄漏

**Comment by rnizametdinov** [comment]
confirm!
take 1 cpu core

**Comment by ybxxqp** [comment]
Please fix! Take 1 cpu core and RAM leak to 1GB in 8 hours. This is affecting plotting!!!

**Comment by trying2016** [comment]
v1.1.1版本修复了CPU和内存占用问题

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
