### ISSUE TITLE
客户端能否支持显示重复、无效的plot

### ISSUE THREAD

**Issue by jaysunneu** [hpool-dev/chia-miner#58]
目录下的文件数量跟客户端显示的数量不一致，客户端识别的文件比目录下少十几个，能否在客户端增加显示识别到的plot有哪些，重复的有哪些，无效的有哪些？

**Comment by codename10086** [comment]
对，这个功能应该有。有时在两台机上转来转去，有些是重复的，希望可以自动识别出来。

**Comment by trying2016** [comment]
v1.1.1 版本支持显示无效问题
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
