### ISSUE TITLE
ERRO[2021-06-08T04:34:21Z] 您的扫盘时间(15.00s)超过最大时间限制(10.00s)         

### ISSUE THREAD

**Issue by matheust3** [hpool-dev/chia-miner#594]
```
ERRO[2021-06-08T04:35:02Z] 您的扫盘时间(15.00s)超过最大时间限制(10.00s)                f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,125}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=5023
ERRO[2021-06-08T04:35:09Z] 扫盘超时                                          f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path=/mnt/hd2 scan limit=10000 scan time=15000 tid=5023
INFO[2021-06-08T04:35:09Z] new mining info                               capacity="3.37 TB" file=loggers.go func=logging.CPrint height=400392 jobId=1315544745 line=168 scan consume=15000 scan time="2021-06-08 04:35:02" tid=5023
```

**Comment by pongit** [comment]
> ```
> ERRO[2021-06-08T04:35:02Z] 您的扫盘时间(15.00s)超过最大时间限制(10.00s)                f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,125}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=5023
> ERRO[2021-06-08T04:35:09Z] 扫盘超时                                          f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path=/mnt/hd2 scan limit=10000 scan time=15000 tid=5023
> INFO[2021-06-08T04:35:09Z] new mining info                               capacity="3.37 TB" file=loggers.go func=logging.CPrint height=400392 jobId=1315544745 line=168 scan consume=15000 scan time="2021-06-08 04:35:02" tid=5023
> ```

**Comment by pongit** [comment]
> ```
> ERRO[2021-06-08T04:35:02Z] 您的扫盘时间(15.00s)超过最大时间限制(10.00s)                f7="{loggers.go,logging.CPrint,156}" f8="{wrapper_miner.go,miner.(*Wrapper).Start.func3,125}" f9="{server.go,server.(*Server).MiningInfo,37}" tid=5023
> ERRO[2021-06-08T04:35:09Z] 扫盘超时                                          f7="{loggers.go,logging.CPrint,156}" f8="{miner.go,chia.(*Miner).MinerStatus,247}" f9="{wrapper_miner.go,miner.(*Wrapper).Start.func3,117}" path=/mnt/hd2 scan limit=10000 scan time=15000 tid=5023
> INFO[2021-06-08T04:35:09Z] new mining info                               capacity="3.37 TB" file=loggers.go func=logging.CPrint height=400392 jobId=1315544745 line=168 scan consume=15000 scan time="2021-06-08 04:35:02" tid=5023
> ```
