### ISSUE TITLE
在文件没有重复的情况下，双机挖矿的算力只计算最高者

### ISSUE THREAD

**Issue by DWRex** [hpool-dev/chia-miner#60]
你好，我有两台机同时挖矿。虽然它们**所挖文件都是没有重复**，但是在后台查看会发现矿池只计算了最高容量的贡献点，并且在在线算力中不能找到比较低的矿机所拥有的“田”。
而当我关闭最高算力的矿机时，贡献点又转为由算力较低的机提供。不过，在在线算力一栏依旧没有算力较低的机的“田”，而是仍然显示已经关闭的最高算力机器的“田”还在线。
两者对比可以发现，虽然算力较低的机器所拥有的“田”是被承认的，但是当有更高算力的机器加入时，其贡献会被抹除。同时，在线算力从始至终都没有更新过一次。
请问这种情况应该如何解决？
谢谢！

**Comment by h9-dev** [comment]
可能出现了矿机名称重复了。
