### ISSUE TITLE
v.1.4.1-1 is still rubbish

### ISSUE THREAD

**Issue by bertybassett** [hpool-dev/chia-miner#602]
version v1.4.0-2 listed 14Tb of 927 plot all on USB drives within 5 seconds.

loaded v1.4.1-1

and now its increased to 18TB of 927 plots with the same setup.

Linux version ubuntu 21.04.

**Comment by tyan-boot** [comment]
can't agree more. In hpool, they fix bug in two ways, 1) replot your files, 2) replace your hard drives.

**Comment by bertybassett** [comment]
New version fixed my issues just need to wait 12 hours
