### ISSUE TITLE
Add logging of badbit filename

### ISSUE THREAD

**Issue by ghost** [hpool-dev/chia-miner#603]
I have made check using standard `chia plots check`. And it shows all fine!

But hpool miner thinks that 1 file is corrupted.

Let us know which file should be replaced - out its name to console.

**Comment by trying2016** [comment]
This error is due to file reading problems

**Comment by ghost** [comment]
> 
> 
> This error is due to file reading problems

@trying2016 It is most likely impossible, it is RAID on server hardware. Miner always shows 1 plot. If plot is not corrupted then you have bug in your software.
