### ISSUE TITLE
升级 1.4.1 依然有错误，200t 只能识别100t 然后就会添加失败了

### ISSUE THREAD

**Issue by gdtiti** [hpool-dev/chia-miner#604]
本地硬盘
以前可以 某天开始突然报错不能识别部分文件
官方程序可以正常挖矿，plots check 一切正常
===========================================================
level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-06-23-93df0e1cea26cadbbbab47720441e54ff0ab19ebaa9eca4d46cb11c1e242a1ad.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-06-23-93df0e1cea26cadbbbab47720441e54ff0ab19ebaa9eca4d46cb11c1e242a1ad.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-08-29-5fbd3f55a440cbc68a3c1f519e4c570f8f914aa3addd84e80c038ec8b3c746b8.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-08-29-5fbd3f55a440cbc68a3c1f519e4c570f8f914aa3addd84e80c038ec8b3c746b8.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-09-52-7cd266c0ea29fdef171a560fd3c711b724148f162651fd03a801051d2432c1ef.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-09-52-7cd266c0ea29fdef171a560fd3c711b724148f162651fd03a801051d2432c1ef.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-11-50-87b5222fcdbafe49e111a8a4c39f86441a3af8d7c89f850316221b77ddbbd14d.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-11-50-87b5222fcdbafe49e111a8a4c39f86441a3af8d7c89f850316221b77ddbbd14d.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-13-38-0717115eef5b299f8af18dfce75d9e12d51697d105bfb8a746456a61d62111f3.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-13-38-0717115eef5b299f8af18dfce75d9e12d51697d105bfb8a746456a61d62111f3.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-14-53-6bc0f675fe0fe20b1f7013f7c9cdc020b1eb64fe933a8a99032b004f1e92989d.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-14-53-6bc0f675fe0fe20b1f7013f7c9cdc020b1eb64fe933a8a99032b004f1e92989d.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-17-28-a4685b550f7a0760880cd32e70956a16ebf76902e7eb72cfe0b18fb8c0d49970.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-17-28-a4685b550f7a0760880cd32e70956a16ebf76902e7eb72cfe0b18fb8c0d49970.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-18-14-bca74398e0910ac8a76cc9f9bc02e8148ecd0721884c809e4d5971eae06fc87c.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-18-14-bca74398e0910ac8a76cc9f9bc02e8148ecd0721884c809e4d5971eae06fc87c.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-22-17-87cedf51210936a3e7d7220bf97e522edde91a776f654c75860cf0073cf64d92.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-22-17-87cedf51210936a3e7d7220bf97e522edde91a776f654c75860cf0073cf64d92.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-22-29-eacba3eb6b5a76b4cd471108dac193dc5cfbbe4adae0242cca1590a3323d798c.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-22-29-eacba3eb6b5a76b4cd471108dac193dc5cfbbe4adae0242cca1590a3323d798c.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-17-22-31-2572f53d2757fa3e02f0e2ab8760e15b9bd97d71d6d4b18140bc3a7363f39340.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-17-22-31-2572f53d2757fa3e02f0e2ab8760e15b9bd97d71d6d4b18140bc3a7363f39340.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-04-11-9cec561273eed1c849d0fbed8f932c4f1dfea7dc651f2395f520e5ab3f94ccf0.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-04-11-9cec561273eed1c849d0fbed8f932c4f1dfea7dc651f2395f520e5ab3f94ccf0.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-04-18-cb9f66853be2469fb00dee384acc11f23faa07dc140bf321b54b9a0208b8b3e6.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-04-18-cb9f66853be2469fb00dee384acc11f23faa07dc140bf321b54b9a0208b8b3e6.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-04-51-ba1b4e0cfe25b33b50b8df6fd48bdc9b8684e71f26c61ef42b6f2416d2df6dce.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-04-51-ba1b4e0cfe25b33b50b8df6fd48bdc9b8684e71f26c61ef42b6f2416d2df6dce.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-09-05-60962b468240817dfabefcac88e6c6d395f76d3ee94f8ac97cb49dbbc53489f0.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-09-05-60962b468240817dfabefcac88e6c6d395f76d3ee94f8ac97cb49dbbc53489f0.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-10-07-6095f7da8b4d3c1da7463f283b0253e27e92b83937f63053443d739c58cfe5bf.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-10-07-6095f7da8b4d3c1da7463f283b0253e27e92b83937f63053443d739c58cfe5bf.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-13-26-ebd7e904de01c41927d5747d798ead019e3124d077a3808c6d088db286c45051.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-13-26-ebd7e904de01c41927d5747d798ead019e3124d077a3808c6d088db286c45051.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-14-02-b98b66d0393ec7d102449c12592fab39691ebea268d3f73c37845309d7a7acba.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-14-02-b98b66d0393ec7d102449c12592fab39691ebea268d3f73c37845309d7a7acba.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-16-12-a609735f677f4e791b7ce1bc4081b1ce8be104e140fff436a17a19dd6675e513.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-16-12-a609735f677f4e791b7ce1bc4081b1ce8be104e140fff436a17a19dd6675e513.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-19-09-77c1645e8ffee5398040c890805cd44792e16b40a3ddb0493a91825ea7baebcf.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-19-09-77c1645e8ffee5398040c890805cd44792e16b40a3ddb0493a91825ea7baebcf.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-19-33-c40ebe391f7c89edef63cb7bccd0e51049f71402c117b307cb53ff53fa947aff.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-19-33-c40ebe391f7c89edef63cb7bccd0e51049f71402c117b307cb53ff53fa947aff.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-22-57-3228f40f0929248b4cbd03b41f6a41348c10db954430e58574d9397dac0bc10d.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-22-57-3228f40f0929248b4cbd03b41f6a41348c10db954430e58574d9397dac0bc10d.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-23-14-16baecfa5b1cb049c3612c50e6c51efc073b3772a9ec71e3641c0cbc8875e660.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-23-14-16baecfa5b1cb049c3612c50e6c51efc073b3772a9ec71e3641c0cbc8875e660.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-18-23-56-bbf4165e95c3d4c0f93b9c48448b5bdee56125874d44d2bf54c98ed416c81492.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-18-23-56-bbf4165e95c3d4c0f93b9c48448b5bdee56125874d44d2bf54c98ed416c81492.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-02-40-f95c35684134b486413591b632970a0c6283b230e2eebc4e037a2804313c38bc.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-02-40-f95c35684134b486413591b632970a0c6283b230e2eebc4e037a2804313c38bc.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-04-36-f5da446cfe4a2b46c176cc54bd1f1560ef4759cf0047afc81b7601167b9e1eef.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-04-36-f5da446cfe4a2b46c176cc54bd1f1560ef4759cf0047afc81b7601167b9e1eef.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-05-19-ed532bf08f2d8796186ac6bc0984cb1c03f9616f89ce288fc76d8a1aac2b5069.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-05-19-ed532bf08f2d8796186ac6bc0984cb1c03f9616f89ce288fc76d8a1aac2b5069.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-06-57-57c80075bd0add226ee36b99f0da43398d7d164e9c4f8edd9ee1b956abbfbf5f.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-06-57-57c80075bd0add226ee36b99f0da43398d7d164e9c4f8edd9ee1b956abbfbf5f.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-10-47-90a6a14e9fd49ec0e1af88e0cbbc16d1a1b72ce6a4196cc38d8fdabe83f7a73f.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-10-47-90a6a14e9fd49ec0e1af88e0cbbc16d1a1b72ce6a4196cc38d8fdabe83f7a73f.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-11-14-b4420e9cf6ba42d994e112601b8e982b5ea89014ba19827045fc5a6f9ccfa150.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-11-14-b4420e9cf6ba42d994e112601b8e982b5ea89014ba19827045fc5a6f9ccfa150.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-13-43-98c8b1b2de6573090714e62a83353898eb57fc864d65f87346ed3dd443469c11.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-13-43-98c8b1b2de6573090714e62a83353898eb57fc864d65f87346ed3dd443469c11.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-15-21-eae46ec8136811578ee2ab431e548ac539771cc370e32e9e726f0a9a9d99533a.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-15-21-eae46ec8136811578ee2ab431e548ac539771cc370e32e9e726f0a9a9d99533a.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-15-56-09baf3325f002b44d232acf92d986b0cfa3f4132a5c3f6bdaec1dc86dcdf95ee.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-15-56-09baf3325f002b44d232acf92d986b0cfa3f4132a5c3f6bdaec1dc86dcdf95ee.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-20-35-4f891e9694980894c7b8cf687a2df02660250ad241d39659e3a4cfdc0fe96bb3.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-20-35-4f891e9694980894c7b8cf687a2df02660250ad241d39659e3a4cfdc0fe96bb3.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-21-03-ee8f7abeff524183c4c516dc230a65f575b578bbf27ed62a4f398d2d445d4df8.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-21-03-ee8f7abeff524183c4c516dc230a65f575b578bbf27ed62a4f398d2d445d4df8.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-19-21-51-5332f00191e649ef9df7b7226f13ae3d4930bdddb2b0532f47c82a6f0b1463f2.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-19-21-51-5332f00191e649ef9df7b7226f13ae3d4930bdddb2b0532f47c82a6f0b1463f2.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-20-01-25-f77fa962ea7877e6e5c87e03c78e2d7de9074812f5c12abc5695e19702674066.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-20-01-25-f77fa962ea7877e6e5c87e03c78e2d7de9074812f5c12abc5695e19702674066.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-20-04-03-4c39084ad368e676832c9f1304dc4bcd7fdec0d18ba04c60d4285fdca64229fb.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-20-04-03-4c39084ad368e676832c9f1304dc4bcd7fdec0d18ba04c60d4285fdca64229fb.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-20-05-12-c9349ea8774dc9ae93d7f14ad2015663f83f0fa8084574f135fe60a46f2fc25e.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-20-05-12-c9349ea8774dc9ae93d7f14ad2015663f83f0fa8084574f135fe60a46f2fc25e.plot tid=112
time="2021-06-10T12:57:38+08:00" level=error msg="add plot file" error="Invalid file /mnt/dst/16t010/plot-k32-2021-05-20-09-59-9152e4f03a584cbcb2520a2d541ee303f63e94b7790d1d096d07967abf6932d7.plot" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,246}" f9="{asm_amd64.s,runtime.goexit,1371}" file=/mnt/dst/16t010/plot-k32-2021-05-20-09-59-9152e4f03a584cbcb2520a2d541ee303f63e94b7790d1d096d07967abf6932d7.plot tid=112

**Comment by trying2016** [comment]
需要检测文件是否正常

**Comment by gdtiti** [comment]
大哥 我i提交了好多次 文件一切正常 plots check 没有错误，官方挖矿正常。而且 每次报的错误文件都不一样 甚至错的盘都不一样
