### ISSUE TITLE
在线算力不刷新

### ISSUE THREAD

**Issue by DWRex** [hpool-dev/chia-miner#61]
你好，即使我把所有矿机离线，在线算力一栏还是显示某些矿机的“田”依然在线。
请问为什么不会刷新？

**Comment by 85256638** [comment]
我也同样的问题，不知道如何解决

**Comment by 85256638** [comment]
我等了大概一个多小时后网站上算力更新了，Dev 应该把这个写道帮助文件里面，要不然每个人都要问
