### ISSUE TITLE
hpool X-Proxy plot issues

### ISSUE THREAD

**Issue by ka1029** [hpool-dev/chia-miner#617]
use hpool new X-Proxy some detail issues plot document is "0" 

![image](https://user-images.githubusercontent.com/84852651/121711356-1a3ab300-cb0d-11eb-9bba-9ed88f7be0ce.png)

**Comment by cool2hatex** [comment]
How yours show storage amount? Mine shows "0" in both sides.

**Comment by jedocampo** [comment]
im having the same problem my miner have 54tb its only reporting 4tb

**Comment by mmaa-crypto** [comment]
same ...

**Comment by mmaa-crypto** [comment]
> How yours show storage amount? Mine shows "0" in both sides.

have you interred your proxy ip on the hpool miner ?

**Comment by cool2hatex** [comment]
> > How yours show storage amount? Mine shows "0" in both sides.
> 
> have you interred your proxy ip on the hpool miner ?

No. :S

**Comment by Magby123** [comment]
> > > How yours show storage amount? Mine shows "0" in both sides.
> > 
> > 
> > have you interred your proxy ip on the hpool miner ?
> 
> No. :S

Mine X proxy showed 14 TB of 40TB in client   and on SIte -  so i turned it off...

**Comment by ka1029** [comment]
> How yours show storage amount? Mine shows "0" in both sides.

left hand side is 33.57TB file .

**Comment by Magby123** [comment]
> > How yours show storage amount? Mine shows "0" in both sides.
> 
> left hand side is 33.57TB file .

 And what was the fix for issue ?
