### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by little-snow-fox** [hpool-dev/chia-miner#625]
Version: HPool-Miner-Chia-v1.4.1-1
运行十几分钟后就出现如下报错
Error logs:
```
time="2021-06-15T15:26:53+08:00" level=info msg="new mining info" capacity="3.56 TB" file=loggers.go func=logging.CPrint height=433840 jobId=1882141026 line=168 scan consume=241 scan time="2021-06-15 15:26:42" tid=901
time="2021-06-15T15:27:01+08:00" level=info msg="new mining info" capacity="3.56 TB" file=loggers.go func=logging.CPrint height=433841 jobId=1319185836 line=168 scan consume=241 scan time="2021-06-15 15:26:53" tid=901
time="2021-06-15T15:27:10+08:00" level=info msg="new mining info" capacity="3.56 TB" file=loggers.go func=logging.CPrint height=433841 jobId=1709518144 line=168 scan consume=241 scan time="2021-06-15 15:27:01" tid=901
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x72fb9a]

goroutine 901 [running]:
github.com/trying2016/common-tools/utils.(*Queue).Push(...)
	vendor/github.com/trying2016/common-tools/utils/queue.go:36
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).AddScanner(...)
	miner/chain/chia/plotterSpace.go:269
hpool.com/dev/miner-client/miner/chain/chia.(*Miner).NewMiningInfo(0xc00014a420, 0xa2da88, 0xc0001701c0, 0xc000170100, 0x0)
	miner/chain/chia/miner.go:187 +0x23a
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func3(0x97f040, 0xc0000102e0)
	miner/wrapper_miner.go:115 +0x10a
hpool.com/dev/miner-client/miner/server.(*Server).MiningInfo(0xc00007b020, 0x97f040, 0xc0000102e0)
	miner/server/server.go:37 +0x3d
hpool.com/dev/miner-client/miner/server/websocket.(*Server).connect.func1(0xc0001582c0, 0xc000021280)
	miner/server/websocket/server.go:127 +0x13f
created by hpool.com/dev/miner-client/miner/server/websocket.(*Server).connect
	miner/server/websocket/server.go:107 +0x4a6
```
System info:
```
test@work:~$ cat /etc/issue
KDE neon 5.22 \n \l

test@work:~$ cat /proc/version
Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021

test@work:~$ docker -v
Docker version 20.10.7, build f0df350

test@work:~$ lsb_release -is
Neon
test@work:~$ lsb_release -rs
20.04

root@work:/opt/sysbox# cat /etc/os-release 
NAME="KDE neon"
VERSION="5.22"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.22"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
System kernel version:
```
test@work:~$ uname -r
5.12.10-051210-generic
```

**Comment by anignatev** [comment]
We have seen the same issue!

Version: HPool-Miner-chia-og-v1.5.6-1, running on Linux CentOS 7.

Please, fix it or publish the source code!!

_________________________________________________________________________ 
Loading plotter files /mnt/data1/ (24/71) 33%
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8e1506]

runtime stack:
runtime.throw(0x9bc50e, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 10 [syscall]:
runtime.cgocall(0x7c09d0, 0xc0000a9190, 0xc0000a9100)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000a9160 sp=0xc0000a9128 pc=0x40719b
hpool.com/dev/pool-wallet/pkg/crypto/bls._Cfunc_key_derive_child(0x131f7a0, 0xc00000305d, 0x0)
        /var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build1088925942/b158/_cgo_gotypes.go:202 +0x49 fp=0xc0000a9190 sp=0xc0000a9160 pc=0x73e569
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild.func1(0xc0000a9208, 0xc0000a9200, 0x131f7a0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0x74 fp=0xc0000a91d0 sp=0xc0000a9190 pc=0x73f374
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild(0xc000510288, 0xc0000a92c8, 0x4, 0x4, 0x0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0xb3 fp=0xc0000a9250 sp=0xc0000a91d0 pc=0x73ea13
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).CheckPlotId(0xc0003502d0, 0xc000131700)
        miner/chain/chia/common/chiapos/chia.go:513 +0x16f fp=0xc0000a9340 sp=0xc0000a9250 pc=0x74304f
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Open(0xc000308a80, 0x6a, 0x0, 0xc0000a9530, 0x16)
        miner/chain/chia/common/chiapos/chia.go:121 +0x225 fp=0xc0000a94e8 sp=0xc0000a9340 pc=0x7412a5
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc000308a80, 0x6a, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:158 +0x85 fp=0xc0000a9540 sp=0xc0000a94e8 pc=0x741725
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc000482100, 0xc000133140, 0xb, 0x1)
        miner/chain/chia/plotterSpace.go:209 +0x3e6 fp=0xc0000a9fc0 sp=0xc0000a9540 pc=0x7532c6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000a9fc8 sp=0xc0000a9fc0 pc=0x474f01
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:68 +0x2fb

goroutine 1 [chan receive]:
hpool.com/dev/miner-client/platform.Run(0xc000163f50, 0xc000100240, 0xa37998, 0xc0001b6240)
        platform/console.go:84 +0x8f3
