### ISSUE TITLE
gui cannot browse map drive network

### ISSUE THREAD

**Issue by arm321689** [hpool-dev/chia-miner#63]
gui cannot browse map drive network
pleas add this function

**Comment by codename10086** [comment]
you can use NAS drive like \\192.168.50.14\ht_2t\Plots to add them.

**Comment by codename10086** [comment]
\\192.168.50.14\ht_2t\Plots

**Comment by codename10086** [comment]
double \

**Comment by PPGOli** [comment]
Beware there is no source code deposit behind this project. It might be a complete scam.

**Comment by h9-dev** [comment]
please try v1.1.1
