### ISSUE TITLE
MAC的挖矿还是无法在矿池里显示出来

### ISSUE THREAD

**Issue by only145** [hpool-dev/chia-miner#67]
<img width="1427" alt="截屏2021-04-30 下午7 34 05" src="https://user-images.githubusercontent.com/69851394/116690504-0a975d00-a9ec-11eb-9598-7fbae276367b.png">
运行界面这样是对的吗？配置文件如下图
<img width="535" alt="截屏2021-04-30 下午7 41 56" src="https://user-images.githubusercontent.com/69851394/116690558-21d64a80-a9ec-11eb-8a82-320648d93dce.png">

**Comment by trying2016** [comment]
请使用最新的v1.1.1版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by trying2016** [comment]
1.2.0版本对崩溃问题进行了修复，有问题请再反馈
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
