### ISSUE TITLE
Mining Problems with HPool !!!! CAREFUL NOW

### ISSUE THREAD

**Issue by nflows** [hpool-dev/chia-miner#671]
Again there are Issues with mining HPool. It is mining in GUI with FULL SPACE but online all the time miner is going offline. EVEN IT IS NOT:... Hack???? Scam?????

Definitively stopping to Farm via HPool. You had enough time to make a proper pool... 
Bye

**Comment by trying2016** [comment]
If Miner is offline or there is no task, the firewall may cause the connection to fail. It is recommended to update to version 1.4.2 and choose the Japanese route
https://github.com/hpool-dev/chia-miner/releases/tag/1.4.2
