### ISSUE TITLE
How to choose China/Japan line in YAML file?

### ISSUE THREAD

**Issue by jiangwei221** [hpool-dev/chia-miner#672]
Hi:
Version 1.4.2 supported China and Japan line, how can I set it in the YAML file?
Thanks!

**Comment by kellenkuo** [comment]
> Hi:
> Version 1.4.2 supported China and Japan line, how can I set it in the YAML file?
> Thanks!

Unfortunately, You can't set it in the YAML file. Instead you have to setup x-proxy which hpool provide and config proxy in the YAML file, then you can change Japan line in x-proxy config webpage.
Hope this will help you^^

**Comment by trying2016** [comment]
Add line: jp in YAML

**Comment by BVVSL9** [comment]
> Add line: jp in YAML

of Hpool YAML or Xproxy
please give an example
