### ISSUE TITLE
用linux接矿池运行hpool-miner-chia报错

### ISSUE THREAD

**Issue by zhouchiyan82** [hpool-dev/chia-miner#68]
这个是什么原因导致的？？不是文件问题，GUI是可以用的，但是linux使用就会报这个错误
INFO[2021-04-30T20:40:24+08:00] update line fail                              error="Get \"https://chia.hpool.com/proxy/wslines\": dial tcp: lookup chia.hpool.com on [fd4d:2220:9517::1]:53: dial udp [fd4d:2220:9517::1]:53: connect: network is unreachable" file=loggers.go func=logging.CPrint line=168 tid=1

**Comment by LXY1226** [comment]
dns设置错了

**Comment by zhouchiyan82** [comment]
> dns设置错了

你好是我群辉的DNS么？主网的DNS没动过，我2台不同网络的收割机都出现过这个问题

**Comment by zhouchiyan82** [comment]
> dns设置错了

谢谢你的提醒，修改之后可以正常使用了，感谢大佬
