### ISSUE TITLE
关掉1.0.5，打开1.1.0然后关掉，二者仍在后台运行

### ISSUE THREAD

**Issue by codename10086** [hpool-dev/chia-miner#69]
如何完全退出这个程序？不想重启，因为还在Plotting，但后台运行两个挖矿程序，而且在线算力也重复显示。

**Comment by trying2016** [comment]
v1.1.1 版本修复了该问题，请使用最新版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1
