### ISSUE TITLE
Huge memory leak, v1.5.1(Build 3)

### ISSUE THREAD

**Issue by strmt7** [hpool-dev/chia-miner#690]
I have 32GB of ram on my pc, however the latest version of HPool-Miner-Chia-og appears to eat up all available ram when left open for extended periods of time. This causes all sorts of problems and hiccups on my pc. Please fix ASAP!

**Comment by nuezito** [comment]
Same problem with 64 GB Ram and 120Gb Virtual Memory. The latest version of HPool-Miner-Chia-og is a Bug!!!!. And 15 Days the developers doing nothing.!!

**Comment by trying2016** [comment]
Caused by the windows file system cache, the problem has been fixed in v1.5.2
https://github.com/hpool-dev/chia-miner/releases
