### ISSUE TITLE
Memory leak Hpool-Miner-Chia v1.1.0

### ISSUE THREAD

**Issue by SametBasturkk** [hpool-dev/chia-miner#70]
Hpool-Miner-Chia v1.1.0 using 750 mb ram. Its not make sense. 1.0.5 was using 50 mb. I return backed to 1.0.5

**Comment by PPGOli** [comment]
Beware that the project has no source code deposit. It might be a complete scam...

**Comment by h9-dev** [comment]
> Beware that the project has no source code deposit. It might be a complete scam...

The Office,Windows,MacOS,iOS is opensource ?

**Comment by h9-dev** [comment]
> Hpool-Miner-Chia v1.1.0 using 750 mb ram. Its not make sense. 1.0.5 was using 50 mb. I return backed to 1.0.5

Please use v1.1.1 .
