### ISSUE TITLE
x-proxy 1.0.7-1 - (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by silentsc** [hpool-dev/chia-miner#710]
There seems to be occasionally issue with the reconnection, where chia unable to reconnect.

2021/09/16 22:52:06 [I] new mining info, chain: Chia height: 867577 jobId: 4263607391 enable:true
2021/09/16 22:52:14 [I] new mining info, chain: Chia height: 867577 jobId: 2898986594 enable:true
2021/09/16 22:52:20 [I] new mining info, chain: Mass height: 1533082 jobId: 442085307 enable:true
2021/09/16 22:52:32 [I] new mining info, chain: Mass height: 1533083 jobId: 3648607773 enable:true
2021/09/16 22:52:34 [E] read message fail, error websocket: close 1006 (abnormal closure): unexpected EOF
2021/09/16 22:52:35 [I] connect success Mass wss://mass-sh01.hpool.com/x-proxynode/ws mass0000xxxxx
2021/09/16 22:52:58 [I] total client count:1 need close count:0
2021/09/16 22:53:06 [I] new mining info, chain: Mass height: 1533084 jobId: 3127583800 enable:true
2021/09/16 22:53:58 [I] total client count:1 need close count:0
2021/09/16 22:54:07 [I] new mining info, chain: Mass height: 1533085 jobId: 1125162892 enable:true
2021/09/16 22:54:58 [I] total client count:1 need close count:0
2021/09/16 22:55:29 [I] new mining info, chain: Mass height: 1533086 jobId: 587673920 enable:true
2021/09/16 22:55:58 [I] total client count:1 need close count:0
2021/09/16 22:56:44 [I] new mining info, chain: Mass height: 1533087 jobId: 3527082367 enable:true
2021/09/16 22:56:58 [I] total client count:1 need close count:0
2021/09/16 22:57:21 [I] new mining info, chain: Mass height: 1533088 jobId: 3487930031 enable:true
2021/09/16 22:57:51 [I] new mining info, chain: Mass height: 1533089 jobId: 3976671744 enable:true

Above are logs from the x-proxy.

Intermittent issue and hopefully the xproxy able to build some connection checking to reconnect if there connection lost.

**Comment by trying2016** [comment]
After the link fails, it will automatically re-link
