### ISSUE TITLE
HPOOL Service Wechat problem

### ISSUE THREAD

**Issue by xguya** [hpool-dev/chia-miner#73]
Hello, 
I can't open a wecaht account because wechat as me friend confirmation and I haven't friend with wechat. Can you add some alternative please? Telegram for example.

**Comment by codename10086** [comment]
It has Google Authenticator option.

**Comment by xguya** [comment]
Yes but online support is only with wechat.

**Comment by h9-dev** [comment]
Please use Google Authenticator. if you cannot use wechat.
