### ISSUE TITLE
好久可以有ARM版？ 不出ARM版可以开放源码，我们来编译呀。

### ISSUE THREAD

**Issue by betterA** [hpool-dev/chia-miner#77]
好久可以有ARM版？ 不出ARM版可以开放源码，我们来编译呀。

**Comment by PPGOli** [comment]
I did not find the source code deposit behind this project. It might be a complete scam?

**Comment by MBTimY** [comment]
支持出ARM版本的, 挖矿大家还是ARM的机器比较多呀.

**Comment by StormYudi** [comment]
坐等ARM版本！

**Comment by h9-dev** [comment]
有 ARM 设备的朋友们请联系客服，帮我做一次测试。
感谢！

----

有 ARM 設備的朋友們請聯繫客服，幫我做一次測試。
感謝！

----

Friends who have ARM devices, please contact customer service to help me do a test.
thank!

----

Друзья, у которых есть устройства ARM, свяжитесь со службой поддержки, чтобы помочь мне провести тест.
благодарить!

**Comment by krypdkat** [comment]
> 有 ARM 设备的朋友们请联系客服，帮我做一次测试。
> 感谢！
> 
> 有 ARM 設備的朋友們請聯繫客服，幫我做一次測試。
> 感謝！
> 
> Friends who have ARM devices, please contact customer service to help me do a test.
> thank!
> 
> Друзья, у которых есть устройства ARM, свяжитесь со службой поддержки, чтобы помочь мне провести тест.
> благодарить!

how to contact customer service... ?

**Comment by trying2016** [comment]
需要arm的请联系 官方客服微信：17717291449

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
