### ISSUE TITLE
Beware - There is no source code deposit behind this project - POSSIBLY SCAM???

### ISSUE THREAD

**Issue by PPGOli** [hpool-dev/chia-miner#78]
As you refuse to post the source code as supposed on Github and closing without reply I will keep posting. Also sending an inquiry to Github

**Comment by PPGOli** [comment]
Nobody wants to steal from you. Basically most of the code will be from Chia project anyway. So why keep it in secret if there is nothing malicious?

**Comment by hotcpu1949** [comment]
我来帮这位外国老哥直译一下供大家参考（按照github和开源的相关规则，github上这样的项目应该发布全部源代码。当然了，po主不想放源码的原因，呵呵，就不用解释了吧）

“小心！这项目没有放出源码，可能是蠕虫病毒/木马？”
“没人想偷你们的项目，反正大部分基础代码都是从奇亚项目里来的。所以你们干嘛搞的神神秘秘？”
“如果你们还拒绝放出代码，拒不回复并且关闭这个问题（不让其他人看到），我会一直重复发布并向github发起调查举报”

**Comment by h9-dev** [comment]
随意吧，开心就好！
Feel free, just be happy.
