### ISSUE TITLE
程序显示new mining info ，后台在线矿机和离线矿机为空

### ISSUE THREAD

**Issue by 85256638** [hpool-dev/chia-miner#79]
![image](https://user-images.githubusercontent.com/3270742/116821241-0779a980-ab71-11eb-9486-c4611e7ae031.png)
![image](https://user-images.githubusercontent.com/3270742/116821262-182a1f80-ab71-11eb-8031-e60407825638.png)

程序已经更新到 v1.1.1
这个问题也被其他人问过很多次，但是每次都被close了，也没有说出任何解决办法，
是要等几个小时后之后网页自己就更新了吗？？麻烦说清楚一些，谢谢了！ 帮助网页有不说这个，然后客服也加不上

**Comment by 95289527** [comment]
我也觉得这个有问题 要不就挖矿日志报个错也行啊 明明没报错矿池又没有算力

**Comment by 85256638** [comment]
> 我也觉得这个有问题 要不就挖矿日志报个错也行啊 明明没报错矿池又没有算力

![image](https://user-images.githubusercontent.com/3270742/116823708-cd62d480-ab7d-11eb-822b-14db660c50bb.png)
更新一下，我的在线算力有显示了， 大概等了一个多小时吧

**Comment by 85256638** [comment]
> 我也觉得这个有问题 要不就挖矿日志报个错也行啊 明明没报错矿池又没有算力

![image](https://user-images.githubusercontent.com/3270742/116823728-fa16ec00-ab7d-11eb-8695-e33b82810a03.png)

贡献点也有显示了

**Comment by h9-dev** [comment]
第一次在线需要等1小时才能看到在线算力。
