### ISSUE TITLE
centos 7.4 段错误

### ISSUE THREAD

**Issue by NirHeaven** [hpool-dev/chia-miner#8]
能不能编译一个兼容centos 7.4的程序啊？或者release源码我自己编译

**Comment by h9-dev** [comment]
可能centos 自带的libgcc 版本太低了，我们后面会对齐做静态链接。目前建议你使用 docker 安装 ubuntu 20.04以解决在 centos 上运行的问题。

**Comment by NirHeaven** [comment]
是gcc版本老么？还是libc？我这边libc是2.17的，gcc版本我可以升级啊

**Comment by NirHeaven** [comment]
你说的是glibc吧？这个我这是真没辙，我这边P完了没有空间搭建docker了，能告知下啥时候能安排上嘛

**Comment by NirHeaven** [comment]
而且这个程序还是静态依赖的。。。
