### ISSUE TITLE
3号6点之后P的图都无法加入到算力里面

### ISSUE THREAD

**Issue by wc357** [hpool-dev/chia-miner#85]

**Comment by h9-dev** [comment]
> 3号6点之后P的图都无法加入到算力里面，1.1.1显示总容量增加了，但是网站的在线算力没增加，贡献点也没上升。
> 重启也没用，1.1.1里面看所有plot文件显示都为有效。
> 怀疑被内部盗用，之后的P的图都挂到SOLO里面了。

请提供你的账号给客服，帮你查验。新的算力产生贡献点需要等1小时，不要频繁重启 miner。

**Comment by wc357** [comment]
***@***.***&nbsp;
1小时肯定超了，尝试过各种方式。最后多挂了一个plot在miner看算力会不会增加，然而今天6点到现在算力0增长




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HPool ***@***.***&gt;; 
发送时间: 2021年5月3日(星期一) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hpool-dev/chia-miner] 3号6点之后P的图都无法加入到算力里面 (#85)





  
3号6点之后P的图都无法加入到算力里面，1.1.1显示总容量增加了，但是网站的在线算力没增加，贡献点也没上升。
 重启也没用，1.1.1里面看所有plot文件显示都为有效。
 怀疑被内部盗用，之后的P的图都挂到SOLO里面了。
  
请提供你的账号给客服，帮你查验。新的算力产生贡献点需要等1小时，不要频繁重启 miner。

**Comment by wc357** [comment]
***@***.***&nbsp;
是7点 说成6点了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] 3号6点之后P的图都无法加入到算力里面 (#85)





  
3号6点之后P的图都无法加入到算力里面，1.1.1显示总容量增加了，但是网站的在线算力没增加，贡献点也没上升。
 重启也没用，1.1.1里面看所有plot文件显示都为有效。
 怀疑被内部盗用，之后的P的图都挂到SOLO里面了。
  
请提供你的账号给客服，帮你查验。新的算力产生贡献点需要等1小时，不要频繁重启 miner。

**Comment by wc357** [comment]
有了。可能是白天的时候算力刷新时间比平时长弄了半天没刷出来。谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] 3号6点之后P的图都无法加入到算力里面 (#85)





  
3号6点之后P的图都无法加入到算力里面，1.1.1显示总容量增加了，但是网站的在线算力没增加，贡献点也没上升。
 重启也没用，1.1.1里面看所有plot文件显示都为有效。
 怀疑被内部盗用，之后的P的图都挂到SOLO里面了。
  
请提供你的账号给客服，帮你查验。新的算力产生贡献点需要等1小时，不要频繁重启 miner。

**Comment by wc357** [comment]
有了。可能是白天的时候算力刷新时间比平时长弄了半天没刷出来。谢谢。
