### ISSUE TITLE
linux 的hpool矿池持续有严重问题，log提示正常，单网站上无法显示在线矿机和在线算力，同等条件下windows版本就能正常显示

### ISSUE THREAD

**Issue by whatsappfree** [hpool-dev/chia-miner#86]
linux 的hpool矿池持续有严重问题，log提示正常，单网站上无法显示在线矿机和在线算力，同等条件下windows版本就能正常显示

**Comment by trying2016** [comment]
请更新v1.1.1版本

**Comment by trying2016** [comment]
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by frostashe** [comment]
> 请更新v1.1.1版本

更新到v1.1.1反而出现这个问题，日志没有异常信息，算例全部丢失，需要重启程序才能将算力上线

**Comment by trying2016** [comment]
v1.1.1版本更新过几次，建议重新下载，试试。

**Comment by Lixiaobai233** [comment]
上线多长时间出在线算力？linux版本。

**Comment by trying2016** [comment]
算力在线时间为1小时，矿机在线时间在10分钟左右

**Comment by zjshen14** [comment]
是不是得算力非0以后才能在矿池里看到在线矿机？

**Comment by zjshen14** [comment]
@trying2016

**Comment by whatsappfree** [comment]
我找到问题的原因了，在linux下使用webdav挂载网络硬盘，就会出现这样的错误，应该是程序不兼容，plot文件放在本地硬盘就不会出错。
