### ISSUE TITLE
算力和收益不匹配

### ISSUE THREAD

**Issue by arandomg** [hpool-dev/chia-miner#89]
以HPOOL截图时间(21/05/04-03:17 GMT+8)为例

全网难度1750.59，矿池算力801.98，理论上矿池占据全网的**45.81%**
全网24小时产出块4608，矿池产出1432，矿池占**31.08%**

**请问少的1/3收益去哪了？**
<img width="890" alt="hpool21-5-4-03-17GMT8" src="https://user-images.githubusercontent.com/83610215/116922425-5da72500-ac23-11eb-9a90-9ec518498822.png">

**Comment by h9-dev** [comment]
全网难度是基于历史的统计，实际的难度比这个大。
