### ISSUE TITLE
新版必须输入矿池API？

### ISSUE THREAD

**Issue by moremoneylessproblem** [hpool-dev/chia-miner#9]
1.0.4.1必须输入你们的矿池API才可以访问？上一个版本只要定义P F两个KEY就可以了，这个版本已经绑定必须输入你的矿池API了？

**Comment by h9-dev** [comment]
> 1.0.4.1必须输入你们的矿池API才可以访问？上一个版本只要定义P F两个KEY就可以了，这个版本已经绑定必须输入你的矿池API了？

Farmer public key 和 Pool public key 是 P 盘用的，miner 不使用这两个 key，您是否混淆了 plotter 和 miner。我们 非 GUI 版本的miner 一直可以通过 APIKEY 配置的。
