### ISSUE TITLE
经常会崩溃

### ISSUE THREAD

**Issue by OscarSheng** [hpool-dev/chia-miner#90]
不知道是不是因为我同时在p盘， 已经出现很多次无故闪退了

**Comment by h9-dev** [comment]
是不是内存内 Plotter 用完了？

**Comment by OscarSheng** [comment]
有可能，但是用完了也不至于闪退吧，我显卡挖矿的软件都没事？

**Comment by trying2016** [comment]
请重新下载v1.1.1版本
https://github.com/hpool-dev/chia-miner/releases/tag/v1.1.1

**Comment by OscarSheng** [comment]
我用的就是这个版本

**Comment by trying2016** [comment]
v1.1.1中间更新过多次，建议重新下载，确保是最新的

**Comment by trying2016** [comment]
1.2.0版本对崩溃问题进行了修复，有问题请再反馈
https://github.com/hpool-dev/chia-miner/releases/tag/v1.2.0-1
