### ISSUE TITLE
在线算力更新间隔

### ISSUE THREAD

**Issue by HarukaMa** [hpool-dev/chia-miner#91]
现在似乎在线算力要启动后一小时才会更新，之后每两小时才会更新。但我们现在没几分钟到十几分钟就会有新 plot 上线，并且能正确反映到矿机列表里。

请问为什么更新间隔要这么长？两小时的设计原因是什么？

**Comment by h9-dev** [comment]
为了防止频繁的关闭、重启矿机，导致错过任务而影响大家的收益。

**Comment by HarukaMa** [comment]
> 为了防止频繁的关闭、重启矿机，导致错过任务而影响大家的收益。

这只解答了启动后一小时的延迟，但之后更新的那么慢是什么原因？

**Comment by h9-dev** [comment]
K32大约100G一个文件，800P 就是800万 个文件。过短的证明提交对服务器压力太大，几乎等于 DDoS。

**Comment by arandomg** [comment]
> K32大约100G一个文件，800P 就是800万 个文件。过短的证明提交对服务器压力太大，几乎等于 DDoS。

又不是每分钟新增800万个，为什么流量很大？
